// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/tracker/internal/tracker/model"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// DisconnectZoomLocal provides a mock function with given fields: ctx, userID
func (_m *Store) DisconnectZoomLocal(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DisconnectZoomLocal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DisconnectZoomLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectZoomLocal'
type Store_DisconnectZoomLocal_Call struct {
	*mock.Call
}

// DisconnectZoomLocal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) DisconnectZoomLocal(ctx interface{}, userID interface{}) *Store_DisconnectZoomLocal_Call {
	return &Store_DisconnectZoomLocal_Call{Call: _e.mock.On("DisconnectZoomLocal", ctx, userID)}
}

func (_c *Store_DisconnectZoomLocal_Call) Run(run func(ctx context.Context, userID string)) *Store_DisconnectZoomLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_DisconnectZoomLocal_Call) Return(_a0 error) *Store_DisconnectZoomLocal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DisconnectZoomLocal_Call) RunAndReturn(run func(context.Context, string) error) *Store_DisconnectZoomLocal_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSettings provides a mock function with given fields: ctx, userID
func (_m *Store) GetUserSettings(ctx context.Context, userID string) (*model.UserSettings, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSettings")
	}

	var r0 *model.UserSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserSettings, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserSettings); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetUserSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSettings'
type Store_GetUserSettings_Call struct {
	*mock.Call
}

// GetUserSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) GetUserSettings(ctx interface{}, userID interface{}) *Store_GetUserSettings_Call {
	return &Store_GetUserSettings_Call{Call: _e.mock.On("GetUserSettings", ctx, userID)}
}

func (_c *Store_GetUserSettings_Call) Run(run func(ctx context.Context, userID string)) *Store_GetUserSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetUserSettings_Call) Return(_a0 *model.UserSettings, _a1 error) *Store_GetUserSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetUserSettings_Call) RunAndReturn(run func(context.Context, string) (*model.UserSettings, error)) *Store_GetUserSettings_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkTasksByUser provides a mock function with given fields: ctx, userID
func (_m *Store) ListWorkTasksByUser(ctx context.Context, userID string) ([]model.WorkTask, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkTasksByUser")
	}

	var r0 []model.WorkTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.WorkTask, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.WorkTask); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.WorkTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListWorkTasksByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkTasksByUser'
type Store_ListWorkTasksByUser_Call struct {
	*mock.Call
}

// ListWorkTasksByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) ListWorkTasksByUser(ctx interface{}, userID interface{}) *Store_ListWorkTasksByUser_Call {
	return &Store_ListWorkTasksByUser_Call{Call: _e.mock.On("ListWorkTasksByUser", ctx, userID)}
}

func (_c *Store_ListWorkTasksByUser_Call) Run(run func(ctx context.Context, userID string)) *Store_ListWorkTasksByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ListWorkTasksByUser_Call) Return(_a0 []model.WorkTask, _a1 error) *Store_ListWorkTasksByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListWorkTasksByUser_Call) RunAndReturn(run func(context.Context, string) ([]model.WorkTask, error)) *Store_ListWorkTasksByUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkZoomReauthRequired provides a mock function with given fields: ctx, userID
func (_m *Store) MarkZoomReauthRequired(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkZoomReauthRequired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_MarkZoomReauthRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkZoomReauthRequired'
type Store_MarkZoomReauthRequired_Call struct {
	*mock.Call
}

// MarkZoomReauthRequired is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) MarkZoomReauthRequired(ctx interface{}, userID interface{}) *Store_MarkZoomReauthRequired_Call {
	return &Store_MarkZoomReauthRequired_Call{Call: _e.mock.On("MarkZoomReauthRequired", ctx, userID)}
}

func (_c *Store_MarkZoomReauthRequired_Call) Run(run func(ctx context.Context, userID string)) *Store_MarkZoomReauthRequired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_MarkZoomReauthRequired_Call) Return(_a0 error) *Store_MarkZoomReauthRequired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_MarkZoomReauthRequired_Call) RunAndReturn(run func(context.Context, string) error) *Store_MarkZoomReauthRequired_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
