// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/sandbox/internal/sandbox/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// ClaimQueuedRuns provides a mock function with given fields: ctx, limit, leaseDuration
func (_m *Store) ClaimQueuedRuns(ctx context.Context, limit int, leaseDuration time.Duration) ([]model.CodeRun, error) {
	ret := _m.Called(ctx, limit, leaseDuration)

	if len(ret) == 0 {
		panic("no return value specified for ClaimQueuedRuns")
	}

	var r0 []model.CodeRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, time.Duration) ([]model.CodeRun, error)); ok {
		return rf(ctx, limit, leaseDuration)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, time.Duration) []model.CodeRun); ok {
		r0 = rf(ctx, limit, leaseDuration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CodeRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, time.Duration) error); ok {
		r1 = rf(ctx, limit, leaseDuration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ClaimQueuedRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimQueuedRuns'
type Store_ClaimQueuedRuns_Call struct {
	*mock.Call
}

// ClaimQueuedRuns is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - leaseDuration time.Duration
func (_e *Store_Expecter) ClaimQueuedRuns(ctx interface{}, limit interface{}, leaseDuration interface{}) *Store_ClaimQueuedRuns_Call {
	return &Store_ClaimQueuedRuns_Call{Call: _e.mock.On("ClaimQueuedRuns", ctx, limit, leaseDuration)}
}

func (_c *Store_ClaimQueuedRuns_Call) Run(run func(ctx context.Context, limit int, leaseDuration time.Duration)) *Store_ClaimQueuedRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(time.Duration))
	})
	return _c
}

func (_c *Store_ClaimQueuedRuns_Call) Return(_a0 []model.CodeRun, _a1 error) *Store_ClaimQueuedRuns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ClaimQueuedRuns_Call) RunAndReturn(run func(context.Context, int, time.Duration) ([]model.CodeRun, error)) *Store_ClaimQueuedRuns_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function with given fields: ctx, run
func (_m *Store) Complete(ctx context.Context, run *model.CodeRun) error {
	ret := _m.Called(ctx, run)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CodeRun) error); ok {
		r0 = rf(ctx, run)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type Store_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - run *model.CodeRun
func (_e *Store_Expecter) Complete(ctx interface{}, run interface{}) *Store_Complete_Call {
	return &Store_Complete_Call{Call: _e.mock.On("Complete", ctx, run)}
}

func (_c *Store_Complete_Call) Run(run func(ctx context.Context, run *model.CodeRun)) *Store_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.CodeRun))
	})
	return _c
}

func (_c *Store_Complete_Call) Return(_a0 error) *Store_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_Complete_Call) RunAndReturn(run func(context.Context, *model.CodeRun) error) *Store_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
