// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/sandbox/internal/sandbox/model"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: ctx, run
func (_m *Store) Complete(ctx context.Context, run *model.CodeRun) error {
	ret := _m.Called(ctx, run)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CodeRun) error); ok {
		r0 = rf(ctx, run)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type Store_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - run *model.CodeRun
func (_e *Store_Expecter) Complete(ctx interface{}, run interface{}) *Store_Complete_Call {
	return &Store_Complete_Call{Call: _e.mock.On("Complete", ctx, run)}
}

func (_c *Store_Complete_Call) Run(run func(ctx context.Context, run *model.CodeRun)) *Store_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.CodeRun))
	})
	return _c
}

func (_c *Store_Complete_Call) Return(_a0 error) *Store_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_Complete_Call) RunAndReturn(run func(context.Context, *model.CodeRun) error) *Store_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, run, limits
func (_m *Store) Create(ctx context.Context, run *model.CodeRun, limits model.RunLimits) error {
	ret := _m.Called(ctx, run, limits)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CodeRun, model.RunLimits) error); ok {
		r0 = rf(ctx, run, limits)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Store_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - run *model.CodeRun
//   - limits model.RunLimits
func (_e *Store_Expecter) Create(ctx interface{}, run interface{}, limits interface{}) *Store_Create_Call {
	return &Store_Create_Call{Call: _e.mock.On("Create", ctx, run, limits)}
}

func (_c *Store_Create_Call) Run(run func(ctx context.Context, run *model.CodeRun, limits model.RunLimits)) *Store_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.CodeRun), args[2].(model.RunLimits))
	})
	return _c
}

func (_c *Store_Create_Call) Return(_a0 error) *Store_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_Create_Call) RunAndReturn(run func(context.Context, *model.CodeRun, model.RunLimits) error) *Store_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
