// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/notes/internal/notes/model"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// GetPublishedNoteRecordBySlug provides a mock function with given fields: ctx, slug
func (_m *Store) GetPublishedNoteRecordBySlug(ctx context.Context, slug string) (*model.PublishedNoteRecord, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishedNoteRecordBySlug")
	}

	var r0 *model.PublishedNoteRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.PublishedNoteRecord, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.PublishedNoteRecord); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PublishedNoteRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetPublishedNoteRecordBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublishedNoteRecordBySlug'
type Store_GetPublishedNoteRecordBySlug_Call struct {
	*mock.Call
}

// GetPublishedNoteRecordBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *Store_Expecter) GetPublishedNoteRecordBySlug(ctx interface{}, slug interface{}) *Store_GetPublishedNoteRecordBySlug_Call {
	return &Store_GetPublishedNoteRecordBySlug_Call{Call: _e.mock.On("GetPublishedNoteRecordBySlug", ctx, slug)}
}

func (_c *Store_GetPublishedNoteRecordBySlug_Call) Run(run func(ctx context.Context, slug string)) *Store_GetPublishedNoteRecordBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetPublishedNoteRecordBySlug_Call) Return(_a0 *model.PublishedNoteRecord, _a1 error) *Store_GetPublishedNoteRecordBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetPublishedNoteRecordBySlug_Call) RunAndReturn(run func(context.Context, string) (*model.PublishedNoteRecord, error)) *Store_GetPublishedNoteRecordBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
