// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	jwt "github.com/dobriygolang/project-nordly/services/identity/pkg/jwt"

	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ScopedTokenIssuer is an autogenerated mock type for the ScopedTokenIssuer type
type ScopedTokenIssuer struct {
	mock.Mock
}

type ScopedTokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *ScopedTokenIssuer) EXPECT() *ScopedTokenIssuer_Expecter {
	return &ScopedTokenIssuer_Expecter{mock: &_m.Mock}
}

// IssueScopedAccessToken provides a mock function with given fields: userID, role, scope, displayName, ttl
func (_m *ScopedTokenIssuer) IssueScopedAccessToken(userID string, role jwt.Role, scope jwt.EditorScope, displayName string, ttl time.Duration) (string, error) {
	ret := _m.Called(userID, role, scope, displayName, ttl)

	if len(ret) == 0 {
		panic("no return value specified for IssueScopedAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, jwt.Role, jwt.EditorScope, string, time.Duration) (string, error)); ok {
		return rf(userID, role, scope, displayName, ttl)
	}
	if rf, ok := ret.Get(0).(func(string, jwt.Role, jwt.EditorScope, string, time.Duration) string); ok {
		r0 = rf(userID, role, scope, displayName, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, jwt.Role, jwt.EditorScope, string, time.Duration) error); ok {
		r1 = rf(userID, role, scope, displayName, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScopedTokenIssuer_IssueScopedAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueScopedAccessToken'
type ScopedTokenIssuer_IssueScopedAccessToken_Call struct {
	*mock.Call
}

// IssueScopedAccessToken is a helper method to define mock.On call
//   - userID string
//   - role jwt.Role
//   - scope jwt.EditorScope
//   - displayName string
//   - ttl time.Duration
func (_e *ScopedTokenIssuer_Expecter) IssueScopedAccessToken(userID interface{}, role interface{}, scope interface{}, displayName interface{}, ttl interface{}) *ScopedTokenIssuer_IssueScopedAccessToken_Call {
	return &ScopedTokenIssuer_IssueScopedAccessToken_Call{Call: _e.mock.On("IssueScopedAccessToken", userID, role, scope, displayName, ttl)}
}

func (_c *ScopedTokenIssuer_IssueScopedAccessToken_Call) Run(run func(userID string, role jwt.Role, scope jwt.EditorScope, displayName string, ttl time.Duration)) *ScopedTokenIssuer_IssueScopedAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(jwt.Role), args[2].(jwt.EditorScope), args[3].(string), args[4].(time.Duration))
	})
	return _c
}

func (_c *ScopedTokenIssuer_IssueScopedAccessToken_Call) Return(_a0 string, _a1 error) *ScopedTokenIssuer_IssueScopedAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScopedTokenIssuer_IssueScopedAccessToken_Call) RunAndReturn(run func(string, jwt.Role, jwt.EditorScope, string, time.Duration) (string, error)) *ScopedTokenIssuer_IssueScopedAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewScopedTokenIssuer creates a new instance of ScopedTokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScopedTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScopedTokenIssuer {
	mock := &ScopedTokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
