// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/tracker/internal/tracker/model"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// GetEpic provides a mock function with given fields: ctx, epicID, userID
func (_m *Store) GetEpic(ctx context.Context, epicID string, userID string) (*model.Epic, error) {
	ret := _m.Called(ctx, epicID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetEpic")
	}

	var r0 *model.Epic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Epic, error)); ok {
		return rf(ctx, epicID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Epic); ok {
		r0 = rf(ctx, epicID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Epic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, epicID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetEpic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEpic'
type Store_GetEpic_Call struct {
	*mock.Call
}

// GetEpic is a helper method to define mock.On call
//   - ctx context.Context
//   - epicID string
//   - userID string
func (_e *Store_Expecter) GetEpic(ctx interface{}, epicID interface{}, userID interface{}) *Store_GetEpic_Call {
	return &Store_GetEpic_Call{Call: _e.mock.On("GetEpic", ctx, epicID, userID)}
}

func (_c *Store_GetEpic_Call) Run(run func(ctx context.Context, epicID string, userID string)) *Store_GetEpic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_GetEpic_Call) Return(_a0 *model.Epic, _a1 error) *Store_GetEpic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetEpic_Call) RunAndReturn(run func(context.Context, string, string) (*model.Epic, error)) *Store_GetEpic_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSettings provides a mock function with given fields: ctx, userID
func (_m *Store) GetUserSettings(ctx context.Context, userID string) (*model.UserSettings, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSettings")
	}

	var r0 *model.UserSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserSettings, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserSettings); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetUserSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSettings'
type Store_GetUserSettings_Call struct {
	*mock.Call
}

// GetUserSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) GetUserSettings(ctx interface{}, userID interface{}) *Store_GetUserSettings_Call {
	return &Store_GetUserSettings_Call{Call: _e.mock.On("GetUserSettings", ctx, userID)}
}

func (_c *Store_GetUserSettings_Call) Run(run func(ctx context.Context, userID string)) *Store_GetUserSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetUserSettings_Call) Return(_a0 *model.UserSettings, _a1 error) *Store_GetUserSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetUserSettings_Call) RunAndReturn(run func(context.Context, string) (*model.UserSettings, error)) *Store_GetUserSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkTask provides a mock function with given fields: ctx, taskID, userID
func (_m *Store) GetWorkTask(ctx context.Context, taskID string, userID string) (*model.WorkTask, error) {
	ret := _m.Called(ctx, taskID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkTask")
	}

	var r0 *model.WorkTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.WorkTask, error)); ok {
		return rf(ctx, taskID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.WorkTask); ok {
		r0 = rf(ctx, taskID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WorkTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, taskID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetWorkTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkTask'
type Store_GetWorkTask_Call struct {
	*mock.Call
}

// GetWorkTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - userID string
func (_e *Store_Expecter) GetWorkTask(ctx interface{}, taskID interface{}, userID interface{}) *Store_GetWorkTask_Call {
	return &Store_GetWorkTask_Call{Call: _e.mock.On("GetWorkTask", ctx, taskID, userID)}
}

func (_c *Store_GetWorkTask_Call) Run(run func(ctx context.Context, taskID string, userID string)) *Store_GetWorkTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_GetWorkTask_Call) Return(_a0 *model.WorkTask, _a1 error) *Store_GetWorkTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetWorkTask_Call) RunAndReturn(run func(context.Context, string, string) (*model.WorkTask, error)) *Store_GetWorkTask_Call {
	_c.Call.Return(run)
	return _c
}

// MarkGoogleReauthRequired provides a mock function with given fields: ctx, userID
func (_m *Store) MarkGoogleReauthRequired(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkGoogleReauthRequired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_MarkGoogleReauthRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkGoogleReauthRequired'
type Store_MarkGoogleReauthRequired_Call struct {
	*mock.Call
}

// MarkGoogleReauthRequired is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) MarkGoogleReauthRequired(ctx interface{}, userID interface{}) *Store_MarkGoogleReauthRequired_Call {
	return &Store_MarkGoogleReauthRequired_Call{Call: _e.mock.On("MarkGoogleReauthRequired", ctx, userID)}
}

func (_c *Store_MarkGoogleReauthRequired_Call) Run(run func(ctx context.Context, userID string)) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_MarkGoogleReauthRequired_Call) Return(_a0 error) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_MarkGoogleReauthRequired_Call) RunAndReturn(run func(context.Context, string) error) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Return(run)
	return _c
}

// MarkZoomReauthRequired provides a mock function with given fields: ctx, userID
func (_m *Store) MarkZoomReauthRequired(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkZoomReauthRequired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_MarkZoomReauthRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkZoomReauthRequired'
type Store_MarkZoomReauthRequired_Call struct {
	*mock.Call
}

// MarkZoomReauthRequired is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) MarkZoomReauthRequired(ctx interface{}, userID interface{}) *Store_MarkZoomReauthRequired_Call {
	return &Store_MarkZoomReauthRequired_Call{Call: _e.mock.On("MarkZoomReauthRequired", ctx, userID)}
}

func (_c *Store_MarkZoomReauthRequired_Call) Run(run func(ctx context.Context, userID string)) *Store_MarkZoomReauthRequired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_MarkZoomReauthRequired_Call) Return(_a0 error) *Store_MarkZoomReauthRequired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_MarkZoomReauthRequired_Call) RunAndReturn(run func(context.Context, string) error) *Store_MarkZoomReauthRequired_Call {
	_c.Call.Return(run)
	return _c
}

// PatchWorkTask provides a mock function with given fields: ctx, taskID, userID, patch
func (_m *Store) PatchWorkTask(ctx context.Context, taskID string, userID string, patch model.WorkTaskPatch) (*model.WorkTask, error) {
	ret := _m.Called(ctx, taskID, userID, patch)

	if len(ret) == 0 {
		panic("no return value specified for PatchWorkTask")
	}

	var r0 *model.WorkTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.WorkTaskPatch) (*model.WorkTask, error)); ok {
		return rf(ctx, taskID, userID, patch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.WorkTaskPatch) *model.WorkTask); ok {
		r0 = rf(ctx, taskID, userID, patch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WorkTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.WorkTaskPatch) error); ok {
		r1 = rf(ctx, taskID, userID, patch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_PatchWorkTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchWorkTask'
type Store_PatchWorkTask_Call struct {
	*mock.Call
}

// PatchWorkTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - userID string
//   - patch model.WorkTaskPatch
func (_e *Store_Expecter) PatchWorkTask(ctx interface{}, taskID interface{}, userID interface{}, patch interface{}) *Store_PatchWorkTask_Call {
	return &Store_PatchWorkTask_Call{Call: _e.mock.On("PatchWorkTask", ctx, taskID, userID, patch)}
}

func (_c *Store_PatchWorkTask_Call) Run(run func(ctx context.Context, taskID string, userID string, patch model.WorkTaskPatch)) *Store_PatchWorkTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.WorkTaskPatch))
	})
	return _c
}

func (_c *Store_PatchWorkTask_Call) Return(_a0 *model.WorkTask, _a1 error) *Store_PatchWorkTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_PatchWorkTask_Call) RunAndReturn(run func(context.Context, string, string, model.WorkTaskPatch) (*model.WorkTask, error)) *Store_PatchWorkTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
