// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Zoom is an autogenerated mock type for the Zoom type
type Zoom struct {
	mock.Mock
}

type Zoom_Expecter struct {
	mock *mock.Mock
}

func (_m *Zoom) EXPECT() *Zoom_Expecter {
	return &Zoom_Expecter{mock: &_m.Mock}
}

// Configured provides a mock function with no fields
func (_m *Zoom) Configured() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Configured")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Zoom_Configured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configured'
type Zoom_Configured_Call struct {
	*mock.Call
}

// Configured is a helper method to define mock.On call
func (_e *Zoom_Expecter) Configured() *Zoom_Configured_Call {
	return &Zoom_Configured_Call{Call: _e.mock.On("Configured")}
}

func (_c *Zoom_Configured_Call) Run(run func()) *Zoom_Configured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Zoom_Configured_Call) Return(_a0 bool) *Zoom_Configured_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Zoom_Configured_Call) RunAndReturn(run func() bool) *Zoom_Configured_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMeeting provides a mock function with given fields: ctx, refreshToken, meetingID
func (_m *Zoom) DeleteMeeting(ctx context.Context, refreshToken string, meetingID string) error {
	ret := _m.Called(ctx, refreshToken, meetingID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMeeting")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, refreshToken, meetingID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Zoom_DeleteMeeting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMeeting'
type Zoom_DeleteMeeting_Call struct {
	*mock.Call
}

// DeleteMeeting is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - meetingID string
func (_e *Zoom_Expecter) DeleteMeeting(ctx interface{}, refreshToken interface{}, meetingID interface{}) *Zoom_DeleteMeeting_Call {
	return &Zoom_DeleteMeeting_Call{Call: _e.mock.On("DeleteMeeting", ctx, refreshToken, meetingID)}
}

func (_c *Zoom_DeleteMeeting_Call) Run(run func(ctx context.Context, refreshToken string, meetingID string)) *Zoom_DeleteMeeting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Zoom_DeleteMeeting_Call) Return(_a0 error) *Zoom_DeleteMeeting_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Zoom_DeleteMeeting_Call) RunAndReturn(run func(context.Context, string, string) error) *Zoom_DeleteMeeting_Call {
	_c.Call.Return(run)
	return _c
}

// NewZoom creates a new instance of Zoom. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewZoom(t interface {
	mock.TestingT
	Cleanup(func())
}) *Zoom {
	mock := &Zoom{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
