// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/focus/internal/focus/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// AbandonSessionsStartedBefore provides a mock function with given fields: ctx, cutoff, now
func (_m *Store) AbandonSessionsStartedBefore(ctx context.Context, cutoff time.Time, now time.Time) (int64, error) {
	ret := _m.Called(ctx, cutoff, now)

	if len(ret) == 0 {
		panic("no return value specified for AbandonSessionsStartedBefore")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (int64, error)); ok {
		return rf(ctx, cutoff, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) int64); ok {
		r0 = rf(ctx, cutoff, now)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, cutoff, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_AbandonSessionsStartedBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbandonSessionsStartedBefore'
type Store_AbandonSessionsStartedBefore_Call struct {
	*mock.Call
}

// AbandonSessionsStartedBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoff time.Time
//   - now time.Time
func (_e *Store_Expecter) AbandonSessionsStartedBefore(ctx interface{}, cutoff interface{}, now interface{}) *Store_AbandonSessionsStartedBefore_Call {
	return &Store_AbandonSessionsStartedBefore_Call{Call: _e.mock.On("AbandonSessionsStartedBefore", ctx, cutoff, now)}
}

func (_c *Store_AbandonSessionsStartedBefore_Call) Run(run func(ctx context.Context, cutoff time.Time, now time.Time)) *Store_AbandonSessionsStartedBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *Store_AbandonSessionsStartedBefore_Call) Return(_a0 int64, _a1 error) *Store_AbandonSessionsStartedBefore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_AbandonSessionsStartedBefore_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) (int64, error)) *Store_AbandonSessionsStartedBefore_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function with given fields: ctx, userID, mode, pinnedTitle, taskID, clientSessionID, startedAt
func (_m *Store) CreateSession(ctx context.Context, userID string, mode model.SessionMode, pinnedTitle string, taskID *string, clientSessionID *string, startedAt time.Time) (*model.Session, bool, error) {
	ret := _m.Called(ctx, userID, mode, pinnedTitle, taskID, clientSessionID, startedAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *model.Session
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.SessionMode, string, *string, *string, time.Time) (*model.Session, bool, error)); ok {
		return rf(ctx, userID, mode, pinnedTitle, taskID, clientSessionID, startedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.SessionMode, string, *string, *string, time.Time) *model.Session); ok {
		r0 = rf(ctx, userID, mode, pinnedTitle, taskID, clientSessionID, startedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.SessionMode, string, *string, *string, time.Time) bool); ok {
		r1 = rf(ctx, userID, mode, pinnedTitle, taskID, clientSessionID, startedAt)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, model.SessionMode, string, *string, *string, time.Time) error); ok {
		r2 = rf(ctx, userID, mode, pinnedTitle, taskID, clientSessionID, startedAt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Store_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type Store_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - mode model.SessionMode
//   - pinnedTitle string
//   - taskID *string
//   - clientSessionID *string
//   - startedAt time.Time
func (_e *Store_Expecter) CreateSession(ctx interface{}, userID interface{}, mode interface{}, pinnedTitle interface{}, taskID interface{}, clientSessionID interface{}, startedAt interface{}) *Store_CreateSession_Call {
	return &Store_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, mode, pinnedTitle, taskID, clientSessionID, startedAt)}
}

func (_c *Store_CreateSession_Call) Run(run func(ctx context.Context, userID string, mode model.SessionMode, pinnedTitle string, taskID *string, clientSessionID *string, startedAt time.Time)) *Store_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.SessionMode), args[3].(string), args[4].(*string), args[5].(*string), args[6].(time.Time))
	})
	return _c
}

func (_c *Store_CreateSession_Call) Return(_a0 *model.Session, _a1 bool, _a2 error) *Store_CreateSession_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Store_CreateSession_Call) RunAndReturn(run func(context.Context, string, model.SessionMode, string, *string, *string, time.Time) (*model.Session, bool, error)) *Store_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// EndSession provides a mock function with given fields: ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt
func (_m *Store) EndSession(ctx context.Context, userID string, sessionID string, secondsFocused int, pomodorosCompleted int, endedAt time.Time) (*model.Session, model.SessionEndOutcome, error) {
	ret := _m.Called(ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt)

	if len(ret) == 0 {
		panic("no return value specified for EndSession")
	}

	var r0 *model.Session
	var r1 model.SessionEndOutcome
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int, time.Time) (*model.Session, model.SessionEndOutcome, error)); ok {
		return rf(ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int, time.Time) *model.Session); ok {
		r0 = rf(ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int, time.Time) model.SessionEndOutcome); ok {
		r1 = rf(ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt)
	} else {
		r1 = ret.Get(1).(model.SessionEndOutcome)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, int, time.Time) error); ok {
		r2 = rf(ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Store_EndSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndSession'
type Store_EndSession_Call struct {
	*mock.Call
}

// EndSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
//   - secondsFocused int
//   - pomodorosCompleted int
//   - endedAt time.Time
func (_e *Store_Expecter) EndSession(ctx interface{}, userID interface{}, sessionID interface{}, secondsFocused interface{}, pomodorosCompleted interface{}, endedAt interface{}) *Store_EndSession_Call {
	return &Store_EndSession_Call{Call: _e.mock.On("EndSession", ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt)}
}

func (_c *Store_EndSession_Call) Run(run func(ctx context.Context, userID string, sessionID string, secondsFocused int, pomodorosCompleted int, endedAt time.Time)) *Store_EndSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int), args[5].(time.Time))
	})
	return _c
}

func (_c *Store_EndSession_Call) Return(_a0 *model.Session, _a1 model.SessionEndOutcome, _a2 error) *Store_EndSession_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Store_EndSession_Call) RunAndReturn(run func(context.Context, string, string, int, int, time.Time) (*model.Session, model.SessionEndOutcome, error)) *Store_EndSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByClientID provides a mock function with given fields: ctx, userID, clientSessionID
func (_m *Store) GetSessionByClientID(ctx context.Context, userID string, clientSessionID string) (*model.Session, error) {
	ret := _m.Called(ctx, userID, clientSessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByClientID")
	}

	var r0 *model.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Session, error)); ok {
		return rf(ctx, userID, clientSessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Session); ok {
		r0 = rf(ctx, userID, clientSessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, clientSessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetSessionByClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByClientID'
type Store_GetSessionByClientID_Call struct {
	*mock.Call
}

// GetSessionByClientID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - clientSessionID string
func (_e *Store_Expecter) GetSessionByClientID(ctx interface{}, userID interface{}, clientSessionID interface{}) *Store_GetSessionByClientID_Call {
	return &Store_GetSessionByClientID_Call{Call: _e.mock.On("GetSessionByClientID", ctx, userID, clientSessionID)}
}

func (_c *Store_GetSessionByClientID_Call) Run(run func(ctx context.Context, userID string, clientSessionID string)) *Store_GetSessionByClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_GetSessionByClientID_Call) Return(_a0 *model.Session, _a1 error) *Store_GetSessionByClientID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetSessionByClientID_Call) RunAndReturn(run func(context.Context, string, string) (*model.Session, error)) *Store_GetSessionByClientID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx, userID, upTo
func (_m *Store) GetStats(ctx context.Context, userID string, upTo time.Time) (*model.Stats, error) {
	ret := _m.Called(ctx, userID, upTo)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *model.Stats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*model.Stats, error)); ok {
		return rf(ctx, userID, upTo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *model.Stats); ok {
		r0 = rf(ctx, userID, upTo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Stats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, userID, upTo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type Store_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - upTo time.Time
func (_e *Store_Expecter) GetStats(ctx interface{}, userID interface{}, upTo interface{}) *Store_GetStats_Call {
	return &Store_GetStats_Call{Call: _e.mock.On("GetStats", ctx, userID, upTo)}
}

func (_c *Store_GetStats_Call) Run(run func(ctx context.Context, userID string, upTo time.Time)) *Store_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *Store_GetStats_Call) Return(_a0 *model.Stats, _a1 error) *Store_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetStats_Call) RunAndReturn(run func(context.Context, string, time.Time) (*model.Stats, error)) *Store_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
