// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/rooms/internal/room/model"
	mock "github.com/stretchr/testify/mock"
)

// TokenMinter is an autogenerated mock type for the TokenMinter type
type TokenMinter struct {
	mock.Mock
}

type TokenMinter_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenMinter) EXPECT() *TokenMinter_Expecter {
	return &TokenMinter_Expecter{mock: &_m.Mock}
}

// MintScopedAccessToken provides a mock function with given fields: ctx, role, scope, displayName, ttlSeconds, userID
func (_m *TokenMinter) MintScopedAccessToken(ctx context.Context, role model.ScopedRole, scope string, displayName string, ttlSeconds int32, userID string) (string, error) {
	ret := _m.Called(ctx, role, scope, displayName, ttlSeconds, userID)

	if len(ret) == 0 {
		panic("no return value specified for MintScopedAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ScopedRole, string, string, int32, string) (string, error)); ok {
		return rf(ctx, role, scope, displayName, ttlSeconds, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ScopedRole, string, string, int32, string) string); ok {
		r0 = rf(ctx, role, scope, displayName, ttlSeconds, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ScopedRole, string, string, int32, string) error); ok {
		r1 = rf(ctx, role, scope, displayName, ttlSeconds, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenMinter_MintScopedAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MintScopedAccessToken'
type TokenMinter_MintScopedAccessToken_Call struct {
	*mock.Call
}

// MintScopedAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - role model.ScopedRole
//   - scope string
//   - displayName string
//   - ttlSeconds int32
//   - userID string
func (_e *TokenMinter_Expecter) MintScopedAccessToken(ctx interface{}, role interface{}, scope interface{}, displayName interface{}, ttlSeconds interface{}, userID interface{}) *TokenMinter_MintScopedAccessToken_Call {
	return &TokenMinter_MintScopedAccessToken_Call{Call: _e.mock.On("MintScopedAccessToken", ctx, role, scope, displayName, ttlSeconds, userID)}
}

func (_c *TokenMinter_MintScopedAccessToken_Call) Run(run func(ctx context.Context, role model.ScopedRole, scope string, displayName string, ttlSeconds int32, userID string)) *TokenMinter_MintScopedAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ScopedRole), args[2].(string), args[3].(string), args[4].(int32), args[5].(string))
	})
	return _c
}

func (_c *TokenMinter_MintScopedAccessToken_Call) Return(_a0 string, _a1 error) *TokenMinter_MintScopedAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenMinter_MintScopedAccessToken_Call) RunAndReturn(run func(context.Context, model.ScopedRole, string, string, int32, string) (string, error)) *TokenMinter_MintScopedAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenMinter creates a new instance of TokenMinter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenMinter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenMinter {
	mock := &TokenMinter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
