// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// CheckAndConsumeUsage provides a mock function with given fields: ctx, userID, key, amount
func (_m *Client) CheckAndConsumeUsage(ctx context.Context, userID string, key string, amount int) error {
	ret := _m.Called(ctx, userID, key, amount)

	if len(ret) == 0 {
		panic("no return value specified for CheckAndConsumeUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = rf(ctx, userID, key, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_CheckAndConsumeUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAndConsumeUsage'
type Client_CheckAndConsumeUsage_Call struct {
	*mock.Call
}

// CheckAndConsumeUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - key string
//   - amount int
func (_e *Client_Expecter) CheckAndConsumeUsage(ctx interface{}, userID interface{}, key interface{}, amount interface{}) *Client_CheckAndConsumeUsage_Call {
	return &Client_CheckAndConsumeUsage_Call{Call: _e.mock.On("CheckAndConsumeUsage", ctx, userID, key, amount)}
}

func (_c *Client_CheckAndConsumeUsage_Call) Run(run func(ctx context.Context, userID string, key string, amount int)) *Client_CheckAndConsumeUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *Client_CheckAndConsumeUsage_Call) Return(_a0 error) *Client_CheckAndConsumeUsage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_CheckAndConsumeUsage_Call) RunAndReturn(run func(context.Context, string, string, int) error) *Client_CheckAndConsumeUsage_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
