// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Google is an autogenerated mock type for the Google type
type Google struct {
	mock.Mock
}

type Google_Expecter struct {
	mock *mock.Mock
}

func (_m *Google) EXPECT() *Google_Expecter {
	return &Google_Expecter{mock: &_m.Mock}
}

// Configured provides a mock function with no fields
func (_m *Google) Configured() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Configured")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Google_Configured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configured'
type Google_Configured_Call struct {
	*mock.Call
}

// Configured is a helper method to define mock.On call
func (_e *Google_Expecter) Configured() *Google_Configured_Call {
	return &Google_Configured_Call{Call: _e.mock.On("Configured")}
}

func (_c *Google_Configured_Call) Run(run func()) *Google_Configured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Google_Configured_Call) Return(_a0 bool) *Google_Configured_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Google_Configured_Call) RunAndReturn(run func() bool) *Google_Configured_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeCode provides a mock function with given fields: ctx, code
func (_m *Google) ExchangeCode(ctx context.Context, code string) (string, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Google_ExchangeCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCode'
type Google_ExchangeCode_Call struct {
	*mock.Call
}

// ExchangeCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *Google_Expecter) ExchangeCode(ctx interface{}, code interface{}) *Google_ExchangeCode_Call {
	return &Google_ExchangeCode_Call{Call: _e.mock.On("ExchangeCode", ctx, code)}
}

func (_c *Google_ExchangeCode_Call) Run(run func(ctx context.Context, code string)) *Google_ExchangeCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Google_ExchangeCode_Call) Return(_a0 string, _a1 error) *Google_ExchangeCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Google_ExchangeCode_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Google_ExchangeCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewGoogle creates a new instance of Google. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogle(t interface {
	mock.TestingT
	Cleanup(func())
}) *Google {
	mock := &Google{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
