// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// ConsumeGoogleOAuthState provides a mock function with given fields: ctx, state
func (_m *Store) ConsumeGoogleOAuthState(ctx context.Context, state string) (string, error) {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeGoogleOAuthState")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ConsumeGoogleOAuthState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeGoogleOAuthState'
type Store_ConsumeGoogleOAuthState_Call struct {
	*mock.Call
}

// ConsumeGoogleOAuthState is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *Store_Expecter) ConsumeGoogleOAuthState(ctx interface{}, state interface{}) *Store_ConsumeGoogleOAuthState_Call {
	return &Store_ConsumeGoogleOAuthState_Call{Call: _e.mock.On("ConsumeGoogleOAuthState", ctx, state)}
}

func (_c *Store_ConsumeGoogleOAuthState_Call) Run(run func(ctx context.Context, state string)) *Store_ConsumeGoogleOAuthState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ConsumeGoogleOAuthState_Call) Return(userID string, err error) *Store_ConsumeGoogleOAuthState_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *Store_ConsumeGoogleOAuthState_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Store_ConsumeGoogleOAuthState_Call {
	_c.Call.Return(run)
	return _c
}

// SaveGoogleRefreshToken provides a mock function with given fields: ctx, userID, refreshToken
func (_m *Store) SaveGoogleRefreshToken(ctx context.Context, userID string, refreshToken string) error {
	ret := _m.Called(ctx, userID, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for SaveGoogleRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveGoogleRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveGoogleRefreshToken'
type Store_SaveGoogleRefreshToken_Call struct {
	*mock.Call
}

// SaveGoogleRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - refreshToken string
func (_e *Store_Expecter) SaveGoogleRefreshToken(ctx interface{}, userID interface{}, refreshToken interface{}) *Store_SaveGoogleRefreshToken_Call {
	return &Store_SaveGoogleRefreshToken_Call{Call: _e.mock.On("SaveGoogleRefreshToken", ctx, userID, refreshToken)}
}

func (_c *Store_SaveGoogleRefreshToken_Call) Run(run func(ctx context.Context, userID string, refreshToken string)) *Store_SaveGoogleRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_SaveGoogleRefreshToken_Call) Return(_a0 error) *Store_SaveGoogleRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveGoogleRefreshToken_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_SaveGoogleRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
