// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenSealer is an autogenerated mock type for the TokenSealer type
type TokenSealer struct {
	mock.Mock
}

type TokenSealer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenSealer) EXPECT() *TokenSealer_Expecter {
	return &TokenSealer_Expecter{mock: &_m.Mock}
}

// Seal provides a mock function with given fields: plaintext
func (_m *TokenSealer) Seal(plaintext string) (string, error) {
	ret := _m.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Seal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(plaintext)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(plaintext)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(plaintext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenSealer_Seal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seal'
type TokenSealer_Seal_Call struct {
	*mock.Call
}

// Seal is a helper method to define mock.On call
//   - plaintext string
func (_e *TokenSealer_Expecter) Seal(plaintext interface{}) *TokenSealer_Seal_Call {
	return &TokenSealer_Seal_Call{Call: _e.mock.On("Seal", plaintext)}
}

func (_c *TokenSealer_Seal_Call) Run(run func(plaintext string)) *TokenSealer_Seal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenSealer_Seal_Call) Return(_a0 string, _a1 error) *TokenSealer_Seal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenSealer_Seal_Call) RunAndReturn(run func(string) (string, error)) *TokenSealer_Seal_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenSealer creates a new instance of TokenSealer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenSealer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenSealer {
	mock := &TokenSealer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
