// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// ConsumeZoomOAuthState provides a mock function with given fields: ctx, state
func (_m *Store) ConsumeZoomOAuthState(ctx context.Context, state string) (string, error) {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeZoomOAuthState")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ConsumeZoomOAuthState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeZoomOAuthState'
type Store_ConsumeZoomOAuthState_Call struct {
	*mock.Call
}

// ConsumeZoomOAuthState is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *Store_Expecter) ConsumeZoomOAuthState(ctx interface{}, state interface{}) *Store_ConsumeZoomOAuthState_Call {
	return &Store_ConsumeZoomOAuthState_Call{Call: _e.mock.On("ConsumeZoomOAuthState", ctx, state)}
}

func (_c *Store_ConsumeZoomOAuthState_Call) Run(run func(ctx context.Context, state string)) *Store_ConsumeZoomOAuthState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ConsumeZoomOAuthState_Call) Return(userID string, err error) *Store_ConsumeZoomOAuthState_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *Store_ConsumeZoomOAuthState_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Store_ConsumeZoomOAuthState_Call {
	_c.Call.Return(run)
	return _c
}

// SaveZoomRefreshToken provides a mock function with given fields: ctx, userID, refreshToken
func (_m *Store) SaveZoomRefreshToken(ctx context.Context, userID string, refreshToken string) error {
	ret := _m.Called(ctx, userID, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for SaveZoomRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveZoomRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveZoomRefreshToken'
type Store_SaveZoomRefreshToken_Call struct {
	*mock.Call
}

// SaveZoomRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - refreshToken string
func (_e *Store_Expecter) SaveZoomRefreshToken(ctx interface{}, userID interface{}, refreshToken interface{}) *Store_SaveZoomRefreshToken_Call {
	return &Store_SaveZoomRefreshToken_Call{Call: _e.mock.On("SaveZoomRefreshToken", ctx, userID, refreshToken)}
}

func (_c *Store_SaveZoomRefreshToken_Call) Run(run func(ctx context.Context, userID string, refreshToken string)) *Store_SaveZoomRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_SaveZoomRefreshToken_Call) Return(_a0 error) *Store_SaveZoomRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveZoomRefreshToken_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_SaveZoomRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
