// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	identity "github.com/dobriygolang/project-nordly/services/billing/internal/adapter/identity"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetUserByTelegramID provides a mock function with given fields: ctx, telegramID
func (_m *Client) GetUserByTelegramID(ctx context.Context, telegramID int64) (*identity.User, error) {
	ret := _m.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByTelegramID")
	}

	var r0 *identity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*identity.User, error)); ok {
		return rf(ctx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *identity.User); ok {
		r0 = rf(ctx, telegramID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetUserByTelegramID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByTelegramID'
type Client_GetUserByTelegramID_Call struct {
	*mock.Call
}

// GetUserByTelegramID is a helper method to define mock.On call
//   - ctx context.Context
//   - telegramID int64
func (_e *Client_Expecter) GetUserByTelegramID(ctx interface{}, telegramID interface{}) *Client_GetUserByTelegramID_Call {
	return &Client_GetUserByTelegramID_Call{Call: _e.mock.On("GetUserByTelegramID", ctx, telegramID)}
}

func (_c *Client_GetUserByTelegramID_Call) Run(run func(ctx context.Context, telegramID int64)) *Client_GetUserByTelegramID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Client_GetUserByTelegramID_Call) Return(_a0 *identity.User, _a1 error) *Client_GetUserByTelegramID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetUserByTelegramID_Call) RunAndReturn(run func(context.Context, int64) (*identity.User, error)) *Client_GetUserByTelegramID_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
