// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/rooms/internal/room/model"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// RoomStore is an autogenerated mock type for the RoomStore type
type RoomStore struct {
	mock.Mock
}

type RoomStore_Expecter struct {
	mock *mock.Mock
}

func (_m *RoomStore) EXPECT() *RoomStore_Expecter {
	return &RoomStore_Expecter{mock: &_m.Mock}
}

// AddParticipant provides a mock function with given fields: ctx, p
func (_m *RoomStore) AddParticipant(ctx context.Context, p model.Participant) (model.Participant, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for AddParticipant")
	}

	var r0 model.Participant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Participant) (model.Participant, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Participant) model.Participant); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(model.Participant)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Participant) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoomStore_AddParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddParticipant'
type RoomStore_AddParticipant_Call struct {
	*mock.Call
}

// AddParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - p model.Participant
func (_e *RoomStore_Expecter) AddParticipant(ctx interface{}, p interface{}) *RoomStore_AddParticipant_Call {
	return &RoomStore_AddParticipant_Call{Call: _e.mock.On("AddParticipant", ctx, p)}
}

func (_c *RoomStore_AddParticipant_Call) Run(run func(ctx context.Context, p model.Participant)) *RoomStore_AddParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Participant))
	})
	return _c
}

func (_c *RoomStore_AddParticipant_Call) Return(_a0 model.Participant, _a1 error) *RoomStore_AddParticipant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RoomStore_AddParticipant_Call) RunAndReturn(run func(context.Context, model.Participant) (model.Participant, error)) *RoomStore_AddParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// GetRole provides a mock function with given fields: ctx, roomID, userID
func (_m *RoomStore) GetRole(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (model.Role, error) {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (model.Role, error)); ok {
		return rf(ctx, roomID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) model.Role); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Get(0).(model.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoomStore_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type RoomStore_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *RoomStore_Expecter) GetRole(ctx interface{}, roomID interface{}, userID interface{}) *RoomStore_GetRole_Call {
	return &RoomStore_GetRole_Call{Call: _e.mock.On("GetRole", ctx, roomID, userID)}
}

func (_c *RoomStore_GetRole_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *RoomStore_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *RoomStore_GetRole_Call) Return(_a0 model.Role, _a1 error) *RoomStore_GetRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RoomStore_GetRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (model.Role, error)) *RoomStore_GetRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoom provides a mock function with given fields: ctx, id
func (_m *RoomStore) GetRoom(ctx context.Context, id uuid.UUID) (model.Room, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoom")
	}

	var r0 model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Room, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Room); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoomStore_GetRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoom'
type RoomStore_GetRoom_Call struct {
	*mock.Call
}

// GetRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *RoomStore_Expecter) GetRoom(ctx interface{}, id interface{}) *RoomStore_GetRoom_Call {
	return &RoomStore_GetRoom_Call{Call: _e.mock.On("GetRoom", ctx, id)}
}

func (_c *RoomStore_GetRoom_Call) Run(run func(ctx context.Context, id uuid.UUID)) *RoomStore_GetRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *RoomStore_GetRoom_Call) Return(_a0 model.Room, _a1 error) *RoomStore_GetRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RoomStore_GetRoom_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Room, error)) *RoomStore_GetRoom_Call {
	_c.Call.Return(run)
	return _c
}

// NewRoomStore creates a new instance of RoomStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomStore {
	mock := &RoomStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
