// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Socket is an autogenerated mock type for the Socket type
type Socket struct {
	mock.Mock
}

type Socket_Expecter struct {
	mock *mock.Mock
}

func (_m *Socket) EXPECT() *Socket_Expecter {
	return &Socket_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Socket) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Socket_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Socket_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Socket_Expecter) Close() *Socket_Close_Call {
	return &Socket_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Socket_Close_Call) Run(run func()) *Socket_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Socket_Close_Call) Return(_a0 error) *Socket_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Socket_Close_Call) RunAndReturn(run func() error) *Socket_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ReadMessage provides a mock function with no fields
func (_m *Socket) ReadMessage() (int, []byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadMessage")
	}

	var r0 int
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func() (int, []byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() []byte); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Socket_ReadMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadMessage'
type Socket_ReadMessage_Call struct {
	*mock.Call
}

// ReadMessage is a helper method to define mock.On call
func (_e *Socket_Expecter) ReadMessage() *Socket_ReadMessage_Call {
	return &Socket_ReadMessage_Call{Call: _e.mock.On("ReadMessage")}
}

func (_c *Socket_ReadMessage_Call) Run(run func()) *Socket_ReadMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Socket_ReadMessage_Call) Return(messageType int, p []byte, err error) *Socket_ReadMessage_Call {
	_c.Call.Return(messageType, p, err)
	return _c
}

func (_c *Socket_ReadMessage_Call) RunAndReturn(run func() (int, []byte, error)) *Socket_ReadMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SetCloseHandler provides a mock function with given fields: h
func (_m *Socket) SetCloseHandler(h func(int, string) error) {
	_m.Called(h)
}

// Socket_SetCloseHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCloseHandler'
type Socket_SetCloseHandler_Call struct {
	*mock.Call
}

// SetCloseHandler is a helper method to define mock.On call
//   - h func(int , string) error
func (_e *Socket_Expecter) SetCloseHandler(h interface{}) *Socket_SetCloseHandler_Call {
	return &Socket_SetCloseHandler_Call{Call: _e.mock.On("SetCloseHandler", h)}
}

func (_c *Socket_SetCloseHandler_Call) Run(run func(h func(int, string) error)) *Socket_SetCloseHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(int, string) error))
	})
	return _c
}

func (_c *Socket_SetCloseHandler_Call) Return() *Socket_SetCloseHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *Socket_SetCloseHandler_Call) RunAndReturn(run func(func(int, string) error)) *Socket_SetCloseHandler_Call {
	_c.Run(run)
	return _c
}

// SetPingHandler provides a mock function with given fields: h
func (_m *Socket) SetPingHandler(h func(string) error) {
	_m.Called(h)
}

// Socket_SetPingHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPingHandler'
type Socket_SetPingHandler_Call struct {
	*mock.Call
}

// SetPingHandler is a helper method to define mock.On call
//   - h func(string) error
func (_e *Socket_Expecter) SetPingHandler(h interface{}) *Socket_SetPingHandler_Call {
	return &Socket_SetPingHandler_Call{Call: _e.mock.On("SetPingHandler", h)}
}

func (_c *Socket_SetPingHandler_Call) Run(run func(h func(string) error)) *Socket_SetPingHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(string) error))
	})
	return _c
}

func (_c *Socket_SetPingHandler_Call) Return() *Socket_SetPingHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *Socket_SetPingHandler_Call) RunAndReturn(run func(func(string) error)) *Socket_SetPingHandler_Call {
	_c.Run(run)
	return _c
}

// SetPongHandler provides a mock function with given fields: h
func (_m *Socket) SetPongHandler(h func(string) error) {
	_m.Called(h)
}

// Socket_SetPongHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPongHandler'
type Socket_SetPongHandler_Call struct {
	*mock.Call
}

// SetPongHandler is a helper method to define mock.On call
//   - h func(string) error
func (_e *Socket_Expecter) SetPongHandler(h interface{}) *Socket_SetPongHandler_Call {
	return &Socket_SetPongHandler_Call{Call: _e.mock.On("SetPongHandler", h)}
}

func (_c *Socket_SetPongHandler_Call) Run(run func(h func(string) error)) *Socket_SetPongHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(string) error))
	})
	return _c
}

func (_c *Socket_SetPongHandler_Call) Return() *Socket_SetPongHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *Socket_SetPongHandler_Call) RunAndReturn(run func(func(string) error)) *Socket_SetPongHandler_Call {
	_c.Run(run)
	return _c
}

// SetReadDeadline provides a mock function with given fields: t
func (_m *Socket) SetReadDeadline(t time.Time) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetReadDeadline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Socket_SetReadDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReadDeadline'
type Socket_SetReadDeadline_Call struct {
	*mock.Call
}

// SetReadDeadline is a helper method to define mock.On call
//   - t time.Time
func (_e *Socket_Expecter) SetReadDeadline(t interface{}) *Socket_SetReadDeadline_Call {
	return &Socket_SetReadDeadline_Call{Call: _e.mock.On("SetReadDeadline", t)}
}

func (_c *Socket_SetReadDeadline_Call) Run(run func(t time.Time)) *Socket_SetReadDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *Socket_SetReadDeadline_Call) Return(_a0 error) *Socket_SetReadDeadline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Socket_SetReadDeadline_Call) RunAndReturn(run func(time.Time) error) *Socket_SetReadDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// SetReadLimit provides a mock function with given fields: limit
func (_m *Socket) SetReadLimit(limit int64) {
	_m.Called(limit)
}

// Socket_SetReadLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReadLimit'
type Socket_SetReadLimit_Call struct {
	*mock.Call
}

// SetReadLimit is a helper method to define mock.On call
//   - limit int64
func (_e *Socket_Expecter) SetReadLimit(limit interface{}) *Socket_SetReadLimit_Call {
	return &Socket_SetReadLimit_Call{Call: _e.mock.On("SetReadLimit", limit)}
}

func (_c *Socket_SetReadLimit_Call) Run(run func(limit int64)) *Socket_SetReadLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Socket_SetReadLimit_Call) Return() *Socket_SetReadLimit_Call {
	_c.Call.Return()
	return _c
}

func (_c *Socket_SetReadLimit_Call) RunAndReturn(run func(int64)) *Socket_SetReadLimit_Call {
	_c.Run(run)
	return _c
}

// SetWriteDeadline provides a mock function with given fields: t
func (_m *Socket) SetWriteDeadline(t time.Time) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetWriteDeadline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Socket_SetWriteDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWriteDeadline'
type Socket_SetWriteDeadline_Call struct {
	*mock.Call
}

// SetWriteDeadline is a helper method to define mock.On call
//   - t time.Time
func (_e *Socket_Expecter) SetWriteDeadline(t interface{}) *Socket_SetWriteDeadline_Call {
	return &Socket_SetWriteDeadline_Call{Call: _e.mock.On("SetWriteDeadline", t)}
}

func (_c *Socket_SetWriteDeadline_Call) Run(run func(t time.Time)) *Socket_SetWriteDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *Socket_SetWriteDeadline_Call) Return(_a0 error) *Socket_SetWriteDeadline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Socket_SetWriteDeadline_Call) RunAndReturn(run func(time.Time) error) *Socket_SetWriteDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// WriteControl provides a mock function with given fields: messageType, data, deadline
func (_m *Socket) WriteControl(messageType int, data []byte, deadline time.Time) error {
	ret := _m.Called(messageType, data, deadline)

	if len(ret) == 0 {
		panic("no return value specified for WriteControl")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []byte, time.Time) error); ok {
		r0 = rf(messageType, data, deadline)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Socket_WriteControl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteControl'
type Socket_WriteControl_Call struct {
	*mock.Call
}

// WriteControl is a helper method to define mock.On call
//   - messageType int
//   - data []byte
//   - deadline time.Time
func (_e *Socket_Expecter) WriteControl(messageType interface{}, data interface{}, deadline interface{}) *Socket_WriteControl_Call {
	return &Socket_WriteControl_Call{Call: _e.mock.On("WriteControl", messageType, data, deadline)}
}

func (_c *Socket_WriteControl_Call) Run(run func(messageType int, data []byte, deadline time.Time)) *Socket_WriteControl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].([]byte), args[2].(time.Time))
	})
	return _c
}

func (_c *Socket_WriteControl_Call) Return(_a0 error) *Socket_WriteControl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Socket_WriteControl_Call) RunAndReturn(run func(int, []byte, time.Time) error) *Socket_WriteControl_Call {
	_c.Call.Return(run)
	return _c
}

// WriteMessage provides a mock function with given fields: messageType, data
func (_m *Socket) WriteMessage(messageType int, data []byte) error {
	ret := _m.Called(messageType, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []byte) error); ok {
		r0 = rf(messageType, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Socket_WriteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMessage'
type Socket_WriteMessage_Call struct {
	*mock.Call
}

// WriteMessage is a helper method to define mock.On call
//   - messageType int
//   - data []byte
func (_e *Socket_Expecter) WriteMessage(messageType interface{}, data interface{}) *Socket_WriteMessage_Call {
	return &Socket_WriteMessage_Call{Call: _e.mock.On("WriteMessage", messageType, data)}
}

func (_c *Socket_WriteMessage_Call) Run(run func(messageType int, data []byte)) *Socket_WriteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].([]byte))
	})
	return _c
}

func (_c *Socket_WriteMessage_Call) Return(_a0 error) *Socket_WriteMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Socket_WriteMessage_Call) RunAndReturn(run func(int, []byte) error) *Socket_WriteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewSocket creates a new instance of Socket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSocket(t interface {
	mock.TestingT
	Cleanup(func())
}) *Socket {
	mock := &Socket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
