// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/identity/internal/auth/model"
	mock "github.com/stretchr/testify/mock"
)

// LoginCodeStore is an autogenerated mock type for the LoginCodeStore type
type LoginCodeStore struct {
	mock.Mock
}

type LoginCodeStore_Expecter struct {
	mock *mock.Mock
}

func (_m *LoginCodeStore) EXPECT() *LoginCodeStore_Expecter {
	return &LoginCodeStore_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, code, data, ttlSeconds
func (_m *LoginCodeStore) Save(ctx context.Context, code string, data *model.TelegramLoginCode, ttlSeconds int) error {
	ret := _m.Called(ctx, code, data, ttlSeconds)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.TelegramLoginCode, int) error); ok {
		r0 = rf(ctx, code, data, ttlSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoginCodeStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type LoginCodeStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - data *model.TelegramLoginCode
//   - ttlSeconds int
func (_e *LoginCodeStore_Expecter) Save(ctx interface{}, code interface{}, data interface{}, ttlSeconds interface{}) *LoginCodeStore_Save_Call {
	return &LoginCodeStore_Save_Call{Call: _e.mock.On("Save", ctx, code, data, ttlSeconds)}
}

func (_c *LoginCodeStore_Save_Call) Run(run func(ctx context.Context, code string, data *model.TelegramLoginCode, ttlSeconds int)) *LoginCodeStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.TelegramLoginCode), args[3].(int))
	})
	return _c
}

func (_c *LoginCodeStore_Save_Call) Return(_a0 error) *LoginCodeStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoginCodeStore_Save_Call) RunAndReturn(run func(context.Context, string, *model.TelegramLoginCode, int) error) *LoginCodeStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoginCodeStore creates a new instance of LoginCodeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginCodeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginCodeStore {
	mock := &LoginCodeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
