// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	identityv1 "github.com/dobriygolang/project-nordly/services/identity/pkg/api/identity/v1"
	mock "github.com/stretchr/testify/mock"
)

// IdentityClient is an autogenerated mock type for the IdentityClient type
type IdentityClient struct {
	mock.Mock
}

type IdentityClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentityClient) EXPECT() *IdentityClient_Expecter {
	return &IdentityClient_Expecter{mock: &_m.Mock}
}

// MintScopedAccessToken provides a mock function with given fields: ctx, in, opts
func (_m *IdentityClient) MintScopedAccessToken(ctx context.Context, in *identityv1.MintScopedAccessTokenRequest, opts ...grpc.CallOption) (*identityv1.MintScopedAccessTokenResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for MintScopedAccessToken")
	}

	var r0 *identityv1.MintScopedAccessTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *identityv1.MintScopedAccessTokenRequest, ...grpc.CallOption) (*identityv1.MintScopedAccessTokenResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *identityv1.MintScopedAccessTokenRequest, ...grpc.CallOption) *identityv1.MintScopedAccessTokenResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identityv1.MintScopedAccessTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *identityv1.MintScopedAccessTokenRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentityClient_MintScopedAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MintScopedAccessToken'
type IdentityClient_MintScopedAccessToken_Call struct {
	*mock.Call
}

// MintScopedAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - in *identityv1.MintScopedAccessTokenRequest
//   - opts ...grpc.CallOption
func (_e *IdentityClient_Expecter) MintScopedAccessToken(ctx interface{}, in interface{}, opts ...interface{}) *IdentityClient_MintScopedAccessToken_Call {
	return &IdentityClient_MintScopedAccessToken_Call{Call: _e.mock.On("MintScopedAccessToken",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *IdentityClient_MintScopedAccessToken_Call) Run(run func(ctx context.Context, in *identityv1.MintScopedAccessTokenRequest, opts ...grpc.CallOption)) *IdentityClient_MintScopedAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*identityv1.MintScopedAccessTokenRequest), variadicArgs...)
	})
	return _c
}

func (_c *IdentityClient_MintScopedAccessToken_Call) Return(_a0 *identityv1.MintScopedAccessTokenResponse, _a1 error) *IdentityClient_MintScopedAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdentityClient_MintScopedAccessToken_Call) RunAndReturn(run func(context.Context, *identityv1.MintScopedAccessTokenRequest, ...grpc.CallOption) (*identityv1.MintScopedAccessTokenResponse, error)) *IdentityClient_MintScopedAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewIdentityClient creates a new instance of IdentityClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityClient {
	mock := &IdentityClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
