// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	billing "github.com/dobriygolang/project-nordly/services/identity/internal/adapter/billing"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// CheckFeature provides a mock function with given fields: ctx, userID, key
func (_m *Client) CheckFeature(ctx context.Context, userID string, key string) (bool, error) {
	ret := _m.Called(ctx, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for CheckFeature")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, userID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userID, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_CheckFeature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckFeature'
type Client_CheckFeature_Call struct {
	*mock.Call
}

// CheckFeature is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - key string
func (_e *Client_Expecter) CheckFeature(ctx interface{}, userID interface{}, key interface{}) *Client_CheckFeature_Call {
	return &Client_CheckFeature_Call{Call: _e.mock.On("CheckFeature", ctx, userID, key)}
}

func (_c *Client_CheckFeature_Call) Run(run func(ctx context.Context, userID string, key string)) *Client_CheckFeature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Client_CheckFeature_Call) Return(_a0 bool, _a1 error) *Client_CheckFeature_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_CheckFeature_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *Client_CheckFeature_Call {
	_c.Call.Return(run)
	return _c
}

// GetGaugeLimit provides a mock function with given fields: ctx, userID, key
func (_m *Client) GetGaugeLimit(ctx context.Context, userID string, key string) (billing.GaugeLimit, error) {
	ret := _m.Called(ctx, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetGaugeLimit")
	}

	var r0 billing.GaugeLimit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (billing.GaugeLimit, error)); ok {
		return rf(ctx, userID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) billing.GaugeLimit); ok {
		r0 = rf(ctx, userID, key)
	} else {
		r0 = ret.Get(0).(billing.GaugeLimit)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetGaugeLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGaugeLimit'
type Client_GetGaugeLimit_Call struct {
	*mock.Call
}

// GetGaugeLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - key string
func (_e *Client_Expecter) GetGaugeLimit(ctx interface{}, userID interface{}, key interface{}) *Client_GetGaugeLimit_Call {
	return &Client_GetGaugeLimit_Call{Call: _e.mock.On("GetGaugeLimit", ctx, userID, key)}
}

func (_c *Client_GetGaugeLimit_Call) Run(run func(ctx context.Context, userID string, key string)) *Client_GetGaugeLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Client_GetGaugeLimit_Call) Return(_a0 billing.GaugeLimit, _a1 error) *Client_GetGaugeLimit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetGaugeLimit_Call) RunAndReturn(run func(context.Context, string, string) (billing.GaugeLimit, error)) *Client_GetGaugeLimit_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
