// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// SaveZoomOAuthState provides a mock function with given fields: ctx, userID, state
func (_m *Store) SaveZoomOAuthState(ctx context.Context, userID string, state string) error {
	ret := _m.Called(ctx, userID, state)

	if len(ret) == 0 {
		panic("no return value specified for SaveZoomOAuthState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveZoomOAuthState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveZoomOAuthState'
type Store_SaveZoomOAuthState_Call struct {
	*mock.Call
}

// SaveZoomOAuthState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - state string
func (_e *Store_Expecter) SaveZoomOAuthState(ctx interface{}, userID interface{}, state interface{}) *Store_SaveZoomOAuthState_Call {
	return &Store_SaveZoomOAuthState_Call{Call: _e.mock.On("SaveZoomOAuthState", ctx, userID, state)}
}

func (_c *Store_SaveZoomOAuthState_Call) Run(run func(ctx context.Context, userID string, state string)) *Store_SaveZoomOAuthState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_SaveZoomOAuthState_Call) Return(_a0 error) *Store_SaveZoomOAuthState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveZoomOAuthState_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_SaveZoomOAuthState_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
