// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	model "github.com/dobriygolang/project-nordly/services/tracker/internal/tracker/model"
	repository "github.com/dobriygolang/project-nordly/services/tracker/internal/tracker/repository"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// ClearAllGoogleCalendarSyncState provides a mock function with given fields: ctx, userID
func (_m *Store) ClearAllGoogleCalendarSyncState(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearAllGoogleCalendarSyncState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_ClearAllGoogleCalendarSyncState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAllGoogleCalendarSyncState'
type Store_ClearAllGoogleCalendarSyncState_Call struct {
	*mock.Call
}

// ClearAllGoogleCalendarSyncState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) ClearAllGoogleCalendarSyncState(ctx interface{}, userID interface{}) *Store_ClearAllGoogleCalendarSyncState_Call {
	return &Store_ClearAllGoogleCalendarSyncState_Call{Call: _e.mock.On("ClearAllGoogleCalendarSyncState", ctx, userID)}
}

func (_c *Store_ClearAllGoogleCalendarSyncState_Call) Run(run func(ctx context.Context, userID string)) *Store_ClearAllGoogleCalendarSyncState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ClearAllGoogleCalendarSyncState_Call) Return(_a0 error) *Store_ClearAllGoogleCalendarSyncState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_ClearAllGoogleCalendarSyncState_Call) RunAndReturn(run func(context.Context, string) error) *Store_ClearAllGoogleCalendarSyncState_Call {
	_c.Call.Return(run)
	return _c
}

// ClearAllGoogleEventIDs provides a mock function with given fields: ctx, userID
func (_m *Store) ClearAllGoogleEventIDs(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearAllGoogleEventIDs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_ClearAllGoogleEventIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAllGoogleEventIDs'
type Store_ClearAllGoogleEventIDs_Call struct {
	*mock.Call
}

// ClearAllGoogleEventIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) ClearAllGoogleEventIDs(ctx interface{}, userID interface{}) *Store_ClearAllGoogleEventIDs_Call {
	return &Store_ClearAllGoogleEventIDs_Call{Call: _e.mock.On("ClearAllGoogleEventIDs", ctx, userID)}
}

func (_c *Store_ClearAllGoogleEventIDs_Call) Run(run func(ctx context.Context, userID string)) *Store_ClearAllGoogleEventIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ClearAllGoogleEventIDs_Call) Return(_a0 error) *Store_ClearAllGoogleEventIDs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_ClearAllGoogleEventIDs_Call) RunAndReturn(run func(context.Context, string) error) *Store_ClearAllGoogleEventIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ClearGoogleConnection provides a mock function with given fields: ctx, userID
func (_m *Store) ClearGoogleConnection(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearGoogleConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_ClearGoogleConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearGoogleConnection'
type Store_ClearGoogleConnection_Call struct {
	*mock.Call
}

// ClearGoogleConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) ClearGoogleConnection(ctx interface{}, userID interface{}) *Store_ClearGoogleConnection_Call {
	return &Store_ClearGoogleConnection_Call{Call: _e.mock.On("ClearGoogleConnection", ctx, userID)}
}

func (_c *Store_ClearGoogleConnection_Call) Run(run func(ctx context.Context, userID string)) *Store_ClearGoogleConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ClearGoogleConnection_Call) Return(_a0 error) *Store_ClearGoogleConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_ClearGoogleConnection_Call) RunAndReturn(run func(context.Context, string) error) *Store_ClearGoogleConnection_Call {
	_c.Call.Return(run)
	return _c
}

// ClearGoogleEventIDByEventID provides a mock function with given fields: ctx, userID, eventID
func (_m *Store) ClearGoogleEventIDByEventID(ctx context.Context, userID string, eventID string) error {
	ret := _m.Called(ctx, userID, eventID)

	if len(ret) == 0 {
		panic("no return value specified for ClearGoogleEventIDByEventID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_ClearGoogleEventIDByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearGoogleEventIDByEventID'
type Store_ClearGoogleEventIDByEventID_Call struct {
	*mock.Call
}

// ClearGoogleEventIDByEventID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - eventID string
func (_e *Store_Expecter) ClearGoogleEventIDByEventID(ctx interface{}, userID interface{}, eventID interface{}) *Store_ClearGoogleEventIDByEventID_Call {
	return &Store_ClearGoogleEventIDByEventID_Call{Call: _e.mock.On("ClearGoogleEventIDByEventID", ctx, userID, eventID)}
}

func (_c *Store_ClearGoogleEventIDByEventID_Call) Run(run func(ctx context.Context, userID string, eventID string)) *Store_ClearGoogleEventIDByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_ClearGoogleEventIDByEventID_Call) Return(_a0 error) *Store_ClearGoogleEventIDByEventID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_ClearGoogleEventIDByEventID_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_ClearGoogleEventIDByEventID_Call {
	_c.Call.Return(run)
	return _c
}

// ClearGoogleEventsCache provides a mock function with given fields: ctx, userID
func (_m *Store) ClearGoogleEventsCache(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearGoogleEventsCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_ClearGoogleEventsCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearGoogleEventsCache'
type Store_ClearGoogleEventsCache_Call struct {
	*mock.Call
}

// ClearGoogleEventsCache is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) ClearGoogleEventsCache(ctx interface{}, userID interface{}) *Store_ClearGoogleEventsCache_Call {
	return &Store_ClearGoogleEventsCache_Call{Call: _e.mock.On("ClearGoogleEventsCache", ctx, userID)}
}

func (_c *Store_ClearGoogleEventsCache_Call) Run(run func(ctx context.Context, userID string)) *Store_ClearGoogleEventsCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ClearGoogleEventsCache_Call) Return(_a0 error) *Store_ClearGoogleEventsCache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_ClearGoogleEventsCache_Call) RunAndReturn(run func(context.Context, string) error) *Store_ClearGoogleEventsCache_Call {
	_c.Call.Return(run)
	return _c
}

// ClearZoomConnection provides a mock function with given fields: ctx, userID
func (_m *Store) ClearZoomConnection(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearZoomConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_ClearZoomConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearZoomConnection'
type Store_ClearZoomConnection_Call struct {
	*mock.Call
}

// ClearZoomConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) ClearZoomConnection(ctx interface{}, userID interface{}) *Store_ClearZoomConnection_Call {
	return &Store_ClearZoomConnection_Call{Call: _e.mock.On("ClearZoomConnection", ctx, userID)}
}

func (_c *Store_ClearZoomConnection_Call) Run(run func(ctx context.Context, userID string)) *Store_ClearZoomConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ClearZoomConnection_Call) Return(_a0 error) *Store_ClearZoomConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_ClearZoomConnection_Call) RunAndReturn(run func(context.Context, string) error) *Store_ClearZoomConnection_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumeGoogleOAuthState provides a mock function with given fields: ctx, state
func (_m *Store) ConsumeGoogleOAuthState(ctx context.Context, state string) (string, error) {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeGoogleOAuthState")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ConsumeGoogleOAuthState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeGoogleOAuthState'
type Store_ConsumeGoogleOAuthState_Call struct {
	*mock.Call
}

// ConsumeGoogleOAuthState is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *Store_Expecter) ConsumeGoogleOAuthState(ctx interface{}, state interface{}) *Store_ConsumeGoogleOAuthState_Call {
	return &Store_ConsumeGoogleOAuthState_Call{Call: _e.mock.On("ConsumeGoogleOAuthState", ctx, state)}
}

func (_c *Store_ConsumeGoogleOAuthState_Call) Run(run func(ctx context.Context, state string)) *Store_ConsumeGoogleOAuthState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ConsumeGoogleOAuthState_Call) Return(_a0 string, _a1 error) *Store_ConsumeGoogleOAuthState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ConsumeGoogleOAuthState_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Store_ConsumeGoogleOAuthState_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumeZoomOAuthState provides a mock function with given fields: ctx, state
func (_m *Store) ConsumeZoomOAuthState(ctx context.Context, state string) (string, error) {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeZoomOAuthState")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ConsumeZoomOAuthState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeZoomOAuthState'
type Store_ConsumeZoomOAuthState_Call struct {
	*mock.Call
}

// ConsumeZoomOAuthState is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *Store_Expecter) ConsumeZoomOAuthState(ctx interface{}, state interface{}) *Store_ConsumeZoomOAuthState_Call {
	return &Store_ConsumeZoomOAuthState_Call{Call: _e.mock.On("ConsumeZoomOAuthState", ctx, state)}
}

func (_c *Store_ConsumeZoomOAuthState_Call) Run(run func(ctx context.Context, state string)) *Store_ConsumeZoomOAuthState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ConsumeZoomOAuthState_Call) Return(_a0 string, _a1 error) *Store_ConsumeZoomOAuthState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ConsumeZoomOAuthState_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Store_ConsumeZoomOAuthState_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEpic provides a mock function with given fields: ctx, userID, name, color
func (_m *Store) CreateEpic(ctx context.Context, userID string, name string, color string) (*model.Epic, error) {
	ret := _m.Called(ctx, userID, name, color)

	if len(ret) == 0 {
		panic("no return value specified for CreateEpic")
	}

	var r0 *model.Epic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.Epic, error)); ok {
		return rf(ctx, userID, name, color)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.Epic); ok {
		r0 = rf(ctx, userID, name, color)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Epic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, name, color)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CreateEpic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEpic'
type Store_CreateEpic_Call struct {
	*mock.Call
}

// CreateEpic is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
//   - color string
func (_e *Store_Expecter) CreateEpic(ctx interface{}, userID interface{}, name interface{}, color interface{}) *Store_CreateEpic_Call {
	return &Store_CreateEpic_Call{Call: _e.mock.On("CreateEpic", ctx, userID, name, color)}
}

func (_c *Store_CreateEpic_Call) Run(run func(ctx context.Context, userID string, name string, color string)) *Store_CreateEpic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Store_CreateEpic_Call) Return(_a0 *model.Epic, _a1 error) *Store_CreateEpic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CreateEpic_Call) RunAndReturn(run func(context.Context, string, string, string) (*model.Epic, error)) *Store_CreateEpic_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorkTask provides a mock function with given fields: ctx, userID, kind, title, status
func (_m *Store) CreateWorkTask(ctx context.Context, userID string, kind string, title string, status string) (*model.WorkTask, error) {
	ret := _m.Called(ctx, userID, kind, title, status)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkTask")
	}

	var r0 *model.WorkTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*model.WorkTask, error)); ok {
		return rf(ctx, userID, kind, title, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *model.WorkTask); ok {
		r0 = rf(ctx, userID, kind, title, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WorkTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, userID, kind, title, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CreateWorkTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkTask'
type Store_CreateWorkTask_Call struct {
	*mock.Call
}

// CreateWorkTask is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - kind string
//   - title string
//   - status string
func (_e *Store_Expecter) CreateWorkTask(ctx interface{}, userID interface{}, kind interface{}, title interface{}, status interface{}) *Store_CreateWorkTask_Call {
	return &Store_CreateWorkTask_Call{Call: _e.mock.On("CreateWorkTask", ctx, userID, kind, title, status)}
}

func (_c *Store_CreateWorkTask_Call) Run(run func(ctx context.Context, userID string, kind string, title string, status string)) *Store_CreateWorkTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *Store_CreateWorkTask_Call) Return(_a0 *model.WorkTask, _a1 error) *Store_CreateWorkTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CreateWorkTask_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*model.WorkTask, error)) *Store_CreateWorkTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGoogleEvents provides a mock function with given fields: ctx, userID, calendarID, eventIDs
func (_m *Store) DeleteGoogleEvents(ctx context.Context, userID string, calendarID string, eventIDs []string) error {
	ret := _m.Called(ctx, userID, calendarID, eventIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGoogleEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = rf(ctx, userID, calendarID, eventIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DeleteGoogleEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGoogleEvents'
type Store_DeleteGoogleEvents_Call struct {
	*mock.Call
}

// DeleteGoogleEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - calendarID string
//   - eventIDs []string
func (_e *Store_Expecter) DeleteGoogleEvents(ctx interface{}, userID interface{}, calendarID interface{}, eventIDs interface{}) *Store_DeleteGoogleEvents_Call {
	return &Store_DeleteGoogleEvents_Call{Call: _e.mock.On("DeleteGoogleEvents", ctx, userID, calendarID, eventIDs)}
}

func (_c *Store_DeleteGoogleEvents_Call) Run(run func(ctx context.Context, userID string, calendarID string, eventIDs []string)) *Store_DeleteGoogleEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *Store_DeleteGoogleEvents_Call) Return(_a0 error) *Store_DeleteGoogleEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DeleteGoogleEvents_Call) RunAndReturn(run func(context.Context, string, string, []string) error) *Store_DeleteGoogleEvents_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGoogleEventsByCalendar provides a mock function with given fields: ctx, userID, calendarID
func (_m *Store) DeleteGoogleEventsByCalendar(ctx context.Context, userID string, calendarID string) error {
	ret := _m.Called(ctx, userID, calendarID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGoogleEventsByCalendar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, calendarID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DeleteGoogleEventsByCalendar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGoogleEventsByCalendar'
type Store_DeleteGoogleEventsByCalendar_Call struct {
	*mock.Call
}

// DeleteGoogleEventsByCalendar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - calendarID string
func (_e *Store_Expecter) DeleteGoogleEventsByCalendar(ctx interface{}, userID interface{}, calendarID interface{}) *Store_DeleteGoogleEventsByCalendar_Call {
	return &Store_DeleteGoogleEventsByCalendar_Call{Call: _e.mock.On("DeleteGoogleEventsByCalendar", ctx, userID, calendarID)}
}

func (_c *Store_DeleteGoogleEventsByCalendar_Call) Run(run func(ctx context.Context, userID string, calendarID string)) *Store_DeleteGoogleEventsByCalendar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_DeleteGoogleEventsByCalendar_Call) Return(_a0 error) *Store_DeleteGoogleEventsByCalendar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DeleteGoogleEventsByCalendar_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_DeleteGoogleEventsByCalendar_Call {
	_c.Call.Return(run)
	return _c
}

// GetEpic provides a mock function with given fields: ctx, epicID, userID
func (_m *Store) GetEpic(ctx context.Context, epicID string, userID string) (*model.Epic, error) {
	ret := _m.Called(ctx, epicID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetEpic")
	}

	var r0 *model.Epic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Epic, error)); ok {
		return rf(ctx, epicID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Epic); ok {
		r0 = rf(ctx, epicID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Epic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, epicID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetEpic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEpic'
type Store_GetEpic_Call struct {
	*mock.Call
}

// GetEpic is a helper method to define mock.On call
//   - ctx context.Context
//   - epicID string
//   - userID string
func (_e *Store_Expecter) GetEpic(ctx interface{}, epicID interface{}, userID interface{}) *Store_GetEpic_Call {
	return &Store_GetEpic_Call{Call: _e.mock.On("GetEpic", ctx, epicID, userID)}
}

func (_c *Store_GetEpic_Call) Run(run func(ctx context.Context, epicID string, userID string)) *Store_GetEpic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_GetEpic_Call) Return(_a0 *model.Epic, _a1 error) *Store_GetEpic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetEpic_Call) RunAndReturn(run func(context.Context, string, string) (*model.Epic, error)) *Store_GetEpic_Call {
	_c.Call.Return(run)
	return _c
}

// GetGoogleCalendarSyncToken provides a mock function with given fields: ctx, userID, calendarID
func (_m *Store) GetGoogleCalendarSyncToken(ctx context.Context, userID string, calendarID string) (string, error) {
	ret := _m.Called(ctx, userID, calendarID)

	if len(ret) == 0 {
		panic("no return value specified for GetGoogleCalendarSyncToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, userID, calendarID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userID, calendarID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, calendarID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetGoogleCalendarSyncToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGoogleCalendarSyncToken'
type Store_GetGoogleCalendarSyncToken_Call struct {
	*mock.Call
}

// GetGoogleCalendarSyncToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - calendarID string
func (_e *Store_Expecter) GetGoogleCalendarSyncToken(ctx interface{}, userID interface{}, calendarID interface{}) *Store_GetGoogleCalendarSyncToken_Call {
	return &Store_GetGoogleCalendarSyncToken_Call{Call: _e.mock.On("GetGoogleCalendarSyncToken", ctx, userID, calendarID)}
}

func (_c *Store_GetGoogleCalendarSyncToken_Call) Run(run func(ctx context.Context, userID string, calendarID string)) *Store_GetGoogleCalendarSyncToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_GetGoogleCalendarSyncToken_Call) Return(_a0 string, _a1 error) *Store_GetGoogleCalendarSyncToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetGoogleCalendarSyncToken_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *Store_GetGoogleCalendarSyncToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSettings provides a mock function with given fields: ctx, userID
func (_m *Store) GetUserSettings(ctx context.Context, userID string) (*model.UserSettings, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSettings")
	}

	var r0 *model.UserSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserSettings, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserSettings); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetUserSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSettings'
type Store_GetUserSettings_Call struct {
	*mock.Call
}

// GetUserSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) GetUserSettings(ctx interface{}, userID interface{}) *Store_GetUserSettings_Call {
	return &Store_GetUserSettings_Call{Call: _e.mock.On("GetUserSettings", ctx, userID)}
}

func (_c *Store_GetUserSettings_Call) Run(run func(ctx context.Context, userID string)) *Store_GetUserSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetUserSettings_Call) Return(_a0 *model.UserSettings, _a1 error) *Store_GetUserSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetUserSettings_Call) RunAndReturn(run func(context.Context, string) (*model.UserSettings, error)) *Store_GetUserSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkTask provides a mock function with given fields: ctx, taskID, userID
func (_m *Store) GetWorkTask(ctx context.Context, taskID string, userID string) (*model.WorkTask, error) {
	ret := _m.Called(ctx, taskID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkTask")
	}

	var r0 *model.WorkTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.WorkTask, error)); ok {
		return rf(ctx, taskID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.WorkTask); ok {
		r0 = rf(ctx, taskID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WorkTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, taskID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetWorkTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkTask'
type Store_GetWorkTask_Call struct {
	*mock.Call
}

// GetWorkTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - userID string
func (_e *Store_Expecter) GetWorkTask(ctx interface{}, taskID interface{}, userID interface{}) *Store_GetWorkTask_Call {
	return &Store_GetWorkTask_Call{Call: _e.mock.On("GetWorkTask", ctx, taskID, userID)}
}

func (_c *Store_GetWorkTask_Call) Run(run func(ctx context.Context, taskID string, userID string)) *Store_GetWorkTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_GetWorkTask_Call) Return(_a0 *model.WorkTask, _a1 error) *Store_GetWorkTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetWorkTask_Call) RunAndReturn(run func(context.Context, string, string) (*model.WorkTask, error)) *Store_GetWorkTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListEpicsByUser provides a mock function with given fields: ctx, userID
func (_m *Store) ListEpicsByUser(ctx context.Context, userID string) ([]model.Epic, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListEpicsByUser")
	}

	var r0 []model.Epic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Epic, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Epic); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Epic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListEpicsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEpicsByUser'
type Store_ListEpicsByUser_Call struct {
	*mock.Call
}

// ListEpicsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) ListEpicsByUser(ctx interface{}, userID interface{}) *Store_ListEpicsByUser_Call {
	return &Store_ListEpicsByUser_Call{Call: _e.mock.On("ListEpicsByUser", ctx, userID)}
}

func (_c *Store_ListEpicsByUser_Call) Run(run func(ctx context.Context, userID string)) *Store_ListEpicsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ListEpicsByUser_Call) Return(_a0 []model.Epic, _a1 error) *Store_ListEpicsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListEpicsByUser_Call) RunAndReturn(run func(context.Context, string) ([]model.Epic, error)) *Store_ListEpicsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListGoogleConnectedSettings provides a mock function with given fields: ctx
func (_m *Store) ListGoogleConnectedSettings(ctx context.Context) ([]model.UserSettings, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListGoogleConnectedSettings")
	}

	var r0 []model.UserSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.UserSettings, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.UserSettings); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListGoogleConnectedSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGoogleConnectedSettings'
type Store_ListGoogleConnectedSettings_Call struct {
	*mock.Call
}

// ListGoogleConnectedSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Store_Expecter) ListGoogleConnectedSettings(ctx interface{}) *Store_ListGoogleConnectedSettings_Call {
	return &Store_ListGoogleConnectedSettings_Call{Call: _e.mock.On("ListGoogleConnectedSettings", ctx)}
}

func (_c *Store_ListGoogleConnectedSettings_Call) Run(run func(ctx context.Context)) *Store_ListGoogleConnectedSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Store_ListGoogleConnectedSettings_Call) Return(_a0 []model.UserSettings, _a1 error) *Store_ListGoogleConnectedSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListGoogleConnectedSettings_Call) RunAndReturn(run func(context.Context) ([]model.UserSettings, error)) *Store_ListGoogleConnectedSettings_Call {
	_c.Call.Return(run)
	return _c
}

// ListGoogleEventIDs provides a mock function with given fields: ctx, userID
func (_m *Store) ListGoogleEventIDs(ctx context.Context, userID string) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListGoogleEventIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListGoogleEventIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGoogleEventIDs'
type Store_ListGoogleEventIDs_Call struct {
	*mock.Call
}

// ListGoogleEventIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) ListGoogleEventIDs(ctx interface{}, userID interface{}) *Store_ListGoogleEventIDs_Call {
	return &Store_ListGoogleEventIDs_Call{Call: _e.mock.On("ListGoogleEventIDs", ctx, userID)}
}

func (_c *Store_ListGoogleEventIDs_Call) Run(run func(ctx context.Context, userID string)) *Store_ListGoogleEventIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ListGoogleEventIDs_Call) Return(_a0 []string, _a1 error) *Store_ListGoogleEventIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListGoogleEventIDs_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *Store_ListGoogleEventIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ListGoogleEvents provides a mock function with given fields: ctx, userID, calendarID, timeMin, timeMax
func (_m *Store) ListGoogleEvents(ctx context.Context, userID string, calendarID string, timeMin time.Time, timeMax time.Time) ([]model.CachedCalendarEvent, error) {
	ret := _m.Called(ctx, userID, calendarID, timeMin, timeMax)

	if len(ret) == 0 {
		panic("no return value specified for ListGoogleEvents")
	}

	var r0 []model.CachedCalendarEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) ([]model.CachedCalendarEvent, error)); ok {
		return rf(ctx, userID, calendarID, timeMin, timeMax)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) []model.CachedCalendarEvent); ok {
		r0 = rf(ctx, userID, calendarID, timeMin, timeMax)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CachedCalendarEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, calendarID, timeMin, timeMax)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListGoogleEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGoogleEvents'
type Store_ListGoogleEvents_Call struct {
	*mock.Call
}

// ListGoogleEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - calendarID string
//   - timeMin time.Time
//   - timeMax time.Time
func (_e *Store_Expecter) ListGoogleEvents(ctx interface{}, userID interface{}, calendarID interface{}, timeMin interface{}, timeMax interface{}) *Store_ListGoogleEvents_Call {
	return &Store_ListGoogleEvents_Call{Call: _e.mock.On("ListGoogleEvents", ctx, userID, calendarID, timeMin, timeMax)}
}

func (_c *Store_ListGoogleEvents_Call) Run(run func(ctx context.Context, userID string, calendarID string, timeMin time.Time, timeMax time.Time)) *Store_ListGoogleEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *Store_ListGoogleEvents_Call) Return(_a0 []model.CachedCalendarEvent, _a1 error) *Store_ListGoogleEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListGoogleEvents_Call) RunAndReturn(run func(context.Context, string, string, time.Time, time.Time) ([]model.CachedCalendarEvent, error)) *Store_ListGoogleEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListGoogleEventsForUser provides a mock function with given fields: ctx, userID, timeMin, timeMax
func (_m *Store) ListGoogleEventsForUser(ctx context.Context, userID string, timeMin time.Time, timeMax time.Time) ([]model.CachedCalendarEvent, error) {
	ret := _m.Called(ctx, userID, timeMin, timeMax)

	if len(ret) == 0 {
		panic("no return value specified for ListGoogleEventsForUser")
	}

	var r0 []model.CachedCalendarEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]model.CachedCalendarEvent, error)); ok {
		return rf(ctx, userID, timeMin, timeMax)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []model.CachedCalendarEvent); ok {
		r0 = rf(ctx, userID, timeMin, timeMax)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CachedCalendarEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, timeMin, timeMax)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListGoogleEventsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGoogleEventsForUser'
type Store_ListGoogleEventsForUser_Call struct {
	*mock.Call
}

// ListGoogleEventsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - timeMin time.Time
//   - timeMax time.Time
func (_e *Store_Expecter) ListGoogleEventsForUser(ctx interface{}, userID interface{}, timeMin interface{}, timeMax interface{}) *Store_ListGoogleEventsForUser_Call {
	return &Store_ListGoogleEventsForUser_Call{Call: _e.mock.On("ListGoogleEventsForUser", ctx, userID, timeMin, timeMax)}
}

func (_c *Store_ListGoogleEventsForUser_Call) Run(run func(ctx context.Context, userID string, timeMin time.Time, timeMax time.Time)) *Store_ListGoogleEventsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *Store_ListGoogleEventsForUser_Call) Return(_a0 []model.CachedCalendarEvent, _a1 error) *Store_ListGoogleEventsForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListGoogleEventsForUser_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]model.CachedCalendarEvent, error)) *Store_ListGoogleEventsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkTasksByUser provides a mock function with given fields: ctx, userID
func (_m *Store) ListWorkTasksByUser(ctx context.Context, userID string) ([]model.WorkTask, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkTasksByUser")
	}

	var r0 []model.WorkTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.WorkTask, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.WorkTask); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.WorkTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListWorkTasksByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkTasksByUser'
type Store_ListWorkTasksByUser_Call struct {
	*mock.Call
}

// ListWorkTasksByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) ListWorkTasksByUser(ctx interface{}, userID interface{}) *Store_ListWorkTasksByUser_Call {
	return &Store_ListWorkTasksByUser_Call{Call: _e.mock.On("ListWorkTasksByUser", ctx, userID)}
}

func (_c *Store_ListWorkTasksByUser_Call) Run(run func(ctx context.Context, userID string)) *Store_ListWorkTasksByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ListWorkTasksByUser_Call) Return(_a0 []model.WorkTask, _a1 error) *Store_ListWorkTasksByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListWorkTasksByUser_Call) RunAndReturn(run func(context.Context, string) ([]model.WorkTask, error)) *Store_ListWorkTasksByUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkGoogleReauthRequired provides a mock function with given fields: ctx, userID
func (_m *Store) MarkGoogleReauthRequired(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkGoogleReauthRequired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_MarkGoogleReauthRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkGoogleReauthRequired'
type Store_MarkGoogleReauthRequired_Call struct {
	*mock.Call
}

// MarkGoogleReauthRequired is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) MarkGoogleReauthRequired(ctx interface{}, userID interface{}) *Store_MarkGoogleReauthRequired_Call {
	return &Store_MarkGoogleReauthRequired_Call{Call: _e.mock.On("MarkGoogleReauthRequired", ctx, userID)}
}

func (_c *Store_MarkGoogleReauthRequired_Call) Run(run func(ctx context.Context, userID string)) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_MarkGoogleReauthRequired_Call) Return(_a0 error) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_MarkGoogleReauthRequired_Call) RunAndReturn(run func(context.Context, string) error) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Return(run)
	return _c
}

// MarkZoomReauthRequired provides a mock function with given fields: ctx, userID
func (_m *Store) MarkZoomReauthRequired(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkZoomReauthRequired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_MarkZoomReauthRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkZoomReauthRequired'
type Store_MarkZoomReauthRequired_Call struct {
	*mock.Call
}

// MarkZoomReauthRequired is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) MarkZoomReauthRequired(ctx interface{}, userID interface{}) *Store_MarkZoomReauthRequired_Call {
	return &Store_MarkZoomReauthRequired_Call{Call: _e.mock.On("MarkZoomReauthRequired", ctx, userID)}
}

func (_c *Store_MarkZoomReauthRequired_Call) Run(run func(ctx context.Context, userID string)) *Store_MarkZoomReauthRequired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_MarkZoomReauthRequired_Call) Return(_a0 error) *Store_MarkZoomReauthRequired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_MarkZoomReauthRequired_Call) RunAndReturn(run func(context.Context, string) error) *Store_MarkZoomReauthRequired_Call {
	_c.Call.Return(run)
	return _c
}

// PatchWorkTask provides a mock function with given fields: ctx, taskID, userID, patch
func (_m *Store) PatchWorkTask(ctx context.Context, taskID string, userID string, patch repository.WorkTaskPatch) (*model.WorkTask, error) {
	ret := _m.Called(ctx, taskID, userID, patch)

	if len(ret) == 0 {
		panic("no return value specified for PatchWorkTask")
	}

	var r0 *model.WorkTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, repository.WorkTaskPatch) (*model.WorkTask, error)); ok {
		return rf(ctx, taskID, userID, patch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, repository.WorkTaskPatch) *model.WorkTask); ok {
		r0 = rf(ctx, taskID, userID, patch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WorkTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, repository.WorkTaskPatch) error); ok {
		r1 = rf(ctx, taskID, userID, patch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_PatchWorkTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchWorkTask'
type Store_PatchWorkTask_Call struct {
	*mock.Call
}

// PatchWorkTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - userID string
//   - patch repository.WorkTaskPatch
func (_e *Store_Expecter) PatchWorkTask(ctx interface{}, taskID interface{}, userID interface{}, patch interface{}) *Store_PatchWorkTask_Call {
	return &Store_PatchWorkTask_Call{Call: _e.mock.On("PatchWorkTask", ctx, taskID, userID, patch)}
}

func (_c *Store_PatchWorkTask_Call) Run(run func(ctx context.Context, taskID string, userID string, patch repository.WorkTaskPatch)) *Store_PatchWorkTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(repository.WorkTaskPatch))
	})
	return _c
}

func (_c *Store_PatchWorkTask_Call) Return(_a0 *model.WorkTask, _a1 error) *Store_PatchWorkTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_PatchWorkTask_Call) RunAndReturn(run func(context.Context, string, string, repository.WorkTaskPatch) (*model.WorkTask, error)) *Store_PatchWorkTask_Call {
	_c.Call.Return(run)
	return _c
}

// SaveGoogleCalendarSyncToken provides a mock function with given fields: ctx, userID, calendarID, syncToken
func (_m *Store) SaveGoogleCalendarSyncToken(ctx context.Context, userID string, calendarID string, syncToken string) error {
	ret := _m.Called(ctx, userID, calendarID, syncToken)

	if len(ret) == 0 {
		panic("no return value specified for SaveGoogleCalendarSyncToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, calendarID, syncToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveGoogleCalendarSyncToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveGoogleCalendarSyncToken'
type Store_SaveGoogleCalendarSyncToken_Call struct {
	*mock.Call
}

// SaveGoogleCalendarSyncToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - calendarID string
//   - syncToken string
func (_e *Store_Expecter) SaveGoogleCalendarSyncToken(ctx interface{}, userID interface{}, calendarID interface{}, syncToken interface{}) *Store_SaveGoogleCalendarSyncToken_Call {
	return &Store_SaveGoogleCalendarSyncToken_Call{Call: _e.mock.On("SaveGoogleCalendarSyncToken", ctx, userID, calendarID, syncToken)}
}

func (_c *Store_SaveGoogleCalendarSyncToken_Call) Run(run func(ctx context.Context, userID string, calendarID string, syncToken string)) *Store_SaveGoogleCalendarSyncToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Store_SaveGoogleCalendarSyncToken_Call) Return(_a0 error) *Store_SaveGoogleCalendarSyncToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveGoogleCalendarSyncToken_Call) RunAndReturn(run func(context.Context, string, string, string) error) *Store_SaveGoogleCalendarSyncToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveGoogleOAuthState provides a mock function with given fields: ctx, userID, state
func (_m *Store) SaveGoogleOAuthState(ctx context.Context, userID string, state string) error {
	ret := _m.Called(ctx, userID, state)

	if len(ret) == 0 {
		panic("no return value specified for SaveGoogleOAuthState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveGoogleOAuthState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveGoogleOAuthState'
type Store_SaveGoogleOAuthState_Call struct {
	*mock.Call
}

// SaveGoogleOAuthState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - state string
func (_e *Store_Expecter) SaveGoogleOAuthState(ctx interface{}, userID interface{}, state interface{}) *Store_SaveGoogleOAuthState_Call {
	return &Store_SaveGoogleOAuthState_Call{Call: _e.mock.On("SaveGoogleOAuthState", ctx, userID, state)}
}

func (_c *Store_SaveGoogleOAuthState_Call) Run(run func(ctx context.Context, userID string, state string)) *Store_SaveGoogleOAuthState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_SaveGoogleOAuthState_Call) Return(_a0 error) *Store_SaveGoogleOAuthState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveGoogleOAuthState_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_SaveGoogleOAuthState_Call {
	_c.Call.Return(run)
	return _c
}

// SaveGoogleRefreshToken provides a mock function with given fields: ctx, userID, refreshToken
func (_m *Store) SaveGoogleRefreshToken(ctx context.Context, userID string, refreshToken string) error {
	ret := _m.Called(ctx, userID, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for SaveGoogleRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveGoogleRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveGoogleRefreshToken'
type Store_SaveGoogleRefreshToken_Call struct {
	*mock.Call
}

// SaveGoogleRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - refreshToken string
func (_e *Store_Expecter) SaveGoogleRefreshToken(ctx interface{}, userID interface{}, refreshToken interface{}) *Store_SaveGoogleRefreshToken_Call {
	return &Store_SaveGoogleRefreshToken_Call{Call: _e.mock.On("SaveGoogleRefreshToken", ctx, userID, refreshToken)}
}

func (_c *Store_SaveGoogleRefreshToken_Call) Run(run func(ctx context.Context, userID string, refreshToken string)) *Store_SaveGoogleRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_SaveGoogleRefreshToken_Call) Return(_a0 error) *Store_SaveGoogleRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveGoogleRefreshToken_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_SaveGoogleRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveZoomOAuthState provides a mock function with given fields: ctx, userID, state
func (_m *Store) SaveZoomOAuthState(ctx context.Context, userID string, state string) error {
	ret := _m.Called(ctx, userID, state)

	if len(ret) == 0 {
		panic("no return value specified for SaveZoomOAuthState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveZoomOAuthState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveZoomOAuthState'
type Store_SaveZoomOAuthState_Call struct {
	*mock.Call
}

// SaveZoomOAuthState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - state string
func (_e *Store_Expecter) SaveZoomOAuthState(ctx interface{}, userID interface{}, state interface{}) *Store_SaveZoomOAuthState_Call {
	return &Store_SaveZoomOAuthState_Call{Call: _e.mock.On("SaveZoomOAuthState", ctx, userID, state)}
}

func (_c *Store_SaveZoomOAuthState_Call) Run(run func(ctx context.Context, userID string, state string)) *Store_SaveZoomOAuthState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_SaveZoomOAuthState_Call) Return(_a0 error) *Store_SaveZoomOAuthState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveZoomOAuthState_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_SaveZoomOAuthState_Call {
	_c.Call.Return(run)
	return _c
}

// SaveZoomRefreshToken provides a mock function with given fields: ctx, userID, refreshToken
func (_m *Store) SaveZoomRefreshToken(ctx context.Context, userID string, refreshToken string) error {
	ret := _m.Called(ctx, userID, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for SaveZoomRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveZoomRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveZoomRefreshToken'
type Store_SaveZoomRefreshToken_Call struct {
	*mock.Call
}

// SaveZoomRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - refreshToken string
func (_e *Store_Expecter) SaveZoomRefreshToken(ctx interface{}, userID interface{}, refreshToken interface{}) *Store_SaveZoomRefreshToken_Call {
	return &Store_SaveZoomRefreshToken_Call{Call: _e.mock.On("SaveZoomRefreshToken", ctx, userID, refreshToken)}
}

func (_c *Store_SaveZoomRefreshToken_Call) Run(run func(ctx context.Context, userID string, refreshToken string)) *Store_SaveZoomRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_SaveZoomRefreshToken_Call) Return(_a0 error) *Store_SaveZoomRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveZoomRefreshToken_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_SaveZoomRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertGoogleEvents provides a mock function with given fields: ctx, userID, events
func (_m *Store) UpsertGoogleEvents(ctx context.Context, userID string, events []model.CachedCalendarEvent) error {
	ret := _m.Called(ctx, userID, events)

	if len(ret) == 0 {
		panic("no return value specified for UpsertGoogleEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.CachedCalendarEvent) error); ok {
		r0 = rf(ctx, userID, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_UpsertGoogleEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertGoogleEvents'
type Store_UpsertGoogleEvents_Call struct {
	*mock.Call
}

// UpsertGoogleEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - events []model.CachedCalendarEvent
func (_e *Store_Expecter) UpsertGoogleEvents(ctx interface{}, userID interface{}, events interface{}) *Store_UpsertGoogleEvents_Call {
	return &Store_UpsertGoogleEvents_Call{Call: _e.mock.On("UpsertGoogleEvents", ctx, userID, events)}
}

func (_c *Store_UpsertGoogleEvents_Call) Run(run func(ctx context.Context, userID string, events []model.CachedCalendarEvent)) *Store_UpsertGoogleEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]model.CachedCalendarEvent))
	})
	return _c
}

func (_c *Store_UpsertGoogleEvents_Call) Return(_a0 error) *Store_UpsertGoogleEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_UpsertGoogleEvents_Call) RunAndReturn(run func(context.Context, string, []model.CachedCalendarEvent) error) *Store_UpsertGoogleEvents_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUserSettings provides a mock function with given fields: ctx, userID, patch
func (_m *Store) UpsertUserSettings(ctx context.Context, userID string, patch repository.UserSettingsPatch) (*model.UserSettings, error) {
	ret := _m.Called(ctx, userID, patch)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserSettings")
	}

	var r0 *model.UserSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, repository.UserSettingsPatch) (*model.UserSettings, error)); ok {
		return rf(ctx, userID, patch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, repository.UserSettingsPatch) *model.UserSettings); ok {
		r0 = rf(ctx, userID, patch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, repository.UserSettingsPatch) error); ok {
		r1 = rf(ctx, userID, patch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_UpsertUserSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserSettings'
type Store_UpsertUserSettings_Call struct {
	*mock.Call
}

// UpsertUserSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - patch repository.UserSettingsPatch
func (_e *Store_Expecter) UpsertUserSettings(ctx interface{}, userID interface{}, patch interface{}) *Store_UpsertUserSettings_Call {
	return &Store_UpsertUserSettings_Call{Call: _e.mock.On("UpsertUserSettings", ctx, userID, patch)}
}

func (_c *Store_UpsertUserSettings_Call) Run(run func(ctx context.Context, userID string, patch repository.UserSettingsPatch)) *Store_UpsertUserSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(repository.UserSettingsPatch))
	})
	return _c
}

func (_c *Store_UpsertUserSettings_Call) Return(_a0 *model.UserSettings, _a1 error) *Store_UpsertUserSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_UpsertUserSettings_Call) RunAndReturn(run func(context.Context, string, repository.UserSettingsPatch) (*model.UserSettings, error)) *Store_UpsertUserSettings_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
