// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	model "github.com/dobriygolang/project-nordly/services/tracker/internal/tracker/model"
	repository "github.com/dobriygolang/project-nordly/services/tracker/internal/tracker/repository"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// ApplyGoogleCalendarSyncDelta provides a mock function with given fields: ctx, userID, delta
func (_m *Store) ApplyGoogleCalendarSyncDelta(ctx context.Context, userID string, delta model.CalendarSyncDelta) error {
	ret := _m.Called(ctx, userID, delta)

	if len(ret) == 0 {
		panic("no return value specified for ApplyGoogleCalendarSyncDelta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CalendarSyncDelta) error); ok {
		r0 = rf(ctx, userID, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_ApplyGoogleCalendarSyncDelta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyGoogleCalendarSyncDelta'
type Store_ApplyGoogleCalendarSyncDelta_Call struct {
	*mock.Call
}

// ApplyGoogleCalendarSyncDelta is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - delta model.CalendarSyncDelta
func (_e *Store_Expecter) ApplyGoogleCalendarSyncDelta(ctx interface{}, userID interface{}, delta interface{}) *Store_ApplyGoogleCalendarSyncDelta_Call {
	return &Store_ApplyGoogleCalendarSyncDelta_Call{Call: _e.mock.On("ApplyGoogleCalendarSyncDelta", ctx, userID, delta)}
}

func (_c *Store_ApplyGoogleCalendarSyncDelta_Call) Run(run func(ctx context.Context, userID string, delta model.CalendarSyncDelta)) *Store_ApplyGoogleCalendarSyncDelta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CalendarSyncDelta))
	})
	return _c
}

func (_c *Store_ApplyGoogleCalendarSyncDelta_Call) Return(_a0 error) *Store_ApplyGoogleCalendarSyncDelta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_ApplyGoogleCalendarSyncDelta_Call) RunAndReturn(run func(context.Context, string, model.CalendarSyncDelta) error) *Store_ApplyGoogleCalendarSyncDelta_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumeGoogleOAuthState provides a mock function with given fields: ctx, state
func (_m *Store) ConsumeGoogleOAuthState(ctx context.Context, state string) (string, error) {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeGoogleOAuthState")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ConsumeGoogleOAuthState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeGoogleOAuthState'
type Store_ConsumeGoogleOAuthState_Call struct {
	*mock.Call
}

// ConsumeGoogleOAuthState is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *Store_Expecter) ConsumeGoogleOAuthState(ctx interface{}, state interface{}) *Store_ConsumeGoogleOAuthState_Call {
	return &Store_ConsumeGoogleOAuthState_Call{Call: _e.mock.On("ConsumeGoogleOAuthState", ctx, state)}
}

func (_c *Store_ConsumeGoogleOAuthState_Call) Run(run func(ctx context.Context, state string)) *Store_ConsumeGoogleOAuthState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ConsumeGoogleOAuthState_Call) Return(_a0 string, _a1 error) *Store_ConsumeGoogleOAuthState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ConsumeGoogleOAuthState_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Store_ConsumeGoogleOAuthState_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumeZoomOAuthState provides a mock function with given fields: ctx, state
func (_m *Store) ConsumeZoomOAuthState(ctx context.Context, state string) (string, error) {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeZoomOAuthState")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ConsumeZoomOAuthState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeZoomOAuthState'
type Store_ConsumeZoomOAuthState_Call struct {
	*mock.Call
}

// ConsumeZoomOAuthState is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *Store_Expecter) ConsumeZoomOAuthState(ctx interface{}, state interface{}) *Store_ConsumeZoomOAuthState_Call {
	return &Store_ConsumeZoomOAuthState_Call{Call: _e.mock.On("ConsumeZoomOAuthState", ctx, state)}
}

func (_c *Store_ConsumeZoomOAuthState_Call) Run(run func(ctx context.Context, state string)) *Store_ConsumeZoomOAuthState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ConsumeZoomOAuthState_Call) Return(_a0 string, _a1 error) *Store_ConsumeZoomOAuthState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ConsumeZoomOAuthState_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Store_ConsumeZoomOAuthState_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDefaultEpics provides a mock function with given fields: ctx, userID, seeds
func (_m *Store) CreateDefaultEpics(ctx context.Context, userID string, seeds []model.EpicSeed) ([]model.Epic, error) {
	ret := _m.Called(ctx, userID, seeds)

	if len(ret) == 0 {
		panic("no return value specified for CreateDefaultEpics")
	}

	var r0 []model.Epic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.EpicSeed) ([]model.Epic, error)); ok {
		return rf(ctx, userID, seeds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.EpicSeed) []model.Epic); ok {
		r0 = rf(ctx, userID, seeds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Epic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []model.EpicSeed) error); ok {
		r1 = rf(ctx, userID, seeds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CreateDefaultEpics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDefaultEpics'
type Store_CreateDefaultEpics_Call struct {
	*mock.Call
}

// CreateDefaultEpics is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - seeds []model.EpicSeed
func (_e *Store_Expecter) CreateDefaultEpics(ctx interface{}, userID interface{}, seeds interface{}) *Store_CreateDefaultEpics_Call {
	return &Store_CreateDefaultEpics_Call{Call: _e.mock.On("CreateDefaultEpics", ctx, userID, seeds)}
}

func (_c *Store_CreateDefaultEpics_Call) Run(run func(ctx context.Context, userID string, seeds []model.EpicSeed)) *Store_CreateDefaultEpics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]model.EpicSeed))
	})
	return _c
}

func (_c *Store_CreateDefaultEpics_Call) Return(_a0 []model.Epic, _a1 error) *Store_CreateDefaultEpics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CreateDefaultEpics_Call) RunAndReturn(run func(context.Context, string, []model.EpicSeed) ([]model.Epic, error)) *Store_CreateDefaultEpics_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEpic provides a mock function with given fields: ctx, userID, name, color
func (_m *Store) CreateEpic(ctx context.Context, userID string, name string, color string) (*model.Epic, error) {
	ret := _m.Called(ctx, userID, name, color)

	if len(ret) == 0 {
		panic("no return value specified for CreateEpic")
	}

	var r0 *model.Epic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.Epic, error)); ok {
		return rf(ctx, userID, name, color)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.Epic); ok {
		r0 = rf(ctx, userID, name, color)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Epic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, name, color)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CreateEpic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEpic'
type Store_CreateEpic_Call struct {
	*mock.Call
}

// CreateEpic is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
//   - color string
func (_e *Store_Expecter) CreateEpic(ctx interface{}, userID interface{}, name interface{}, color interface{}) *Store_CreateEpic_Call {
	return &Store_CreateEpic_Call{Call: _e.mock.On("CreateEpic", ctx, userID, name, color)}
}

func (_c *Store_CreateEpic_Call) Run(run func(ctx context.Context, userID string, name string, color string)) *Store_CreateEpic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Store_CreateEpic_Call) Return(_a0 *model.Epic, _a1 error) *Store_CreateEpic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CreateEpic_Call) RunAndReturn(run func(context.Context, string, string, string) (*model.Epic, error)) *Store_CreateEpic_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorkTask provides a mock function with given fields: ctx, userID, kind, title, status
func (_m *Store) CreateWorkTask(ctx context.Context, userID string, kind model.WorkKind, title string, status model.WorkStatus) (*model.WorkTask, error) {
	ret := _m.Called(ctx, userID, kind, title, status)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkTask")
	}

	var r0 *model.WorkTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.WorkKind, string, model.WorkStatus) (*model.WorkTask, error)); ok {
		return rf(ctx, userID, kind, title, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.WorkKind, string, model.WorkStatus) *model.WorkTask); ok {
		r0 = rf(ctx, userID, kind, title, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WorkTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.WorkKind, string, model.WorkStatus) error); ok {
		r1 = rf(ctx, userID, kind, title, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CreateWorkTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkTask'
type Store_CreateWorkTask_Call struct {
	*mock.Call
}

// CreateWorkTask is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - kind model.WorkKind
//   - title string
//   - status model.WorkStatus
func (_e *Store_Expecter) CreateWorkTask(ctx interface{}, userID interface{}, kind interface{}, title interface{}, status interface{}) *Store_CreateWorkTask_Call {
	return &Store_CreateWorkTask_Call{Call: _e.mock.On("CreateWorkTask", ctx, userID, kind, title, status)}
}

func (_c *Store_CreateWorkTask_Call) Run(run func(ctx context.Context, userID string, kind model.WorkKind, title string, status model.WorkStatus)) *Store_CreateWorkTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.WorkKind), args[3].(string), args[4].(model.WorkStatus))
	})
	return _c
}

func (_c *Store_CreateWorkTask_Call) Return(_a0 *model.WorkTask, _a1 error) *Store_CreateWorkTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CreateWorkTask_Call) RunAndReturn(run func(context.Context, string, model.WorkKind, string, model.WorkStatus) (*model.WorkTask, error)) *Store_CreateWorkTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGoogleEventLocal provides a mock function with given fields: ctx, userID, ref
func (_m *Store) DeleteGoogleEventLocal(ctx context.Context, userID string, ref model.GoogleEventRef) error {
	ret := _m.Called(ctx, userID, ref)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGoogleEventLocal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.GoogleEventRef) error); ok {
		r0 = rf(ctx, userID, ref)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DeleteGoogleEventLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGoogleEventLocal'
type Store_DeleteGoogleEventLocal_Call struct {
	*mock.Call
}

// DeleteGoogleEventLocal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - ref model.GoogleEventRef
func (_e *Store_Expecter) DeleteGoogleEventLocal(ctx interface{}, userID interface{}, ref interface{}) *Store_DeleteGoogleEventLocal_Call {
	return &Store_DeleteGoogleEventLocal_Call{Call: _e.mock.On("DeleteGoogleEventLocal", ctx, userID, ref)}
}

func (_c *Store_DeleteGoogleEventLocal_Call) Run(run func(ctx context.Context, userID string, ref model.GoogleEventRef)) *Store_DeleteGoogleEventLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.GoogleEventRef))
	})
	return _c
}

func (_c *Store_DeleteGoogleEventLocal_Call) Return(_a0 error) *Store_DeleteGoogleEventLocal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DeleteGoogleEventLocal_Call) RunAndReturn(run func(context.Context, string, model.GoogleEventRef) error) *Store_DeleteGoogleEventLocal_Call {
	_c.Call.Return(run)
	return _c
}

// DisconnectGoogleLocal provides a mock function with given fields: ctx, userID
func (_m *Store) DisconnectGoogleLocal(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DisconnectGoogleLocal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DisconnectGoogleLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectGoogleLocal'
type Store_DisconnectGoogleLocal_Call struct {
	*mock.Call
}

// DisconnectGoogleLocal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) DisconnectGoogleLocal(ctx interface{}, userID interface{}) *Store_DisconnectGoogleLocal_Call {
	return &Store_DisconnectGoogleLocal_Call{Call: _e.mock.On("DisconnectGoogleLocal", ctx, userID)}
}

func (_c *Store_DisconnectGoogleLocal_Call) Run(run func(ctx context.Context, userID string)) *Store_DisconnectGoogleLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_DisconnectGoogleLocal_Call) Return(_a0 error) *Store_DisconnectGoogleLocal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DisconnectGoogleLocal_Call) RunAndReturn(run func(context.Context, string) error) *Store_DisconnectGoogleLocal_Call {
	_c.Call.Return(run)
	return _c
}

// DisconnectZoomLocal provides a mock function with given fields: ctx, userID
func (_m *Store) DisconnectZoomLocal(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DisconnectZoomLocal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DisconnectZoomLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectZoomLocal'
type Store_DisconnectZoomLocal_Call struct {
	*mock.Call
}

// DisconnectZoomLocal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) DisconnectZoomLocal(ctx interface{}, userID interface{}) *Store_DisconnectZoomLocal_Call {
	return &Store_DisconnectZoomLocal_Call{Call: _e.mock.On("DisconnectZoomLocal", ctx, userID)}
}

func (_c *Store_DisconnectZoomLocal_Call) Run(run func(ctx context.Context, userID string)) *Store_DisconnectZoomLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_DisconnectZoomLocal_Call) Return(_a0 error) *Store_DisconnectZoomLocal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DisconnectZoomLocal_Call) RunAndReturn(run func(context.Context, string) error) *Store_DisconnectZoomLocal_Call {
	_c.Call.Return(run)
	return _c
}

// GetEpic provides a mock function with given fields: ctx, epicID, userID
func (_m *Store) GetEpic(ctx context.Context, epicID string, userID string) (*model.Epic, error) {
	ret := _m.Called(ctx, epicID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetEpic")
	}

	var r0 *model.Epic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Epic, error)); ok {
		return rf(ctx, epicID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Epic); ok {
		r0 = rf(ctx, epicID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Epic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, epicID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetEpic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEpic'
type Store_GetEpic_Call struct {
	*mock.Call
}

// GetEpic is a helper method to define mock.On call
//   - ctx context.Context
//   - epicID string
//   - userID string
func (_e *Store_Expecter) GetEpic(ctx interface{}, epicID interface{}, userID interface{}) *Store_GetEpic_Call {
	return &Store_GetEpic_Call{Call: _e.mock.On("GetEpic", ctx, epicID, userID)}
}

func (_c *Store_GetEpic_Call) Run(run func(ctx context.Context, epicID string, userID string)) *Store_GetEpic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_GetEpic_Call) Return(_a0 *model.Epic, _a1 error) *Store_GetEpic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetEpic_Call) RunAndReturn(run func(context.Context, string, string) (*model.Epic, error)) *Store_GetEpic_Call {
	_c.Call.Return(run)
	return _c
}

// GetGoogleCalendarSyncToken provides a mock function with given fields: ctx, userID, calendarID
func (_m *Store) GetGoogleCalendarSyncToken(ctx context.Context, userID string, calendarID string) (string, error) {
	ret := _m.Called(ctx, userID, calendarID)

	if len(ret) == 0 {
		panic("no return value specified for GetGoogleCalendarSyncToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, userID, calendarID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userID, calendarID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, calendarID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetGoogleCalendarSyncToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGoogleCalendarSyncToken'
type Store_GetGoogleCalendarSyncToken_Call struct {
	*mock.Call
}

// GetGoogleCalendarSyncToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - calendarID string
func (_e *Store_Expecter) GetGoogleCalendarSyncToken(ctx interface{}, userID interface{}, calendarID interface{}) *Store_GetGoogleCalendarSyncToken_Call {
	return &Store_GetGoogleCalendarSyncToken_Call{Call: _e.mock.On("GetGoogleCalendarSyncToken", ctx, userID, calendarID)}
}

func (_c *Store_GetGoogleCalendarSyncToken_Call) Run(run func(ctx context.Context, userID string, calendarID string)) *Store_GetGoogleCalendarSyncToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_GetGoogleCalendarSyncToken_Call) Return(_a0 string, _a1 error) *Store_GetGoogleCalendarSyncToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetGoogleCalendarSyncToken_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *Store_GetGoogleCalendarSyncToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSettings provides a mock function with given fields: ctx, userID
func (_m *Store) GetUserSettings(ctx context.Context, userID string) (*model.UserSettings, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSettings")
	}

	var r0 *model.UserSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserSettings, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserSettings); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetUserSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSettings'
type Store_GetUserSettings_Call struct {
	*mock.Call
}

// GetUserSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) GetUserSettings(ctx interface{}, userID interface{}) *Store_GetUserSettings_Call {
	return &Store_GetUserSettings_Call{Call: _e.mock.On("GetUserSettings", ctx, userID)}
}

func (_c *Store_GetUserSettings_Call) Run(run func(ctx context.Context, userID string)) *Store_GetUserSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetUserSettings_Call) Return(_a0 *model.UserSettings, _a1 error) *Store_GetUserSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetUserSettings_Call) RunAndReturn(run func(context.Context, string) (*model.UserSettings, error)) *Store_GetUserSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkTask provides a mock function with given fields: ctx, taskID, userID
func (_m *Store) GetWorkTask(ctx context.Context, taskID string, userID string) (*model.WorkTask, error) {
	ret := _m.Called(ctx, taskID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkTask")
	}

	var r0 *model.WorkTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.WorkTask, error)); ok {
		return rf(ctx, taskID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.WorkTask); ok {
		r0 = rf(ctx, taskID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WorkTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, taskID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetWorkTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkTask'
type Store_GetWorkTask_Call struct {
	*mock.Call
}

// GetWorkTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - userID string
func (_e *Store_Expecter) GetWorkTask(ctx interface{}, taskID interface{}, userID interface{}) *Store_GetWorkTask_Call {
	return &Store_GetWorkTask_Call{Call: _e.mock.On("GetWorkTask", ctx, taskID, userID)}
}

func (_c *Store_GetWorkTask_Call) Run(run func(ctx context.Context, taskID string, userID string)) *Store_GetWorkTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_GetWorkTask_Call) Return(_a0 *model.WorkTask, _a1 error) *Store_GetWorkTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetWorkTask_Call) RunAndReturn(run func(context.Context, string, string) (*model.WorkTask, error)) *Store_GetWorkTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListEpicsByUser provides a mock function with given fields: ctx, userID
func (_m *Store) ListEpicsByUser(ctx context.Context, userID string) ([]model.Epic, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListEpicsByUser")
	}

	var r0 []model.Epic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Epic, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Epic); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Epic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListEpicsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEpicsByUser'
type Store_ListEpicsByUser_Call struct {
	*mock.Call
}

// ListEpicsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) ListEpicsByUser(ctx interface{}, userID interface{}) *Store_ListEpicsByUser_Call {
	return &Store_ListEpicsByUser_Call{Call: _e.mock.On("ListEpicsByUser", ctx, userID)}
}

func (_c *Store_ListEpicsByUser_Call) Run(run func(ctx context.Context, userID string)) *Store_ListEpicsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ListEpicsByUser_Call) Return(_a0 []model.Epic, _a1 error) *Store_ListEpicsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListEpicsByUser_Call) RunAndReturn(run func(context.Context, string) ([]model.Epic, error)) *Store_ListEpicsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListGoogleConnectedSettings provides a mock function with given fields: ctx
func (_m *Store) ListGoogleConnectedSettings(ctx context.Context) ([]model.UserSettings, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListGoogleConnectedSettings")
	}

	var r0 []model.UserSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.UserSettings, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.UserSettings); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListGoogleConnectedSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGoogleConnectedSettings'
type Store_ListGoogleConnectedSettings_Call struct {
	*mock.Call
}

// ListGoogleConnectedSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Store_Expecter) ListGoogleConnectedSettings(ctx interface{}) *Store_ListGoogleConnectedSettings_Call {
	return &Store_ListGoogleConnectedSettings_Call{Call: _e.mock.On("ListGoogleConnectedSettings", ctx)}
}

func (_c *Store_ListGoogleConnectedSettings_Call) Run(run func(ctx context.Context)) *Store_ListGoogleConnectedSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Store_ListGoogleConnectedSettings_Call) Return(_a0 []model.UserSettings, _a1 error) *Store_ListGoogleConnectedSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListGoogleConnectedSettings_Call) RunAndReturn(run func(context.Context) ([]model.UserSettings, error)) *Store_ListGoogleConnectedSettings_Call {
	_c.Call.Return(run)
	return _c
}

// ListGoogleEventRefs provides a mock function with given fields: ctx, userID
func (_m *Store) ListGoogleEventRefs(ctx context.Context, userID string) ([]model.GoogleEventRef, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListGoogleEventRefs")
	}

	var r0 []model.GoogleEventRef
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.GoogleEventRef, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.GoogleEventRef); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.GoogleEventRef)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListGoogleEventRefs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGoogleEventRefs'
type Store_ListGoogleEventRefs_Call struct {
	*mock.Call
}

// ListGoogleEventRefs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) ListGoogleEventRefs(ctx interface{}, userID interface{}) *Store_ListGoogleEventRefs_Call {
	return &Store_ListGoogleEventRefs_Call{Call: _e.mock.On("ListGoogleEventRefs", ctx, userID)}
}

func (_c *Store_ListGoogleEventRefs_Call) Run(run func(ctx context.Context, userID string)) *Store_ListGoogleEventRefs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ListGoogleEventRefs_Call) Return(_a0 []model.GoogleEventRef, _a1 error) *Store_ListGoogleEventRefs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListGoogleEventRefs_Call) RunAndReturn(run func(context.Context, string) ([]model.GoogleEventRef, error)) *Store_ListGoogleEventRefs_Call {
	_c.Call.Return(run)
	return _c
}

// ListGoogleEventsForUser provides a mock function with given fields: ctx, userID, timeMin, timeMax
func (_m *Store) ListGoogleEventsForUser(ctx context.Context, userID string, timeMin time.Time, timeMax time.Time) ([]model.CachedCalendarEvent, error) {
	ret := _m.Called(ctx, userID, timeMin, timeMax)

	if len(ret) == 0 {
		panic("no return value specified for ListGoogleEventsForUser")
	}

	var r0 []model.CachedCalendarEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]model.CachedCalendarEvent, error)); ok {
		return rf(ctx, userID, timeMin, timeMax)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []model.CachedCalendarEvent); ok {
		r0 = rf(ctx, userID, timeMin, timeMax)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CachedCalendarEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, timeMin, timeMax)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListGoogleEventsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGoogleEventsForUser'
type Store_ListGoogleEventsForUser_Call struct {
	*mock.Call
}

// ListGoogleEventsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - timeMin time.Time
//   - timeMax time.Time
func (_e *Store_Expecter) ListGoogleEventsForUser(ctx interface{}, userID interface{}, timeMin interface{}, timeMax interface{}) *Store_ListGoogleEventsForUser_Call {
	return &Store_ListGoogleEventsForUser_Call{Call: _e.mock.On("ListGoogleEventsForUser", ctx, userID, timeMin, timeMax)}
}

func (_c *Store_ListGoogleEventsForUser_Call) Run(run func(ctx context.Context, userID string, timeMin time.Time, timeMax time.Time)) *Store_ListGoogleEventsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *Store_ListGoogleEventsForUser_Call) Return(_a0 []model.CachedCalendarEvent, _a1 error) *Store_ListGoogleEventsForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListGoogleEventsForUser_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]model.CachedCalendarEvent, error)) *Store_ListGoogleEventsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkTasksByUser provides a mock function with given fields: ctx, userID
func (_m *Store) ListWorkTasksByUser(ctx context.Context, userID string) ([]model.WorkTask, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkTasksByUser")
	}

	var r0 []model.WorkTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.WorkTask, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.WorkTask); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.WorkTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListWorkTasksByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkTasksByUser'
type Store_ListWorkTasksByUser_Call struct {
	*mock.Call
}

// ListWorkTasksByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) ListWorkTasksByUser(ctx interface{}, userID interface{}) *Store_ListWorkTasksByUser_Call {
	return &Store_ListWorkTasksByUser_Call{Call: _e.mock.On("ListWorkTasksByUser", ctx, userID)}
}

func (_c *Store_ListWorkTasksByUser_Call) Run(run func(ctx context.Context, userID string)) *Store_ListWorkTasksByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ListWorkTasksByUser_Call) Return(_a0 []model.WorkTask, _a1 error) *Store_ListWorkTasksByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListWorkTasksByUser_Call) RunAndReturn(run func(context.Context, string) ([]model.WorkTask, error)) *Store_ListWorkTasksByUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkGoogleReauthRequired provides a mock function with given fields: ctx, userID
func (_m *Store) MarkGoogleReauthRequired(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkGoogleReauthRequired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_MarkGoogleReauthRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkGoogleReauthRequired'
type Store_MarkGoogleReauthRequired_Call struct {
	*mock.Call
}

// MarkGoogleReauthRequired is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) MarkGoogleReauthRequired(ctx interface{}, userID interface{}) *Store_MarkGoogleReauthRequired_Call {
	return &Store_MarkGoogleReauthRequired_Call{Call: _e.mock.On("MarkGoogleReauthRequired", ctx, userID)}
}

func (_c *Store_MarkGoogleReauthRequired_Call) Run(run func(ctx context.Context, userID string)) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_MarkGoogleReauthRequired_Call) Return(_a0 error) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_MarkGoogleReauthRequired_Call) RunAndReturn(run func(context.Context, string) error) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Return(run)
	return _c
}

// MarkZoomReauthRequired provides a mock function with given fields: ctx, userID
func (_m *Store) MarkZoomReauthRequired(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkZoomReauthRequired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_MarkZoomReauthRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkZoomReauthRequired'
type Store_MarkZoomReauthRequired_Call struct {
	*mock.Call
}

// MarkZoomReauthRequired is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) MarkZoomReauthRequired(ctx interface{}, userID interface{}) *Store_MarkZoomReauthRequired_Call {
	return &Store_MarkZoomReauthRequired_Call{Call: _e.mock.On("MarkZoomReauthRequired", ctx, userID)}
}

func (_c *Store_MarkZoomReauthRequired_Call) Run(run func(ctx context.Context, userID string)) *Store_MarkZoomReauthRequired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_MarkZoomReauthRequired_Call) Return(_a0 error) *Store_MarkZoomReauthRequired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_MarkZoomReauthRequired_Call) RunAndReturn(run func(context.Context, string) error) *Store_MarkZoomReauthRequired_Call {
	_c.Call.Return(run)
	return _c
}

// PatchWorkTask provides a mock function with given fields: ctx, taskID, userID, patch
func (_m *Store) PatchWorkTask(ctx context.Context, taskID string, userID string, patch model.WorkTaskPatch) (*model.WorkTask, error) {
	ret := _m.Called(ctx, taskID, userID, patch)

	if len(ret) == 0 {
		panic("no return value specified for PatchWorkTask")
	}

	var r0 *model.WorkTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.WorkTaskPatch) (*model.WorkTask, error)); ok {
		return rf(ctx, taskID, userID, patch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.WorkTaskPatch) *model.WorkTask); ok {
		r0 = rf(ctx, taskID, userID, patch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WorkTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.WorkTaskPatch) error); ok {
		r1 = rf(ctx, taskID, userID, patch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_PatchWorkTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchWorkTask'
type Store_PatchWorkTask_Call struct {
	*mock.Call
}

// PatchWorkTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - userID string
//   - patch model.WorkTaskPatch
func (_e *Store_Expecter) PatchWorkTask(ctx interface{}, taskID interface{}, userID interface{}, patch interface{}) *Store_PatchWorkTask_Call {
	return &Store_PatchWorkTask_Call{Call: _e.mock.On("PatchWorkTask", ctx, taskID, userID, patch)}
}

func (_c *Store_PatchWorkTask_Call) Run(run func(ctx context.Context, taskID string, userID string, patch model.WorkTaskPatch)) *Store_PatchWorkTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.WorkTaskPatch))
	})
	return _c
}

func (_c *Store_PatchWorkTask_Call) Return(_a0 *model.WorkTask, _a1 error) *Store_PatchWorkTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_PatchWorkTask_Call) RunAndReturn(run func(context.Context, string, string, model.WorkTaskPatch) (*model.WorkTask, error)) *Store_PatchWorkTask_Call {
	_c.Call.Return(run)
	return _c
}

// PruneGoogleCalendarData provides a mock function with given fields: ctx, userID, calendarIDs
func (_m *Store) PruneGoogleCalendarData(ctx context.Context, userID string, calendarIDs []string) error {
	ret := _m.Called(ctx, userID, calendarIDs)

	if len(ret) == 0 {
		panic("no return value specified for PruneGoogleCalendarData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, userID, calendarIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_PruneGoogleCalendarData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneGoogleCalendarData'
type Store_PruneGoogleCalendarData_Call struct {
	*mock.Call
}

// PruneGoogleCalendarData is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - calendarIDs []string
func (_e *Store_Expecter) PruneGoogleCalendarData(ctx interface{}, userID interface{}, calendarIDs interface{}) *Store_PruneGoogleCalendarData_Call {
	return &Store_PruneGoogleCalendarData_Call{Call: _e.mock.On("PruneGoogleCalendarData", ctx, userID, calendarIDs)}
}

func (_c *Store_PruneGoogleCalendarData_Call) Run(run func(ctx context.Context, userID string, calendarIDs []string)) *Store_PruneGoogleCalendarData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *Store_PruneGoogleCalendarData_Call) Return(_a0 error) *Store_PruneGoogleCalendarData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_PruneGoogleCalendarData_Call) RunAndReturn(run func(context.Context, string, []string) error) *Store_PruneGoogleCalendarData_Call {
	_c.Call.Return(run)
	return _c
}

// SaveGoogleOAuthState provides a mock function with given fields: ctx, userID, state
func (_m *Store) SaveGoogleOAuthState(ctx context.Context, userID string, state string) error {
	ret := _m.Called(ctx, userID, state)

	if len(ret) == 0 {
		panic("no return value specified for SaveGoogleOAuthState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveGoogleOAuthState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveGoogleOAuthState'
type Store_SaveGoogleOAuthState_Call struct {
	*mock.Call
}

// SaveGoogleOAuthState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - state string
func (_e *Store_Expecter) SaveGoogleOAuthState(ctx interface{}, userID interface{}, state interface{}) *Store_SaveGoogleOAuthState_Call {
	return &Store_SaveGoogleOAuthState_Call{Call: _e.mock.On("SaveGoogleOAuthState", ctx, userID, state)}
}

func (_c *Store_SaveGoogleOAuthState_Call) Run(run func(ctx context.Context, userID string, state string)) *Store_SaveGoogleOAuthState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_SaveGoogleOAuthState_Call) Return(_a0 error) *Store_SaveGoogleOAuthState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveGoogleOAuthState_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_SaveGoogleOAuthState_Call {
	_c.Call.Return(run)
	return _c
}

// SaveGoogleRefreshToken provides a mock function with given fields: ctx, userID, refreshToken
func (_m *Store) SaveGoogleRefreshToken(ctx context.Context, userID string, refreshToken string) error {
	ret := _m.Called(ctx, userID, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for SaveGoogleRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveGoogleRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveGoogleRefreshToken'
type Store_SaveGoogleRefreshToken_Call struct {
	*mock.Call
}

// SaveGoogleRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - refreshToken string
func (_e *Store_Expecter) SaveGoogleRefreshToken(ctx interface{}, userID interface{}, refreshToken interface{}) *Store_SaveGoogleRefreshToken_Call {
	return &Store_SaveGoogleRefreshToken_Call{Call: _e.mock.On("SaveGoogleRefreshToken", ctx, userID, refreshToken)}
}

func (_c *Store_SaveGoogleRefreshToken_Call) Run(run func(ctx context.Context, userID string, refreshToken string)) *Store_SaveGoogleRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_SaveGoogleRefreshToken_Call) Return(_a0 error) *Store_SaveGoogleRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveGoogleRefreshToken_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_SaveGoogleRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveZoomOAuthState provides a mock function with given fields: ctx, userID, state
func (_m *Store) SaveZoomOAuthState(ctx context.Context, userID string, state string) error {
	ret := _m.Called(ctx, userID, state)

	if len(ret) == 0 {
		panic("no return value specified for SaveZoomOAuthState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveZoomOAuthState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveZoomOAuthState'
type Store_SaveZoomOAuthState_Call struct {
	*mock.Call
}

// SaveZoomOAuthState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - state string
func (_e *Store_Expecter) SaveZoomOAuthState(ctx interface{}, userID interface{}, state interface{}) *Store_SaveZoomOAuthState_Call {
	return &Store_SaveZoomOAuthState_Call{Call: _e.mock.On("SaveZoomOAuthState", ctx, userID, state)}
}

func (_c *Store_SaveZoomOAuthState_Call) Run(run func(ctx context.Context, userID string, state string)) *Store_SaveZoomOAuthState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_SaveZoomOAuthState_Call) Return(_a0 error) *Store_SaveZoomOAuthState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveZoomOAuthState_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_SaveZoomOAuthState_Call {
	_c.Call.Return(run)
	return _c
}

// SaveZoomRefreshToken provides a mock function with given fields: ctx, userID, refreshToken
func (_m *Store) SaveZoomRefreshToken(ctx context.Context, userID string, refreshToken string) error {
	ret := _m.Called(ctx, userID, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for SaveZoomRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveZoomRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveZoomRefreshToken'
type Store_SaveZoomRefreshToken_Call struct {
	*mock.Call
}

// SaveZoomRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - refreshToken string
func (_e *Store_Expecter) SaveZoomRefreshToken(ctx interface{}, userID interface{}, refreshToken interface{}) *Store_SaveZoomRefreshToken_Call {
	return &Store_SaveZoomRefreshToken_Call{Call: _e.mock.On("SaveZoomRefreshToken", ctx, userID, refreshToken)}
}

func (_c *Store_SaveZoomRefreshToken_Call) Run(run func(ctx context.Context, userID string, refreshToken string)) *Store_SaveZoomRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_SaveZoomRefreshToken_Call) Return(_a0 error) *Store_SaveZoomRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveZoomRefreshToken_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_SaveZoomRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertGoogleEvents provides a mock function with given fields: ctx, userID, events
func (_m *Store) UpsertGoogleEvents(ctx context.Context, userID string, events []model.CachedCalendarEvent) error {
	ret := _m.Called(ctx, userID, events)

	if len(ret) == 0 {
		panic("no return value specified for UpsertGoogleEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.CachedCalendarEvent) error); ok {
		r0 = rf(ctx, userID, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_UpsertGoogleEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertGoogleEvents'
type Store_UpsertGoogleEvents_Call struct {
	*mock.Call
}

// UpsertGoogleEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - events []model.CachedCalendarEvent
func (_e *Store_Expecter) UpsertGoogleEvents(ctx interface{}, userID interface{}, events interface{}) *Store_UpsertGoogleEvents_Call {
	return &Store_UpsertGoogleEvents_Call{Call: _e.mock.On("UpsertGoogleEvents", ctx, userID, events)}
}

func (_c *Store_UpsertGoogleEvents_Call) Run(run func(ctx context.Context, userID string, events []model.CachedCalendarEvent)) *Store_UpsertGoogleEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]model.CachedCalendarEvent))
	})
	return _c
}

func (_c *Store_UpsertGoogleEvents_Call) Return(_a0 error) *Store_UpsertGoogleEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_UpsertGoogleEvents_Call) RunAndReturn(run func(context.Context, string, []model.CachedCalendarEvent) error) *Store_UpsertGoogleEvents_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUserSettings provides a mock function with given fields: ctx, userID, patch
func (_m *Store) UpsertUserSettings(ctx context.Context, userID string, patch repository.UserSettingsPatch) (*model.UserSettings, error) {
	ret := _m.Called(ctx, userID, patch)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserSettings")
	}

	var r0 *model.UserSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, repository.UserSettingsPatch) (*model.UserSettings, error)); ok {
		return rf(ctx, userID, patch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, repository.UserSettingsPatch) *model.UserSettings); ok {
		r0 = rf(ctx, userID, patch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, repository.UserSettingsPatch) error); ok {
		r1 = rf(ctx, userID, patch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_UpsertUserSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserSettings'
type Store_UpsertUserSettings_Call struct {
	*mock.Call
}

// UpsertUserSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - patch repository.UserSettingsPatch
func (_e *Store_Expecter) UpsertUserSettings(ctx interface{}, userID interface{}, patch interface{}) *Store_UpsertUserSettings_Call {
	return &Store_UpsertUserSettings_Call{Call: _e.mock.On("UpsertUserSettings", ctx, userID, patch)}
}

func (_c *Store_UpsertUserSettings_Call) Run(run func(ctx context.Context, userID string, patch repository.UserSettingsPatch)) *Store_UpsertUserSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(repository.UserSettingsPatch))
	})
	return _c
}

func (_c *Store_UpsertUserSettings_Call) Return(_a0 *model.UserSettings, _a1 error) *Store_UpsertUserSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_UpsertUserSettings_Call) RunAndReturn(run func(context.Context, string, repository.UserSettingsPatch) (*model.UserSettings, error)) *Store_UpsertUserSettings_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *Store) WithTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type Store_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *Store_Expecter) WithTx(ctx interface{}, fn interface{}) *Store_WithTx_Call {
	return &Store_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *Store_WithTx_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *Store_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *Store_WithTx_Call) Return(_a0 error) *Store_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_WithTx_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *Store_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
