// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenOpener is an autogenerated mock type for the TokenOpener type
type TokenOpener struct {
	mock.Mock
}

type TokenOpener_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenOpener) EXPECT() *TokenOpener_Expecter {
	return &TokenOpener_Expecter{mock: &_m.Mock}
}

// Open provides a mock function with given fields: value
func (_m *TokenOpener) Open(value string) (string, error) {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(value)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenOpener_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type TokenOpener_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - value string
func (_e *TokenOpener_Expecter) Open(value interface{}) *TokenOpener_Open_Call {
	return &TokenOpener_Open_Call{Call: _e.mock.On("Open", value)}
}

func (_c *TokenOpener_Open_Call) Run(run func(value string)) *TokenOpener_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenOpener_Open_Call) Return(_a0 string, _a1 error) *TokenOpener_Open_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenOpener_Open_Call) RunAndReturn(run func(string) (string, error)) *TokenOpener_Open_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenOpener creates a new instance of TokenOpener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenOpener(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenOpener {
	mock := &TokenOpener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
