// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/sandbox/internal/sandbox/model"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// ClaimQueuedRuns provides a mock function with given fields: ctx, limit
func (_m *Store) ClaimQueuedRuns(ctx context.Context, limit int) ([]model.CodeRun, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ClaimQueuedRuns")
	}

	var r0 []model.CodeRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.CodeRun, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.CodeRun); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CodeRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ClaimQueuedRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimQueuedRuns'
type Store_ClaimQueuedRuns_Call struct {
	*mock.Call
}

// ClaimQueuedRuns is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *Store_Expecter) ClaimQueuedRuns(ctx interface{}, limit interface{}) *Store_ClaimQueuedRuns_Call {
	return &Store_ClaimQueuedRuns_Call{Call: _e.mock.On("ClaimQueuedRuns", ctx, limit)}
}

func (_c *Store_ClaimQueuedRuns_Call) Run(run func(ctx context.Context, limit int)) *Store_ClaimQueuedRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Store_ClaimQueuedRuns_Call) Return(_a0 []model.CodeRun, _a1 error) *Store_ClaimQueuedRuns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ClaimQueuedRuns_Call) RunAndReturn(run func(context.Context, int) ([]model.CodeRun, error)) *Store_ClaimQueuedRuns_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, run
func (_m *Store) Create(ctx context.Context, run *model.CodeRun) error {
	ret := _m.Called(ctx, run)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CodeRun) error); ok {
		r0 = rf(ctx, run)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Store_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - run *model.CodeRun
func (_e *Store_Expecter) Create(ctx interface{}, run interface{}) *Store_Create_Call {
	return &Store_Create_Call{Call: _e.mock.On("Create", ctx, run)}
}

func (_c *Store_Create_Call) Run(run func(ctx context.Context, run *model.CodeRun)) *Store_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.CodeRun))
	})
	return _c
}

func (_c *Store_Create_Call) Return(_a0 error) *Store_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_Create_Call) RunAndReturn(run func(context.Context, *model.CodeRun) error) *Store_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Store) GetByID(ctx context.Context, id string) (*model.CodeRun, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.CodeRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.CodeRun, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.CodeRun); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CodeRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type Store_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Store_Expecter) GetByID(ctx interface{}, id interface{}) *Store_GetByID_Call {
	return &Store_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *Store_GetByID_Call) Run(run func(ctx context.Context, id string)) *Store_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetByID_Call) Return(_a0 *model.CodeRun, _a1 error) *Store_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetByID_Call) RunAndReturn(run func(context.Context, string) (*model.CodeRun, error)) *Store_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, run
func (_m *Store) Update(ctx context.Context, run *model.CodeRun) error {
	ret := _m.Called(ctx, run)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CodeRun) error); ok {
		r0 = rf(ctx, run)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Store_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - run *model.CodeRun
func (_e *Store_Expecter) Update(ctx interface{}, run interface{}) *Store_Update_Call {
	return &Store_Update_Call{Call: _e.mock.On("Update", ctx, run)}
}

func (_c *Store_Update_Call) Run(run func(ctx context.Context, run *model.CodeRun)) *Store_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.CodeRun))
	})
	return _c
}

func (_c *Store_Update_Call) Return(_a0 error) *Store_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_Update_Call) RunAndReturn(run func(context.Context, *model.CodeRun) error) *Store_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
