// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/rooms/internal/room/model"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// CreateRoom provides a mock function with given fields: ctx, room, owner, initialSceneJSON
func (_m *Store) CreateRoom(ctx context.Context, room model.Room, owner model.Participant, initialSceneJSON string) (model.Room, error) {
	ret := _m.Called(ctx, room, owner, initialSceneJSON)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Room, model.Participant, string) (model.Room, error)); ok {
		return rf(ctx, room, owner, initialSceneJSON)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Room, model.Participant, string) model.Room); ok {
		r0 = rf(ctx, room, owner, initialSceneJSON)
	} else {
		r0 = ret.Get(0).(model.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Room, model.Participant, string) error); ok {
		r1 = rf(ctx, room, owner, initialSceneJSON)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type Store_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - room model.Room
//   - owner model.Participant
//   - initialSceneJSON string
func (_e *Store_Expecter) CreateRoom(ctx interface{}, room interface{}, owner interface{}, initialSceneJSON interface{}) *Store_CreateRoom_Call {
	return &Store_CreateRoom_Call{Call: _e.mock.On("CreateRoom", ctx, room, owner, initialSceneJSON)}
}

func (_c *Store_CreateRoom_Call) Run(run func(ctx context.Context, room model.Room, owner model.Participant, initialSceneJSON string)) *Store_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Room), args[2].(model.Participant), args[3].(string))
	})
	return _c
}

func (_c *Store_CreateRoom_Call) Return(_a0 model.Room, _a1 error) *Store_CreateRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CreateRoom_Call) RunAndReturn(run func(context.Context, model.Room, model.Participant, string) (model.Room, error)) *Store_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRoom provides a mock function with given fields: ctx, id, ownerID
func (_m *Store) DeleteRoom(ctx context.Context, id uuid.UUID, ownerID uuid.UUID) error {
	ret := _m.Called(ctx, id, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, ownerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DeleteRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRoom'
type Store_DeleteRoom_Call struct {
	*mock.Call
}

// DeleteRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - ownerID uuid.UUID
func (_e *Store_Expecter) DeleteRoom(ctx interface{}, id interface{}, ownerID interface{}) *Store_DeleteRoom_Call {
	return &Store_DeleteRoom_Call{Call: _e.mock.On("DeleteRoom", ctx, id, ownerID)}
}

func (_c *Store_DeleteRoom_Call) Run(run func(ctx context.Context, id uuid.UUID, ownerID uuid.UUID)) *Store_DeleteRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Store_DeleteRoom_Call) Return(_a0 error) *Store_DeleteRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DeleteRoom_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *Store_DeleteRoom_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
