// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/tracker/internal/tracker/model"
	mock "github.com/stretchr/testify/mock"
)

// Google is an autogenerated mock type for the Google type
type Google struct {
	mock.Mock
}

type Google_Expecter struct {
	mock *mock.Mock
}

func (_m *Google) EXPECT() *Google_Expecter {
	return &Google_Expecter{mock: &_m.Mock}
}

// Configured provides a mock function with no fields
func (_m *Google) Configured() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Configured")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Google_Configured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configured'
type Google_Configured_Call struct {
	*mock.Call
}

// Configured is a helper method to define mock.On call
func (_e *Google_Expecter) Configured() *Google_Configured_Call {
	return &Google_Configured_Call{Call: _e.mock.On("Configured")}
}

func (_c *Google_Configured_Call) Run(run func()) *Google_Configured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Google_Configured_Call) Return(_a0 bool) *Google_Configured_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Google_Configured_Call) RunAndReturn(run func() bool) *Google_Configured_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEventWithMeet provides a mock function with given fields: ctx, refreshToken, calendarID, in
func (_m *Google) CreateEventWithMeet(ctx context.Context, refreshToken string, calendarID string, in model.CalendarEventInput) (model.CalendarEventWithMeet, error) {
	ret := _m.Called(ctx, refreshToken, calendarID, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateEventWithMeet")
	}

	var r0 model.CalendarEventWithMeet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.CalendarEventInput) (model.CalendarEventWithMeet, error)); ok {
		return rf(ctx, refreshToken, calendarID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.CalendarEventInput) model.CalendarEventWithMeet); ok {
		r0 = rf(ctx, refreshToken, calendarID, in)
	} else {
		r0 = ret.Get(0).(model.CalendarEventWithMeet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.CalendarEventInput) error); ok {
		r1 = rf(ctx, refreshToken, calendarID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Google_CreateEventWithMeet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEventWithMeet'
type Google_CreateEventWithMeet_Call struct {
	*mock.Call
}

// CreateEventWithMeet is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - calendarID string
//   - in model.CalendarEventInput
func (_e *Google_Expecter) CreateEventWithMeet(ctx interface{}, refreshToken interface{}, calendarID interface{}, in interface{}) *Google_CreateEventWithMeet_Call {
	return &Google_CreateEventWithMeet_Call{Call: _e.mock.On("CreateEventWithMeet", ctx, refreshToken, calendarID, in)}
}

func (_c *Google_CreateEventWithMeet_Call) Run(run func(ctx context.Context, refreshToken string, calendarID string, in model.CalendarEventInput)) *Google_CreateEventWithMeet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.CalendarEventInput))
	})
	return _c
}

func (_c *Google_CreateEventWithMeet_Call) Return(_a0 model.CalendarEventWithMeet, _a1 error) *Google_CreateEventWithMeet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Google_CreateEventWithMeet_Call) RunAndReturn(run func(context.Context, string, string, model.CalendarEventInput) (model.CalendarEventWithMeet, error)) *Google_CreateEventWithMeet_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEvent provides a mock function with given fields: ctx, refreshToken, calendarID, eventID
func (_m *Google) DeleteEvent(ctx context.Context, refreshToken string, calendarID string, eventID string) error {
	ret := _m.Called(ctx, refreshToken, calendarID, eventID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, refreshToken, calendarID, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Google_DeleteEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEvent'
type Google_DeleteEvent_Call struct {
	*mock.Call
}

// DeleteEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - calendarID string
//   - eventID string
func (_e *Google_Expecter) DeleteEvent(ctx interface{}, refreshToken interface{}, calendarID interface{}, eventID interface{}) *Google_DeleteEvent_Call {
	return &Google_DeleteEvent_Call{Call: _e.mock.On("DeleteEvent", ctx, refreshToken, calendarID, eventID)}
}

func (_c *Google_DeleteEvent_Call) Run(run func(ctx context.Context, refreshToken string, calendarID string, eventID string)) *Google_DeleteEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Google_DeleteEvent_Call) Return(_a0 error) *Google_DeleteEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Google_DeleteEvent_Call) RunAndReturn(run func(context.Context, string, string, string) error) *Google_DeleteEvent_Call {
	_c.Call.Return(run)
	return _c
}

// PatchEventWithMeet provides a mock function with given fields: ctx, refreshToken, calendarID, eventID, in
func (_m *Google) PatchEventWithMeet(ctx context.Context, refreshToken string, calendarID string, eventID string, in model.CalendarEventInput) (model.CalendarEventWithMeet, error) {
	ret := _m.Called(ctx, refreshToken, calendarID, eventID, in)

	if len(ret) == 0 {
		panic("no return value specified for PatchEventWithMeet")
	}

	var r0 model.CalendarEventWithMeet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, model.CalendarEventInput) (model.CalendarEventWithMeet, error)); ok {
		return rf(ctx, refreshToken, calendarID, eventID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, model.CalendarEventInput) model.CalendarEventWithMeet); ok {
		r0 = rf(ctx, refreshToken, calendarID, eventID, in)
	} else {
		r0 = ret.Get(0).(model.CalendarEventWithMeet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, model.CalendarEventInput) error); ok {
		r1 = rf(ctx, refreshToken, calendarID, eventID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Google_PatchEventWithMeet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchEventWithMeet'
type Google_PatchEventWithMeet_Call struct {
	*mock.Call
}

// PatchEventWithMeet is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - calendarID string
//   - eventID string
//   - in model.CalendarEventInput
func (_e *Google_Expecter) PatchEventWithMeet(ctx interface{}, refreshToken interface{}, calendarID interface{}, eventID interface{}, in interface{}) *Google_PatchEventWithMeet_Call {
	return &Google_PatchEventWithMeet_Call{Call: _e.mock.On("PatchEventWithMeet", ctx, refreshToken, calendarID, eventID, in)}
}

func (_c *Google_PatchEventWithMeet_Call) Run(run func(ctx context.Context, refreshToken string, calendarID string, eventID string, in model.CalendarEventInput)) *Google_PatchEventWithMeet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(model.CalendarEventInput))
	})
	return _c
}

func (_c *Google_PatchEventWithMeet_Call) Return(_a0 model.CalendarEventWithMeet, _a1 error) *Google_PatchEventWithMeet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Google_PatchEventWithMeet_Call) RunAndReturn(run func(context.Context, string, string, string, model.CalendarEventInput) (model.CalendarEventWithMeet, error)) *Google_PatchEventWithMeet_Call {
	_c.Call.Return(run)
	return _c
}

// NewGoogle creates a new instance of Google. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogle(t interface {
	mock.TestingT
	Cleanup(func())
}) *Google {
	mock := &Google{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
