// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/rooms/internal/room/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// AddParticipant provides a mock function with given fields: ctx, p
func (_m *Store) AddParticipant(ctx context.Context, p model.Participant) (model.Participant, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for AddParticipant")
	}

	var r0 model.Participant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Participant) (model.Participant, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Participant) model.Participant); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(model.Participant)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Participant) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_AddParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddParticipant'
type Store_AddParticipant_Call struct {
	*mock.Call
}

// AddParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - p model.Participant
func (_e *Store_Expecter) AddParticipant(ctx interface{}, p interface{}) *Store_AddParticipant_Call {
	return &Store_AddParticipant_Call{Call: _e.mock.On("AddParticipant", ctx, p)}
}

func (_c *Store_AddParticipant_Call) Run(run func(ctx context.Context, p model.Participant)) *Store_AddParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Participant))
	})
	return _c
}

func (_c *Store_AddParticipant_Call) Return(_a0 model.Participant, _a1 error) *Store_AddParticipant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_AddParticipant_Call) RunAndReturn(run func(context.Context, model.Participant) (model.Participant, error)) *Store_AddParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRoom provides a mock function with given fields: ctx, room, owner, initialSceneJSON
func (_m *Store) CreateRoom(ctx context.Context, room model.Room, owner model.Participant, initialSceneJSON string) (model.Room, error) {
	ret := _m.Called(ctx, room, owner, initialSceneJSON)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Room, model.Participant, string) (model.Room, error)); ok {
		return rf(ctx, room, owner, initialSceneJSON)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Room, model.Participant, string) model.Room); ok {
		r0 = rf(ctx, room, owner, initialSceneJSON)
	} else {
		r0 = ret.Get(0).(model.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Room, model.Participant, string) error); ok {
		r1 = rf(ctx, room, owner, initialSceneJSON)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type Store_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - room model.Room
//   - owner model.Participant
//   - initialSceneJSON string
func (_e *Store_Expecter) CreateRoom(ctx interface{}, room interface{}, owner interface{}, initialSceneJSON interface{}) *Store_CreateRoom_Call {
	return &Store_CreateRoom_Call{Call: _e.mock.On("CreateRoom", ctx, room, owner, initialSceneJSON)}
}

func (_c *Store_CreateRoom_Call) Run(run func(ctx context.Context, room model.Room, owner model.Participant, initialSceneJSON string)) *Store_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Room), args[2].(model.Participant), args[3].(string))
	})
	return _c
}

func (_c *Store_CreateRoom_Call) Return(_a0 model.Room, _a1 error) *Store_CreateRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CreateRoom_Call) RunAndReturn(run func(context.Context, model.Room, model.Participant, string) (model.Room, error)) *Store_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function with given fields: ctx
func (_m *Store) DeleteExpired(ctx context.Context) ([]uuid.UUID, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]uuid.UUID, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []uuid.UUID); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type Store_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Store_Expecter) DeleteExpired(ctx interface{}) *Store_DeleteExpired_Call {
	return &Store_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx)}
}

func (_c *Store_DeleteExpired_Call) Run(run func(ctx context.Context)) *Store_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Store_DeleteExpired_Call) Return(_a0 []uuid.UUID, _a1 error) *Store_DeleteExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_DeleteExpired_Call) RunAndReturn(run func(context.Context) ([]uuid.UUID, error)) *Store_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteParticipant provides a mock function with given fields: ctx, roomID, userID
func (_m *Store) DeleteParticipant(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteParticipant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DeleteParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteParticipant'
type Store_DeleteParticipant_Call struct {
	*mock.Call
}

// DeleteParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *Store_Expecter) DeleteParticipant(ctx interface{}, roomID interface{}, userID interface{}) *Store_DeleteParticipant_Call {
	return &Store_DeleteParticipant_Call{Call: _e.mock.On("DeleteParticipant", ctx, roomID, userID)}
}

func (_c *Store_DeleteParticipant_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *Store_DeleteParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Store_DeleteParticipant_Call) Return(_a0 error) *Store_DeleteParticipant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DeleteParticipant_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *Store_DeleteParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRoom provides a mock function with given fields: ctx, id, ownerID
func (_m *Store) DeleteRoom(ctx context.Context, id uuid.UUID, ownerID uuid.UUID) error {
	ret := _m.Called(ctx, id, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, ownerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DeleteRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRoom'
type Store_DeleteRoom_Call struct {
	*mock.Call
}

// DeleteRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - ownerID uuid.UUID
func (_e *Store_Expecter) DeleteRoom(ctx interface{}, id interface{}, ownerID interface{}) *Store_DeleteRoom_Call {
	return &Store_DeleteRoom_Call{Call: _e.mock.On("DeleteRoom", ctx, id, ownerID)}
}

func (_c *Store_DeleteRoom_Call) Run(run func(ctx context.Context, id uuid.UUID, ownerID uuid.UUID)) *Store_DeleteRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Store_DeleteRoom_Call) Return(_a0 error) *Store_DeleteRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DeleteRoom_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *Store_DeleteRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetInitialScene provides a mock function with given fields: ctx, roomID
func (_m *Store) GetInitialScene(ctx context.Context, roomID uuid.UUID) (string, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetInitialScene")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, roomID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetInitialScene_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInitialScene'
type Store_GetInitialScene_Call struct {
	*mock.Call
}

// GetInitialScene is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
func (_e *Store_Expecter) GetInitialScene(ctx interface{}, roomID interface{}) *Store_GetInitialScene_Call {
	return &Store_GetInitialScene_Call{Call: _e.mock.On("GetInitialScene", ctx, roomID)}
}

func (_c *Store_GetInitialScene_Call) Run(run func(ctx context.Context, roomID uuid.UUID)) *Store_GetInitialScene_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Store_GetInitialScene_Call) Return(_a0 string, _a1 error) *Store_GetInitialScene_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetInitialScene_Call) RunAndReturn(run func(context.Context, uuid.UUID) (string, error)) *Store_GetInitialScene_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublishedBoardBySlug provides a mock function with given fields: ctx, slug
func (_m *Store) GetPublishedBoardBySlug(ctx context.Context, slug string) (model.PublishedBoard, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishedBoardBySlug")
	}

	var r0 model.PublishedBoard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.PublishedBoard, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.PublishedBoard); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Get(0).(model.PublishedBoard)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetPublishedBoardBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublishedBoardBySlug'
type Store_GetPublishedBoardBySlug_Call struct {
	*mock.Call
}

// GetPublishedBoardBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *Store_Expecter) GetPublishedBoardBySlug(ctx interface{}, slug interface{}) *Store_GetPublishedBoardBySlug_Call {
	return &Store_GetPublishedBoardBySlug_Call{Call: _e.mock.On("GetPublishedBoardBySlug", ctx, slug)}
}

func (_c *Store_GetPublishedBoardBySlug_Call) Run(run func(ctx context.Context, slug string)) *Store_GetPublishedBoardBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetPublishedBoardBySlug_Call) Return(_a0 model.PublishedBoard, _a1 error) *Store_GetPublishedBoardBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetPublishedBoardBySlug_Call) RunAndReturn(run func(context.Context, string) (model.PublishedBoard, error)) *Store_GetPublishedBoardBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetRole provides a mock function with given fields: ctx, roomID, userID
func (_m *Store) GetRole(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (model.Role, error) {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (model.Role, error)); ok {
		return rf(ctx, roomID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) model.Role); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Get(0).(model.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type Store_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *Store_Expecter) GetRole(ctx interface{}, roomID interface{}, userID interface{}) *Store_GetRole_Call {
	return &Store_GetRole_Call{Call: _e.mock.On("GetRole", ctx, roomID, userID)}
}

func (_c *Store_GetRole_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *Store_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Store_GetRole_Call) Return(_a0 model.Role, _a1 error) *Store_GetRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (model.Role, error)) *Store_GetRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoom provides a mock function with given fields: ctx, id
func (_m *Store) GetRoom(ctx context.Context, id uuid.UUID) (model.Room, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoom")
	}

	var r0 model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Room, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Room); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoom'
type Store_GetRoom_Call struct {
	*mock.Call
}

// GetRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Store_Expecter) GetRoom(ctx interface{}, id interface{}) *Store_GetRoom_Call {
	return &Store_GetRoom_Call{Call: _e.mock.On("GetRoom", ctx, id)}
}

func (_c *Store_GetRoom_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Store_GetRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Store_GetRoom_Call) Return(_a0 model.Room, _a1 error) *Store_GetRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetRoom_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Room, error)) *Store_GetRoom_Call {
	_c.Call.Return(run)
	return _c
}

// InsertPublishedBoard provides a mock function with given fields: ctx, userID, slug, title, sceneJSON
func (_m *Store) InsertPublishedBoard(ctx context.Context, userID uuid.UUID, slug string, title string, sceneJSON string) (model.PublishedBoard, error) {
	ret := _m.Called(ctx, userID, slug, title, sceneJSON)

	if len(ret) == 0 {
		panic("no return value specified for InsertPublishedBoard")
	}

	var r0 model.PublishedBoard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) (model.PublishedBoard, error)); ok {
		return rf(ctx, userID, slug, title, sceneJSON)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) model.PublishedBoard); ok {
		r0 = rf(ctx, userID, slug, title, sceneJSON)
	} else {
		r0 = ret.Get(0).(model.PublishedBoard)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string) error); ok {
		r1 = rf(ctx, userID, slug, title, sceneJSON)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_InsertPublishedBoard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertPublishedBoard'
type Store_InsertPublishedBoard_Call struct {
	*mock.Call
}

// InsertPublishedBoard is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - slug string
//   - title string
//   - sceneJSON string
func (_e *Store_Expecter) InsertPublishedBoard(ctx interface{}, userID interface{}, slug interface{}, title interface{}, sceneJSON interface{}) *Store_InsertPublishedBoard_Call {
	return &Store_InsertPublishedBoard_Call{Call: _e.mock.On("InsertPublishedBoard", ctx, userID, slug, title, sceneJSON)}
}

func (_c *Store_InsertPublishedBoard_Call) Run(run func(ctx context.Context, userID uuid.UUID, slug string, title string, sceneJSON string)) *Store_InsertPublishedBoard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *Store_InsertPublishedBoard_Call) Return(_a0 model.PublishedBoard, _a1 error) *Store_InsertPublishedBoard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_InsertPublishedBoard_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string) (model.PublishedBoard, error)) *Store_InsertPublishedBoard_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
