// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/tracker/internal/tracker/model"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// GetUserSettings provides a mock function with given fields: ctx, userID
func (_m *Store) GetUserSettings(ctx context.Context, userID string) (*model.UserSettings, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSettings")
	}

	var r0 *model.UserSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserSettings, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserSettings); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetUserSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSettings'
type Store_GetUserSettings_Call struct {
	*mock.Call
}

// GetUserSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) GetUserSettings(ctx interface{}, userID interface{}) *Store_GetUserSettings_Call {
	return &Store_GetUserSettings_Call{Call: _e.mock.On("GetUserSettings", ctx, userID)}
}

func (_c *Store_GetUserSettings_Call) Run(run func(ctx context.Context, userID string)) *Store_GetUserSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetUserSettings_Call) Return(_a0 *model.UserSettings, _a1 error) *Store_GetUserSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetUserSettings_Call) RunAndReturn(run func(context.Context, string) (*model.UserSettings, error)) *Store_GetUserSettings_Call {
	_c.Call.Return(run)
	return _c
}

// MarkGoogleReauthRequired provides a mock function with given fields: ctx, userID
func (_m *Store) MarkGoogleReauthRequired(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkGoogleReauthRequired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_MarkGoogleReauthRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkGoogleReauthRequired'
type Store_MarkGoogleReauthRequired_Call struct {
	*mock.Call
}

// MarkGoogleReauthRequired is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) MarkGoogleReauthRequired(ctx interface{}, userID interface{}) *Store_MarkGoogleReauthRequired_Call {
	return &Store_MarkGoogleReauthRequired_Call{Call: _e.mock.On("MarkGoogleReauthRequired", ctx, userID)}
}

func (_c *Store_MarkGoogleReauthRequired_Call) Run(run func(ctx context.Context, userID string)) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_MarkGoogleReauthRequired_Call) Return(_a0 error) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_MarkGoogleReauthRequired_Call) RunAndReturn(run func(context.Context, string) error) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertGoogleEvents provides a mock function with given fields: ctx, userID, events
func (_m *Store) UpsertGoogleEvents(ctx context.Context, userID string, events []model.CachedCalendarEvent) error {
	ret := _m.Called(ctx, userID, events)

	if len(ret) == 0 {
		panic("no return value specified for UpsertGoogleEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.CachedCalendarEvent) error); ok {
		r0 = rf(ctx, userID, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_UpsertGoogleEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertGoogleEvents'
type Store_UpsertGoogleEvents_Call struct {
	*mock.Call
}

// UpsertGoogleEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - events []model.CachedCalendarEvent
func (_e *Store_Expecter) UpsertGoogleEvents(ctx interface{}, userID interface{}, events interface{}) *Store_UpsertGoogleEvents_Call {
	return &Store_UpsertGoogleEvents_Call{Call: _e.mock.On("UpsertGoogleEvents", ctx, userID, events)}
}

func (_c *Store_UpsertGoogleEvents_Call) Run(run func(ctx context.Context, userID string, events []model.CachedCalendarEvent)) *Store_UpsertGoogleEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]model.CachedCalendarEvent))
	})
	return _c
}

func (_c *Store_UpsertGoogleEvents_Call) Return(_a0 error) *Store_UpsertGoogleEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_UpsertGoogleEvents_Call) RunAndReturn(run func(context.Context, string, []model.CachedCalendarEvent) error) *Store_UpsertGoogleEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
