// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/notes/internal/notes/model"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// CreateNote provides a mock function with given fields: ctx, userID, title, body, links
func (_m *Store) CreateNote(ctx context.Context, userID string, title string, body string, links []model.WikiLinkRef) (*model.Note, error) {
	ret := _m.Called(ctx, userID, title, body, links)

	if len(ret) == 0 {
		panic("no return value specified for CreateNote")
	}

	var r0 *model.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []model.WikiLinkRef) (*model.Note, error)); ok {
		return rf(ctx, userID, title, body, links)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []model.WikiLinkRef) *model.Note); ok {
		r0 = rf(ctx, userID, title, body, links)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, []model.WikiLinkRef) error); ok {
		r1 = rf(ctx, userID, title, body, links)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CreateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNote'
type Store_CreateNote_Call struct {
	*mock.Call
}

// CreateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - title string
//   - body string
//   - links []model.WikiLinkRef
func (_e *Store_Expecter) CreateNote(ctx interface{}, userID interface{}, title interface{}, body interface{}, links interface{}) *Store_CreateNote_Call {
	return &Store_CreateNote_Call{Call: _e.mock.On("CreateNote", ctx, userID, title, body, links)}
}

func (_c *Store_CreateNote_Call) Run(run func(ctx context.Context, userID string, title string, body string, links []model.WikiLinkRef)) *Store_CreateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]model.WikiLinkRef))
	})
	return _c
}

func (_c *Store_CreateNote_Call) Return(_a0 *model.Note, _a1 error) *Store_CreateNote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CreateNote_Call) RunAndReturn(run func(context.Context, string, string, string, []model.WikiLinkRef) (*model.Note, error)) *Store_CreateNote_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNote provides a mock function with given fields: ctx, userID, id
func (_m *Store) DeleteNote(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DeleteNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNote'
type Store_DeleteNote_Call struct {
	*mock.Call
}

// DeleteNote is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *Store_Expecter) DeleteNote(ctx interface{}, userID interface{}, id interface{}) *Store_DeleteNote_Call {
	return &Store_DeleteNote_Call{Call: _e.mock.On("DeleteNote", ctx, userID, id)}
}

func (_c *Store_DeleteNote_Call) Run(run func(ctx context.Context, userID string, id string)) *Store_DeleteNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_DeleteNote_Call) Return(_a0 error) *Store_DeleteNote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DeleteNote_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_DeleteNote_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNoteAttachment provides a mock function with given fields: ctx, userID, noteID, id
func (_m *Store) DeleteNoteAttachment(ctx context.Context, userID string, noteID string, id string) error {
	ret := _m.Called(ctx, userID, noteID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNoteAttachment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, noteID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DeleteNoteAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNoteAttachment'
type Store_DeleteNoteAttachment_Call struct {
	*mock.Call
}

// DeleteNoteAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - noteID string
//   - id string
func (_e *Store_Expecter) DeleteNoteAttachment(ctx interface{}, userID interface{}, noteID interface{}, id interface{}) *Store_DeleteNoteAttachment_Call {
	return &Store_DeleteNoteAttachment_Call{Call: _e.mock.On("DeleteNoteAttachment", ctx, userID, noteID, id)}
}

func (_c *Store_DeleteNoteAttachment_Call) Run(run func(ctx context.Context, userID string, noteID string, id string)) *Store_DeleteNoteAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Store_DeleteNoteAttachment_Call) Return(_a0 error) *Store_DeleteNoteAttachment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DeleteNoteAttachment_Call) RunAndReturn(run func(context.Context, string, string, string) error) *Store_DeleteNoteAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptNote provides a mock function with given fields: ctx, userID, noteID, ciphertext
func (_m *Store) EncryptNote(ctx context.Context, userID string, noteID string, ciphertext string) error {
	ret := _m.Called(ctx, userID, noteID, ciphertext)

	if len(ret) == 0 {
		panic("no return value specified for EncryptNote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, noteID, ciphertext)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_EncryptNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptNote'
type Store_EncryptNote_Call struct {
	*mock.Call
}

// EncryptNote is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - noteID string
//   - ciphertext string
func (_e *Store_Expecter) EncryptNote(ctx interface{}, userID interface{}, noteID interface{}, ciphertext interface{}) *Store_EncryptNote_Call {
	return &Store_EncryptNote_Call{Call: _e.mock.On("EncryptNote", ctx, userID, noteID, ciphertext)}
}

func (_c *Store_EncryptNote_Call) Run(run func(ctx context.Context, userID string, noteID string, ciphertext string)) *Store_EncryptNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Store_EncryptNote_Call) Return(_a0 error) *Store_EncryptNote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_EncryptNote_Call) RunAndReturn(run func(context.Context, string, string, string) error) *Store_EncryptNote_Call {
	_c.Call.Return(run)
	return _c
}

// GetNote provides a mock function with given fields: ctx, userID, id
func (_m *Store) GetNote(ctx context.Context, userID string, id string) (*model.Note, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNote")
	}

	var r0 *model.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Note, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Note); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNote'
type Store_GetNote_Call struct {
	*mock.Call
}

// GetNote is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *Store_Expecter) GetNote(ctx interface{}, userID interface{}, id interface{}) *Store_GetNote_Call {
	return &Store_GetNote_Call{Call: _e.mock.On("GetNote", ctx, userID, id)}
}

func (_c *Store_GetNote_Call) Run(run func(ctx context.Context, userID string, id string)) *Store_GetNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_GetNote_Call) Return(_a0 *model.Note, _a1 error) *Store_GetNote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetNote_Call) RunAndReturn(run func(context.Context, string, string) (*model.Note, error)) *Store_GetNote_Call {
	_c.Call.Return(run)
	return _c
}

// GetNoteAttachment provides a mock function with given fields: ctx, userID, noteID, id
func (_m *Store) GetNoteAttachment(ctx context.Context, userID string, noteID string, id string) (*model.NoteAttachment, error) {
	ret := _m.Called(ctx, userID, noteID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNoteAttachment")
	}

	var r0 *model.NoteAttachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.NoteAttachment, error)); ok {
		return rf(ctx, userID, noteID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.NoteAttachment); ok {
		r0 = rf(ctx, userID, noteID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NoteAttachment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, noteID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetNoteAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNoteAttachment'
type Store_GetNoteAttachment_Call struct {
	*mock.Call
}

// GetNoteAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - noteID string
//   - id string
func (_e *Store_Expecter) GetNoteAttachment(ctx interface{}, userID interface{}, noteID interface{}, id interface{}) *Store_GetNoteAttachment_Call {
	return &Store_GetNoteAttachment_Call{Call: _e.mock.On("GetNoteAttachment", ctx, userID, noteID, id)}
}

func (_c *Store_GetNoteAttachment_Call) Run(run func(ctx context.Context, userID string, noteID string, id string)) *Store_GetNoteAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Store_GetNoteAttachment_Call) Return(_a0 *model.NoteAttachment, _a1 error) *Store_GetNoteAttachment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetNoteAttachment_Call) RunAndReturn(run func(context.Context, string, string, string) (*model.NoteAttachment, error)) *Store_GetNoteAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublishStatus provides a mock function with given fields: ctx, userID, noteID, publicBaseURL
func (_m *Store) GetPublishStatus(ctx context.Context, userID string, noteID string, publicBaseURL string) (*model.PublishStatus, error) {
	ret := _m.Called(ctx, userID, noteID, publicBaseURL)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishStatus")
	}

	var r0 *model.PublishStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.PublishStatus, error)); ok {
		return rf(ctx, userID, noteID, publicBaseURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.PublishStatus); ok {
		r0 = rf(ctx, userID, noteID, publicBaseURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PublishStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, noteID, publicBaseURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetPublishStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublishStatus'
type Store_GetPublishStatus_Call struct {
	*mock.Call
}

// GetPublishStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - noteID string
//   - publicBaseURL string
func (_e *Store_Expecter) GetPublishStatus(ctx interface{}, userID interface{}, noteID interface{}, publicBaseURL interface{}) *Store_GetPublishStatus_Call {
	return &Store_GetPublishStatus_Call{Call: _e.mock.On("GetPublishStatus", ctx, userID, noteID, publicBaseURL)}
}

func (_c *Store_GetPublishStatus_Call) Run(run func(ctx context.Context, userID string, noteID string, publicBaseURL string)) *Store_GetPublishStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Store_GetPublishStatus_Call) Return(_a0 *model.PublishStatus, _a1 error) *Store_GetPublishStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetPublishStatus_Call) RunAndReturn(run func(context.Context, string, string, string) (*model.PublishStatus, error)) *Store_GetPublishStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublishedNoteAsset provides a mock function with given fields: ctx, slug, assetID
func (_m *Store) GetPublishedNoteAsset(ctx context.Context, slug string, assetID string) (*model.PublishedNoteAsset, error) {
	ret := _m.Called(ctx, slug, assetID)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishedNoteAsset")
	}

	var r0 *model.PublishedNoteAsset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.PublishedNoteAsset, error)); ok {
		return rf(ctx, slug, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.PublishedNoteAsset); ok {
		r0 = rf(ctx, slug, assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PublishedNoteAsset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, slug, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetPublishedNoteAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublishedNoteAsset'
type Store_GetPublishedNoteAsset_Call struct {
	*mock.Call
}

// GetPublishedNoteAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - assetID string
func (_e *Store_Expecter) GetPublishedNoteAsset(ctx interface{}, slug interface{}, assetID interface{}) *Store_GetPublishedNoteAsset_Call {
	return &Store_GetPublishedNoteAsset_Call{Call: _e.mock.On("GetPublishedNoteAsset", ctx, slug, assetID)}
}

func (_c *Store_GetPublishedNoteAsset_Call) Run(run func(ctx context.Context, slug string, assetID string)) *Store_GetPublishedNoteAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_GetPublishedNoteAsset_Call) Return(_a0 *model.PublishedNoteAsset, _a1 error) *Store_GetPublishedNoteAsset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetPublishedNoteAsset_Call) RunAndReturn(run func(context.Context, string, string) (*model.PublishedNoteAsset, error)) *Store_GetPublishedNoteAsset_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublishedNoteBySlug provides a mock function with given fields: ctx, slug
func (_m *Store) GetPublishedNoteBySlug(ctx context.Context, slug string) (*model.PublishedNote, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishedNoteBySlug")
	}

	var r0 *model.PublishedNote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.PublishedNote, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.PublishedNote); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PublishedNote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetPublishedNoteBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublishedNoteBySlug'
type Store_GetPublishedNoteBySlug_Call struct {
	*mock.Call
}

// GetPublishedNoteBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *Store_Expecter) GetPublishedNoteBySlug(ctx interface{}, slug interface{}) *Store_GetPublishedNoteBySlug_Call {
	return &Store_GetPublishedNoteBySlug_Call{Call: _e.mock.On("GetPublishedNoteBySlug", ctx, slug)}
}

func (_c *Store_GetPublishedNoteBySlug_Call) Run(run func(ctx context.Context, slug string)) *Store_GetPublishedNoteBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetPublishedNoteBySlug_Call) Return(_a0 *model.PublishedNote, _a1 error) *Store_GetPublishedNoteBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetPublishedNoteBySlug_Call) RunAndReturn(run func(context.Context, string) (*model.PublishedNote, error)) *Store_GetPublishedNoteBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublishedNoteRecordBySlug provides a mock function with given fields: ctx, slug
func (_m *Store) GetPublishedNoteRecordBySlug(ctx context.Context, slug string) (*model.PublishedNoteRecord, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishedNoteRecordBySlug")
	}

	var r0 *model.PublishedNoteRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.PublishedNoteRecord, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.PublishedNoteRecord); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PublishedNoteRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetPublishedNoteRecordBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublishedNoteRecordBySlug'
type Store_GetPublishedNoteRecordBySlug_Call struct {
	*mock.Call
}

// GetPublishedNoteRecordBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *Store_Expecter) GetPublishedNoteRecordBySlug(ctx interface{}, slug interface{}) *Store_GetPublishedNoteRecordBySlug_Call {
	return &Store_GetPublishedNoteRecordBySlug_Call{Call: _e.mock.On("GetPublishedNoteRecordBySlug", ctx, slug)}
}

func (_c *Store_GetPublishedNoteRecordBySlug_Call) Run(run func(ctx context.Context, slug string)) *Store_GetPublishedNoteRecordBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetPublishedNoteRecordBySlug_Call) Return(_a0 *model.PublishedNoteRecord, _a1 error) *Store_GetPublishedNoteRecordBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetPublishedNoteRecordBySlug_Call) RunAndReturn(run func(context.Context, string) (*model.PublishedNoteRecord, error)) *Store_GetPublishedNoteRecordBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetVaultSalt provides a mock function with given fields: ctx, userID
func (_m *Store) GetVaultSalt(ctx context.Context, userID string) (string, bool, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetVaultSalt")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, bool, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Store_GetVaultSalt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVaultSalt'
type Store_GetVaultSalt_Call struct {
	*mock.Call
}

// GetVaultSalt is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) GetVaultSalt(ctx interface{}, userID interface{}) *Store_GetVaultSalt_Call {
	return &Store_GetVaultSalt_Call{Call: _e.mock.On("GetVaultSalt", ctx, userID)}
}

func (_c *Store_GetVaultSalt_Call) Run(run func(ctx context.Context, userID string)) *Store_GetVaultSalt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetVaultSalt_Call) Return(saltB64 string, ok bool, err error) *Store_GetVaultSalt_Call {
	_c.Call.Return(saltB64, ok, err)
	return _c
}

func (_c *Store_GetVaultSalt_Call) RunAndReturn(run func(context.Context, string) (string, bool, error)) *Store_GetVaultSalt_Call {
	_c.Call.Return(run)
	return _c
}

// InitVault provides a mock function with given fields: ctx, userID
func (_m *Store) InitVault(ctx context.Context, userID string) (string, bool, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for InitVault")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, bool, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Store_InitVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitVault'
type Store_InitVault_Call struct {
	*mock.Call
}

// InitVault is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) InitVault(ctx interface{}, userID interface{}) *Store_InitVault_Call {
	return &Store_InitVault_Call{Call: _e.mock.On("InitVault", ctx, userID)}
}

func (_c *Store_InitVault_Call) Run(run func(ctx context.Context, userID string)) *Store_InitVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_InitVault_Call) Return(saltB64 string, initialized bool, err error) *Store_InitVault_Call {
	_c.Call.Return(saltB64, initialized, err)
	return _c
}

func (_c *Store_InitVault_Call) RunAndReturn(run func(context.Context, string) (string, bool, error)) *Store_InitVault_Call {
	_c.Call.Return(run)
	return _c
}

// ListNoteAttachments provides a mock function with given fields: ctx, userID, noteID
func (_m *Store) ListNoteAttachments(ctx context.Context, userID string, noteID string) ([]model.NoteAttachmentSummary, error) {
	ret := _m.Called(ctx, userID, noteID)

	if len(ret) == 0 {
		panic("no return value specified for ListNoteAttachments")
	}

	var r0 []model.NoteAttachmentSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.NoteAttachmentSummary, error)); ok {
		return rf(ctx, userID, noteID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.NoteAttachmentSummary); ok {
		r0 = rf(ctx, userID, noteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.NoteAttachmentSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, noteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListNoteAttachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNoteAttachments'
type Store_ListNoteAttachments_Call struct {
	*mock.Call
}

// ListNoteAttachments is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - noteID string
func (_e *Store_Expecter) ListNoteAttachments(ctx interface{}, userID interface{}, noteID interface{}) *Store_ListNoteAttachments_Call {
	return &Store_ListNoteAttachments_Call{Call: _e.mock.On("ListNoteAttachments", ctx, userID, noteID)}
}

func (_c *Store_ListNoteAttachments_Call) Run(run func(ctx context.Context, userID string, noteID string)) *Store_ListNoteAttachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_ListNoteAttachments_Call) Return(_a0 []model.NoteAttachmentSummary, _a1 error) *Store_ListNoteAttachments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListNoteAttachments_Call) RunAndReturn(run func(context.Context, string, string) ([]model.NoteAttachmentSummary, error)) *Store_ListNoteAttachments_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotes provides a mock function with given fields: ctx, userID
func (_m *Store) ListNotes(ctx context.Context, userID string) ([]model.NoteSummary, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListNotes")
	}

	var r0 []model.NoteSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.NoteSummary, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.NoteSummary); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.NoteSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListNotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotes'
type Store_ListNotes_Call struct {
	*mock.Call
}

// ListNotes is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) ListNotes(ctx interface{}, userID interface{}) *Store_ListNotes_Call {
	return &Store_ListNotes_Call{Call: _e.mock.On("ListNotes", ctx, userID)}
}

func (_c *Store_ListNotes_Call) Run(run func(ctx context.Context, userID string)) *Store_ListNotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ListNotes_Call) Return(_a0 []model.NoteSummary, _a1 error) *Store_ListNotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListNotes_Call) RunAndReturn(run func(context.Context, string) ([]model.NoteSummary, error)) *Store_ListNotes_Call {
	_c.Call.Return(run)
	return _c
}

// PutNoteAttachment provides a mock function with given fields: ctx, attachment
func (_m *Store) PutNoteAttachment(ctx context.Context, attachment model.NoteAttachment) (*model.NoteAttachment, error) {
	ret := _m.Called(ctx, attachment)

	if len(ret) == 0 {
		panic("no return value specified for PutNoteAttachment")
	}

	var r0 *model.NoteAttachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.NoteAttachment) (*model.NoteAttachment, error)); ok {
		return rf(ctx, attachment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.NoteAttachment) *model.NoteAttachment); ok {
		r0 = rf(ctx, attachment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NoteAttachment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.NoteAttachment) error); ok {
		r1 = rf(ctx, attachment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_PutNoteAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutNoteAttachment'
type Store_PutNoteAttachment_Call struct {
	*mock.Call
}

// PutNoteAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - attachment model.NoteAttachment
func (_e *Store_Expecter) PutNoteAttachment(ctx interface{}, attachment interface{}) *Store_PutNoteAttachment_Call {
	return &Store_PutNoteAttachment_Call{Call: _e.mock.On("PutNoteAttachment", ctx, attachment)}
}

func (_c *Store_PutNoteAttachment_Call) Run(run func(ctx context.Context, attachment model.NoteAttachment)) *Store_PutNoteAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.NoteAttachment))
	})
	return _c
}

func (_c *Store_PutNoteAttachment_Call) Return(_a0 *model.NoteAttachment, _a1 error) *Store_PutNoteAttachment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_PutNoteAttachment_Call) RunAndReturn(run func(context.Context, model.NoteAttachment) (*model.NoteAttachment, error)) *Store_PutNoteAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// ShareNoteToWeb provides a mock function with given fields: ctx, userID, noteID, plaintext, publicBaseURL, meta, assets
func (_m *Store) ShareNoteToWeb(ctx context.Context, userID string, noteID string, plaintext string, publicBaseURL string, meta model.PublishMeta, assets []model.PublishedAttachment) (*model.ShareToWebResult, error) {
	ret := _m.Called(ctx, userID, noteID, plaintext, publicBaseURL, meta, assets)

	if len(ret) == 0 {
		panic("no return value specified for ShareNoteToWeb")
	}

	var r0 *model.ShareToWebResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, model.PublishMeta, []model.PublishedAttachment) (*model.ShareToWebResult, error)); ok {
		return rf(ctx, userID, noteID, plaintext, publicBaseURL, meta, assets)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, model.PublishMeta, []model.PublishedAttachment) *model.ShareToWebResult); ok {
		r0 = rf(ctx, userID, noteID, plaintext, publicBaseURL, meta, assets)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShareToWebResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, model.PublishMeta, []model.PublishedAttachment) error); ok {
		r1 = rf(ctx, userID, noteID, plaintext, publicBaseURL, meta, assets)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ShareNoteToWeb_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareNoteToWeb'
type Store_ShareNoteToWeb_Call struct {
	*mock.Call
}

// ShareNoteToWeb is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - noteID string
//   - plaintext string
//   - publicBaseURL string
//   - meta model.PublishMeta
//   - assets []model.PublishedAttachment
func (_e *Store_Expecter) ShareNoteToWeb(ctx interface{}, userID interface{}, noteID interface{}, plaintext interface{}, publicBaseURL interface{}, meta interface{}, assets interface{}) *Store_ShareNoteToWeb_Call {
	return &Store_ShareNoteToWeb_Call{Call: _e.mock.On("ShareNoteToWeb", ctx, userID, noteID, plaintext, publicBaseURL, meta, assets)}
}

func (_c *Store_ShareNoteToWeb_Call) Run(run func(ctx context.Context, userID string, noteID string, plaintext string, publicBaseURL string, meta model.PublishMeta, assets []model.PublishedAttachment)) *Store_ShareNoteToWeb_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(model.PublishMeta), args[6].([]model.PublishedAttachment))
	})
	return _c
}

func (_c *Store_ShareNoteToWeb_Call) Return(_a0 *model.ShareToWebResult, _a1 error) *Store_ShareNoteToWeb_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ShareNoteToWeb_Call) RunAndReturn(run func(context.Context, string, string, string, string, model.PublishMeta, []model.PublishedAttachment) (*model.ShareToWebResult, error)) *Store_ShareNoteToWeb_Call {
	_c.Call.Return(run)
	return _c
}

// UnpublishNote provides a mock function with given fields: ctx, userID, noteID
func (_m *Store) UnpublishNote(ctx context.Context, userID string, noteID string) error {
	ret := _m.Called(ctx, userID, noteID)

	if len(ret) == 0 {
		panic("no return value specified for UnpublishNote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, noteID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_UnpublishNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpublishNote'
type Store_UnpublishNote_Call struct {
	*mock.Call
}

// UnpublishNote is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - noteID string
func (_e *Store_Expecter) UnpublishNote(ctx interface{}, userID interface{}, noteID interface{}) *Store_UnpublishNote_Call {
	return &Store_UnpublishNote_Call{Call: _e.mock.On("UnpublishNote", ctx, userID, noteID)}
}

func (_c *Store_UnpublishNote_Call) Run(run func(ctx context.Context, userID string, noteID string)) *Store_UnpublishNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_UnpublishNote_Call) Return(_a0 error) *Store_UnpublishNote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_UnpublishNote_Call) RunAndReturn(run func(context.Context, string, string) error) *Store_UnpublishNote_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNote provides a mock function with given fields: ctx, userID, id, title, body, links
func (_m *Store) UpdateNote(ctx context.Context, userID string, id string, title string, body string, links []model.WikiLinkRef) (*model.Note, error) {
	ret := _m.Called(ctx, userID, id, title, body, links)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNote")
	}

	var r0 *model.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, []model.WikiLinkRef) (*model.Note, error)); ok {
		return rf(ctx, userID, id, title, body, links)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, []model.WikiLinkRef) *model.Note); ok {
		r0 = rf(ctx, userID, id, title, body, links)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, []model.WikiLinkRef) error); ok {
		r1 = rf(ctx, userID, id, title, body, links)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_UpdateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNote'
type Store_UpdateNote_Call struct {
	*mock.Call
}

// UpdateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - title string
//   - body string
//   - links []model.WikiLinkRef
func (_e *Store_Expecter) UpdateNote(ctx interface{}, userID interface{}, id interface{}, title interface{}, body interface{}, links interface{}) *Store_UpdateNote_Call {
	return &Store_UpdateNote_Call{Call: _e.mock.On("UpdateNote", ctx, userID, id, title, body, links)}
}

func (_c *Store_UpdateNote_Call) Run(run func(ctx context.Context, userID string, id string, title string, body string, links []model.WikiLinkRef)) *Store_UpdateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].([]model.WikiLinkRef))
	})
	return _c
}

func (_c *Store_UpdateNote_Call) Return(_a0 *model.Note, _a1 error) *Store_UpdateNote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_UpdateNote_Call) RunAndReturn(run func(context.Context, string, string, string, string, []model.WikiLinkRef) (*model.Note, error)) *Store_UpdateNote_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
