// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	authmodel "github.com/dobriygolang/project-nordly/services/identity/internal/auth/model"
	model "github.com/dobriygolang/project-nordly/services/identity/internal/user/model"
	mock "github.com/stretchr/testify/mock"
)

// TokenIssuer is an autogenerated mock type for the TokenIssuer type
type TokenIssuer struct {
	mock.Mock
}

type TokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuer) EXPECT() *TokenIssuer_Expecter {
	return &TokenIssuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: ctx, user
func (_m *TokenIssuer) Issue(ctx context.Context, user *model.User) (*authmodel.AuthResult, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 *authmodel.AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) (*authmodel.AuthResult, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) *authmodel.AuthResult); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authmodel.AuthResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type TokenIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *TokenIssuer_Expecter) Issue(ctx interface{}, user interface{}) *TokenIssuer_Issue_Call {
	return &TokenIssuer_Issue_Call{Call: _e.mock.On("Issue", ctx, user)}
}

func (_c *TokenIssuer_Issue_Call) Run(run func(ctx context.Context, user *model.User)) *TokenIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *TokenIssuer_Issue_Call) Return(_a0 *authmodel.AuthResult, _a1 error) *TokenIssuer_Issue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenIssuer_Issue_Call) RunAndReturn(run func(context.Context, *model.User) (*authmodel.AuthResult, error)) *TokenIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenIssuer creates a new instance of TokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuer {
	mock := &TokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
