// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UsernameAllocator is an autogenerated mock type for the UsernameAllocator type
type UsernameAllocator struct {
	mock.Mock
}

type UsernameAllocator_Expecter struct {
	mock *mock.Mock
}

func (_m *UsernameAllocator) EXPECT() *UsernameAllocator_Expecter {
	return &UsernameAllocator_Expecter{mock: &_m.Mock}
}

// Allocate provides a mock function with given fields: ctx, candidates
func (_m *UsernameAllocator) Allocate(ctx context.Context, candidates ...string) (string, error) {
	_va := make([]interface{}, len(candidates))
	for _i := range candidates {
		_va[_i] = candidates[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Allocate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) (string, error)); ok {
		return rf(ctx, candidates...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...string) string); ok {
		r0 = rf(ctx, candidates...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = rf(ctx, candidates...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsernameAllocator_Allocate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allocate'
type UsernameAllocator_Allocate_Call struct {
	*mock.Call
}

// Allocate is a helper method to define mock.On call
//   - ctx context.Context
//   - candidates ...string
func (_e *UsernameAllocator_Expecter) Allocate(ctx interface{}, candidates ...interface{}) *UsernameAllocator_Allocate_Call {
	return &UsernameAllocator_Allocate_Call{Call: _e.mock.On("Allocate",
		append([]interface{}{ctx}, candidates...)...)}
}

func (_c *UsernameAllocator_Allocate_Call) Run(run func(ctx context.Context, candidates ...string)) *UsernameAllocator_Allocate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *UsernameAllocator_Allocate_Call) Return(_a0 string, _a1 error) *UsernameAllocator_Allocate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsernameAllocator_Allocate_Call) RunAndReturn(run func(context.Context, ...string) (string, error)) *UsernameAllocator_Allocate_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsernameAllocator creates a new instance of UsernameAllocator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsernameAllocator(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsernameAllocator {
	mock := &UsernameAllocator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
