// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/notes/internal/notes/model"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// ShareNoteToWeb provides a mock function with given fields: ctx, userID, noteID, plaintext, publicBaseURL, meta, assets
func (_m *Store) ShareNoteToWeb(ctx context.Context, userID string, noteID string, plaintext string, publicBaseURL string, meta model.PublishMeta, assets []model.PublishedAttachment) (*model.ShareToWebResult, error) {
	ret := _m.Called(ctx, userID, noteID, plaintext, publicBaseURL, meta, assets)

	if len(ret) == 0 {
		panic("no return value specified for ShareNoteToWeb")
	}

	var r0 *model.ShareToWebResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, model.PublishMeta, []model.PublishedAttachment) (*model.ShareToWebResult, error)); ok {
		return rf(ctx, userID, noteID, plaintext, publicBaseURL, meta, assets)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, model.PublishMeta, []model.PublishedAttachment) *model.ShareToWebResult); ok {
		r0 = rf(ctx, userID, noteID, plaintext, publicBaseURL, meta, assets)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShareToWebResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, model.PublishMeta, []model.PublishedAttachment) error); ok {
		r1 = rf(ctx, userID, noteID, plaintext, publicBaseURL, meta, assets)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ShareNoteToWeb_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareNoteToWeb'
type Store_ShareNoteToWeb_Call struct {
	*mock.Call
}

// ShareNoteToWeb is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - noteID string
//   - plaintext string
//   - publicBaseURL string
//   - meta model.PublishMeta
//   - assets []model.PublishedAttachment
func (_e *Store_Expecter) ShareNoteToWeb(ctx interface{}, userID interface{}, noteID interface{}, plaintext interface{}, publicBaseURL interface{}, meta interface{}, assets interface{}) *Store_ShareNoteToWeb_Call {
	return &Store_ShareNoteToWeb_Call{Call: _e.mock.On("ShareNoteToWeb", ctx, userID, noteID, plaintext, publicBaseURL, meta, assets)}
}

func (_c *Store_ShareNoteToWeb_Call) Run(run func(ctx context.Context, userID string, noteID string, plaintext string, publicBaseURL string, meta model.PublishMeta, assets []model.PublishedAttachment)) *Store_ShareNoteToWeb_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(model.PublishMeta), args[6].([]model.PublishedAttachment))
	})
	return _c
}

func (_c *Store_ShareNoteToWeb_Call) Return(_a0 *model.ShareToWebResult, _a1 error) *Store_ShareNoteToWeb_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ShareNoteToWeb_Call) RunAndReturn(run func(context.Context, string, string, string, string, model.PublishMeta, []model.PublishedAttachment) (*model.ShareToWebResult, error)) *Store_ShareNoteToWeb_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
