// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	time "time"

	model "github.com/dobriygolang/project-nordly/services/focus/internal/focus/model"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// EndSession provides a mock function with given fields: ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt
func (_m *Store) EndSession(ctx context.Context, userID string, sessionID string, secondsFocused int, pomodorosCompleted int, endedAt time.Time) (*model.Session, model.SessionEndOutcome, error) {
	ret := _m.Called(ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt)

	if len(ret) == 0 {
		panic("no return value specified for EndSession")
	}

	var r0 *model.Session
	var r1 model.SessionEndOutcome
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int, time.Time) (*model.Session, model.SessionEndOutcome, error)); ok {
		return rf(ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int, time.Time) *model.Session); ok {
		r0 = rf(ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int, time.Time) model.SessionEndOutcome); ok {
		r1 = rf(ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt)
	} else {
		r1 = ret.Get(1).(model.SessionEndOutcome)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, int, time.Time) error); ok {
		r2 = rf(ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Store_EndSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndSession'
type Store_EndSession_Call struct {
	*mock.Call
}

// EndSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
//   - secondsFocused int
//   - pomodorosCompleted int
//   - endedAt time.Time
func (_e *Store_Expecter) EndSession(ctx interface{}, userID interface{}, sessionID interface{}, secondsFocused interface{}, pomodorosCompleted interface{}, endedAt interface{}) *Store_EndSession_Call {
	return &Store_EndSession_Call{Call: _e.mock.On("EndSession", ctx, userID, sessionID, secondsFocused, pomodorosCompleted, endedAt)}
}

func (_c *Store_EndSession_Call) Run(run func(ctx context.Context, userID string, sessionID string, secondsFocused int, pomodorosCompleted int, endedAt time.Time)) *Store_EndSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int), args[5].(time.Time))
	})
	return _c
}

func (_c *Store_EndSession_Call) Return(_a0 *model.Session, _a1 model.SessionEndOutcome, _a2 error) *Store_EndSession_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Store_EndSession_Call) RunAndReturn(run func(context.Context, string, string, int, int, time.Time) (*model.Session, model.SessionEndOutcome, error)) *Store_EndSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
