// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	time "time"

	model "github.com/dobriygolang/project-nordly/services/focus/internal/focus/model"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// GetStats provides a mock function with given fields: ctx, userID, upTo
func (_m *Store) GetStats(ctx context.Context, userID string, upTo time.Time) (*model.Stats, error) {
	ret := _m.Called(ctx, userID, upTo)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *model.Stats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*model.Stats, error)); ok {
		return rf(ctx, userID, upTo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *model.Stats); ok {
		r0 = rf(ctx, userID, upTo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Stats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, userID, upTo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type Store_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - upTo time.Time
func (_e *Store_Expecter) GetStats(ctx interface{}, userID interface{}, upTo interface{}) *Store_GetStats_Call {
	return &Store_GetStats_Call{Call: _e.mock.On("GetStats", ctx, userID, upTo)}
}

func (_c *Store_GetStats_Call) Run(run func(ctx context.Context, userID string, upTo time.Time)) *Store_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *Store_GetStats_Call) Return(_a0 *model.Stats, _a1 error) *Store_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetStats_Call) RunAndReturn(run func(context.Context, string, time.Time) (*model.Stats, error)) *Store_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
