// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RefreshTokenSaver is an autogenerated mock type for the RefreshTokenSaver type
type RefreshTokenSaver struct {
	mock.Mock
}

type RefreshTokenSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenSaver) EXPECT() *RefreshTokenSaver_Expecter {
	return &RefreshTokenSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, tokenHash, userID, ttlSeconds
func (_m *RefreshTokenSaver) Save(ctx context.Context, tokenHash string, userID string, ttlSeconds int) error {
	ret := _m.Called(ctx, tokenHash, userID, ttlSeconds)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = rf(ctx, tokenHash, userID, ttlSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type RefreshTokenSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - userID string
//   - ttlSeconds int
func (_e *RefreshTokenSaver_Expecter) Save(ctx interface{}, tokenHash interface{}, userID interface{}, ttlSeconds interface{}) *RefreshTokenSaver_Save_Call {
	return &RefreshTokenSaver_Save_Call{Call: _e.mock.On("Save", ctx, tokenHash, userID, ttlSeconds)}
}

func (_c *RefreshTokenSaver_Save_Call) Run(run func(ctx context.Context, tokenHash string, userID string, ttlSeconds int)) *RefreshTokenSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *RefreshTokenSaver_Save_Call) Return(_a0 error) *RefreshTokenSaver_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenSaver_Save_Call) RunAndReturn(run func(context.Context, string, string, int) error) *RefreshTokenSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefreshTokenSaver creates a new instance of RefreshTokenSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenSaver {
	mock := &RefreshTokenSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
