// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UsernameExistsChecker is an autogenerated mock type for the UsernameExistsChecker type
type UsernameExistsChecker struct {
	mock.Mock
}

type UsernameExistsChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *UsernameExistsChecker) EXPECT() *UsernameExistsChecker_Expecter {
	return &UsernameExistsChecker_Expecter{mock: &_m.Mock}
}

// UsernameExists provides a mock function with given fields: ctx, username
func (_m *UsernameExistsChecker) UsernameExists(ctx context.Context, username string) (bool, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for UsernameExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsernameExistsChecker_UsernameExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UsernameExists'
type UsernameExistsChecker_UsernameExists_Call struct {
	*mock.Call
}

// UsernameExists is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *UsernameExistsChecker_Expecter) UsernameExists(ctx interface{}, username interface{}) *UsernameExistsChecker_UsernameExists_Call {
	return &UsernameExistsChecker_UsernameExists_Call{Call: _e.mock.On("UsernameExists", ctx, username)}
}

func (_c *UsernameExistsChecker_UsernameExists_Call) Run(run func(ctx context.Context, username string)) *UsernameExistsChecker_UsernameExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UsernameExistsChecker_UsernameExists_Call) Return(_a0 bool, _a1 error) *UsernameExistsChecker_UsernameExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsernameExistsChecker_UsernameExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *UsernameExistsChecker_UsernameExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsernameExistsChecker creates a new instance of UsernameExistsChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsernameExistsChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsernameExistsChecker {
	mock := &UsernameExistsChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
