// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/tracker/internal/tracker/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Google is an autogenerated mock type for the Google type
type Google struct {
	mock.Mock
}

type Google_Expecter struct {
	mock *mock.Mock
}

func (_m *Google) EXPECT() *Google_Expecter {
	return &Google_Expecter{mock: &_m.Mock}
}

// Configured provides a mock function with no fields
func (_m *Google) Configured() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Configured")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Google_Configured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configured'
type Google_Configured_Call struct {
	*mock.Call
}

// Configured is a helper method to define mock.On call
func (_e *Google_Expecter) Configured() *Google_Configured_Call {
	return &Google_Configured_Call{Call: _e.mock.On("Configured")}
}

func (_c *Google_Configured_Call) Run(run func()) *Google_Configured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Google_Configured_Call) Return(_a0 bool) *Google_Configured_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Google_Configured_Call) RunAndReturn(run func() bool) *Google_Configured_Call {
	_c.Call.Return(run)
	return _c
}

// ListCalendars provides a mock function with given fields: ctx, refreshToken
func (_m *Google) ListCalendars(ctx context.Context, refreshToken string) ([]model.Calendar, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for ListCalendars")
	}

	var r0 []model.Calendar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Calendar, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Calendar); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Calendar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Google_ListCalendars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCalendars'
type Google_ListCalendars_Call struct {
	*mock.Call
}

// ListCalendars is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *Google_Expecter) ListCalendars(ctx interface{}, refreshToken interface{}) *Google_ListCalendars_Call {
	return &Google_ListCalendars_Call{Call: _e.mock.On("ListCalendars", ctx, refreshToken)}
}

func (_c *Google_ListCalendars_Call) Run(run func(ctx context.Context, refreshToken string)) *Google_ListCalendars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Google_ListCalendars_Call) Return(_a0 []model.Calendar, _a1 error) *Google_ListCalendars_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Google_ListCalendars_Call) RunAndReturn(run func(context.Context, string) ([]model.Calendar, error)) *Google_ListCalendars_Call {
	_c.Call.Return(run)
	return _c
}

// SyncEvents provides a mock function with given fields: ctx, refreshToken, calendarID, syncToken, timeMin, timeMax
func (_m *Google) SyncEvents(ctx context.Context, refreshToken string, calendarID string, syncToken string, timeMin time.Time, timeMax time.Time) (model.CalendarSyncResult, error) {
	ret := _m.Called(ctx, refreshToken, calendarID, syncToken, timeMin, timeMax)

	if len(ret) == 0 {
		panic("no return value specified for SyncEvents")
	}

	var r0 model.CalendarSyncResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time, time.Time) (model.CalendarSyncResult, error)); ok {
		return rf(ctx, refreshToken, calendarID, syncToken, timeMin, timeMax)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time, time.Time) model.CalendarSyncResult); ok {
		r0 = rf(ctx, refreshToken, calendarID, syncToken, timeMin, timeMax)
	} else {
		r0 = ret.Get(0).(model.CalendarSyncResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, refreshToken, calendarID, syncToken, timeMin, timeMax)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Google_SyncEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncEvents'
type Google_SyncEvents_Call struct {
	*mock.Call
}

// SyncEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - calendarID string
//   - syncToken string
//   - timeMin time.Time
//   - timeMax time.Time
func (_e *Google_Expecter) SyncEvents(ctx interface{}, refreshToken interface{}, calendarID interface{}, syncToken interface{}, timeMin interface{}, timeMax interface{}) *Google_SyncEvents_Call {
	return &Google_SyncEvents_Call{Call: _e.mock.On("SyncEvents", ctx, refreshToken, calendarID, syncToken, timeMin, timeMax)}
}

func (_c *Google_SyncEvents_Call) Run(run func(ctx context.Context, refreshToken string, calendarID string, syncToken string, timeMin time.Time, timeMax time.Time)) *Google_SyncEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(time.Time), args[5].(time.Time))
	})
	return _c
}

func (_c *Google_SyncEvents_Call) Return(_a0 model.CalendarSyncResult, _a1 error) *Google_SyncEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Google_SyncEvents_Call) RunAndReturn(run func(context.Context, string, string, string, time.Time, time.Time) (model.CalendarSyncResult, error)) *Google_SyncEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewGoogle creates a new instance of Google. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogle(t interface {
	mock.TestingT
	Cleanup(func())
}) *Google {
	mock := &Google{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
