// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/tracker/internal/tracker/model"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// ApplyGoogleCalendarSyncDelta provides a mock function with given fields: ctx, userID, delta
func (_m *Store) ApplyGoogleCalendarSyncDelta(ctx context.Context, userID string, delta model.CalendarSyncDelta) error {
	ret := _m.Called(ctx, userID, delta)

	if len(ret) == 0 {
		panic("no return value specified for ApplyGoogleCalendarSyncDelta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CalendarSyncDelta) error); ok {
		r0 = rf(ctx, userID, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_ApplyGoogleCalendarSyncDelta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyGoogleCalendarSyncDelta'
type Store_ApplyGoogleCalendarSyncDelta_Call struct {
	*mock.Call
}

// ApplyGoogleCalendarSyncDelta is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - delta model.CalendarSyncDelta
func (_e *Store_Expecter) ApplyGoogleCalendarSyncDelta(ctx interface{}, userID interface{}, delta interface{}) *Store_ApplyGoogleCalendarSyncDelta_Call {
	return &Store_ApplyGoogleCalendarSyncDelta_Call{Call: _e.mock.On("ApplyGoogleCalendarSyncDelta", ctx, userID, delta)}
}

func (_c *Store_ApplyGoogleCalendarSyncDelta_Call) Run(run func(ctx context.Context, userID string, delta model.CalendarSyncDelta)) *Store_ApplyGoogleCalendarSyncDelta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CalendarSyncDelta))
	})
	return _c
}

func (_c *Store_ApplyGoogleCalendarSyncDelta_Call) Return(_a0 error) *Store_ApplyGoogleCalendarSyncDelta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_ApplyGoogleCalendarSyncDelta_Call) RunAndReturn(run func(context.Context, string, model.CalendarSyncDelta) error) *Store_ApplyGoogleCalendarSyncDelta_Call {
	_c.Call.Return(run)
	return _c
}

// GetGoogleCalendarSyncToken provides a mock function with given fields: ctx, userID, calendarID
func (_m *Store) GetGoogleCalendarSyncToken(ctx context.Context, userID string, calendarID string) (string, error) {
	ret := _m.Called(ctx, userID, calendarID)

	if len(ret) == 0 {
		panic("no return value specified for GetGoogleCalendarSyncToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, userID, calendarID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userID, calendarID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, calendarID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetGoogleCalendarSyncToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGoogleCalendarSyncToken'
type Store_GetGoogleCalendarSyncToken_Call struct {
	*mock.Call
}

// GetGoogleCalendarSyncToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - calendarID string
func (_e *Store_Expecter) GetGoogleCalendarSyncToken(ctx interface{}, userID interface{}, calendarID interface{}) *Store_GetGoogleCalendarSyncToken_Call {
	return &Store_GetGoogleCalendarSyncToken_Call{Call: _e.mock.On("GetGoogleCalendarSyncToken", ctx, userID, calendarID)}
}

func (_c *Store_GetGoogleCalendarSyncToken_Call) Run(run func(ctx context.Context, userID string, calendarID string)) *Store_GetGoogleCalendarSyncToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_GetGoogleCalendarSyncToken_Call) Return(_a0 string, _a1 error) *Store_GetGoogleCalendarSyncToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetGoogleCalendarSyncToken_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *Store_GetGoogleCalendarSyncToken_Call {
	_c.Call.Return(run)
	return _c
}

// ListGoogleConnectedSettings provides a mock function with given fields: ctx
func (_m *Store) ListGoogleConnectedSettings(ctx context.Context) ([]model.UserSettings, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListGoogleConnectedSettings")
	}

	var r0 []model.UserSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.UserSettings, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.UserSettings); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ListGoogleConnectedSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGoogleConnectedSettings'
type Store_ListGoogleConnectedSettings_Call struct {
	*mock.Call
}

// ListGoogleConnectedSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Store_Expecter) ListGoogleConnectedSettings(ctx interface{}) *Store_ListGoogleConnectedSettings_Call {
	return &Store_ListGoogleConnectedSettings_Call{Call: _e.mock.On("ListGoogleConnectedSettings", ctx)}
}

func (_c *Store_ListGoogleConnectedSettings_Call) Run(run func(ctx context.Context)) *Store_ListGoogleConnectedSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Store_ListGoogleConnectedSettings_Call) Return(_a0 []model.UserSettings, _a1 error) *Store_ListGoogleConnectedSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ListGoogleConnectedSettings_Call) RunAndReturn(run func(context.Context) ([]model.UserSettings, error)) *Store_ListGoogleConnectedSettings_Call {
	_c.Call.Return(run)
	return _c
}

// MarkGoogleReauthRequired provides a mock function with given fields: ctx, userID
func (_m *Store) MarkGoogleReauthRequired(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkGoogleReauthRequired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_MarkGoogleReauthRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkGoogleReauthRequired'
type Store_MarkGoogleReauthRequired_Call struct {
	*mock.Call
}

// MarkGoogleReauthRequired is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Store_Expecter) MarkGoogleReauthRequired(ctx interface{}, userID interface{}) *Store_MarkGoogleReauthRequired_Call {
	return &Store_MarkGoogleReauthRequired_Call{Call: _e.mock.On("MarkGoogleReauthRequired", ctx, userID)}
}

func (_c *Store_MarkGoogleReauthRequired_Call) Run(run func(ctx context.Context, userID string)) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_MarkGoogleReauthRequired_Call) Return(_a0 error) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_MarkGoogleReauthRequired_Call) RunAndReturn(run func(context.Context, string) error) *Store_MarkGoogleReauthRequired_Call {
	_c.Call.Return(run)
	return _c
}

// PruneGoogleCalendarData provides a mock function with given fields: ctx, userID, calendarIDs
func (_m *Store) PruneGoogleCalendarData(ctx context.Context, userID string, calendarIDs []string) error {
	ret := _m.Called(ctx, userID, calendarIDs)

	if len(ret) == 0 {
		panic("no return value specified for PruneGoogleCalendarData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, userID, calendarIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_PruneGoogleCalendarData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneGoogleCalendarData'
type Store_PruneGoogleCalendarData_Call struct {
	*mock.Call
}

// PruneGoogleCalendarData is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - calendarIDs []string
func (_e *Store_Expecter) PruneGoogleCalendarData(ctx interface{}, userID interface{}, calendarIDs interface{}) *Store_PruneGoogleCalendarData_Call {
	return &Store_PruneGoogleCalendarData_Call{Call: _e.mock.On("PruneGoogleCalendarData", ctx, userID, calendarIDs)}
}

func (_c *Store_PruneGoogleCalendarData_Call) Run(run func(ctx context.Context, userID string, calendarIDs []string)) *Store_PruneGoogleCalendarData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *Store_PruneGoogleCalendarData_Call) Return(_a0 error) *Store_PruneGoogleCalendarData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_PruneGoogleCalendarData_Call) RunAndReturn(run func(context.Context, string, []string) error) *Store_PruneGoogleCalendarData_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
