// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/rooms/internal/room/model"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// AddParticipant provides a mock function with given fields: ctx, p
func (_m *Store) AddParticipant(ctx context.Context, p model.Participant) (model.Participant, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for AddParticipant")
	}

	var r0 model.Participant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Participant) (model.Participant, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Participant) model.Participant); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(model.Participant)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Participant) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_AddParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddParticipant'
type Store_AddParticipant_Call struct {
	*mock.Call
}

// AddParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - p model.Participant
func (_e *Store_Expecter) AddParticipant(ctx interface{}, p interface{}) *Store_AddParticipant_Call {
	return &Store_AddParticipant_Call{Call: _e.mock.On("AddParticipant", ctx, p)}
}

func (_c *Store_AddParticipant_Call) Run(run func(ctx context.Context, p model.Participant)) *Store_AddParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Participant))
	})
	return _c
}

func (_c *Store_AddParticipant_Call) Return(_a0 model.Participant, _a1 error) *Store_AddParticipant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_AddParticipant_Call) RunAndReturn(run func(context.Context, model.Participant) (model.Participant, error)) *Store_AddParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteParticipant provides a mock function with given fields: ctx, roomID, userID
func (_m *Store) DeleteParticipant(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteParticipant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DeleteParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteParticipant'
type Store_DeleteParticipant_Call struct {
	*mock.Call
}

// DeleteParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *Store_Expecter) DeleteParticipant(ctx interface{}, roomID interface{}, userID interface{}) *Store_DeleteParticipant_Call {
	return &Store_DeleteParticipant_Call{Call: _e.mock.On("DeleteParticipant", ctx, roomID, userID)}
}

func (_c *Store_DeleteParticipant_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *Store_DeleteParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Store_DeleteParticipant_Call) Return(_a0 error) *Store_DeleteParticipant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DeleteParticipant_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *Store_DeleteParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoom provides a mock function with given fields: ctx, id
func (_m *Store) GetRoom(ctx context.Context, id uuid.UUID) (model.Room, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoom")
	}

	var r0 model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Room, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Room); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoom'
type Store_GetRoom_Call struct {
	*mock.Call
}

// GetRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Store_Expecter) GetRoom(ctx interface{}, id interface{}) *Store_GetRoom_Call {
	return &Store_GetRoom_Call{Call: _e.mock.On("GetRoom", ctx, id)}
}

func (_c *Store_GetRoom_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Store_GetRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Store_GetRoom_Call) Return(_a0 model.Room, _a1 error) *Store_GetRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetRoom_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Room, error)) *Store_GetRoom_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
