// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dobriygolang/project-nordly/services/identity/internal/user/model"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *Store) Create(ctx context.Context, user *model.User) (*model.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) (*model.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) *model.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Store_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *Store_Expecter) Create(ctx interface{}, user interface{}) *Store_Create_Call {
	return &Store_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *Store_Create_Call) Run(run func(ctx context.Context, user *model.User)) *Store_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *Store_Create_Call) Return(_a0 *model.User, _a1 error) *Store_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_Create_Call) RunAndReturn(run func(context.Context, *model.User) (*model.User, error)) *Store_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Store) GetByID(ctx context.Context, id string) (*model.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type Store_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Store_Expecter) GetByID(ctx interface{}, id interface{}) *Store_GetByID_Call {
	return &Store_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *Store_GetByID_Call) Run(run func(ctx context.Context, id string)) *Store_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetByID_Call) Return(_a0 *model.User, _a1 error) *Store_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetByID_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *Store_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTelegramID provides a mock function with given fields: ctx, telegramID
func (_m *Store) GetByTelegramID(ctx context.Context, telegramID int64) (*model.User, error) {
	ret := _m.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTelegramID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.User, error)); ok {
		return rf(ctx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.User); ok {
		r0 = rf(ctx, telegramID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetByTelegramID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTelegramID'
type Store_GetByTelegramID_Call struct {
	*mock.Call
}

// GetByTelegramID is a helper method to define mock.On call
//   - ctx context.Context
//   - telegramID int64
func (_e *Store_Expecter) GetByTelegramID(ctx interface{}, telegramID interface{}) *Store_GetByTelegramID_Call {
	return &Store_GetByTelegramID_Call{Call: _e.mock.On("GetByTelegramID", ctx, telegramID)}
}

func (_c *Store_GetByTelegramID_Call) Run(run func(ctx context.Context, telegramID int64)) *Store_GetByTelegramID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Store_GetByTelegramID_Call) Return(_a0 *model.User, _a1 error) *Store_GetByTelegramID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetByTelegramID_Call) RunAndReturn(run func(context.Context, int64) (*model.User, error)) *Store_GetByTelegramID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *Store) Update(ctx context.Context, user *model.User) (*model.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) (*model.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) *model.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Store_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *Store_Expecter) Update(ctx interface{}, user interface{}) *Store_Update_Call {
	return &Store_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *Store_Update_Call) Run(run func(ctx context.Context, user *model.User)) *Store_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *Store_Update_Call) Return(_a0 *model.User, _a1 error) *Store_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_Update_Call) RunAndReturn(run func(context.Context, *model.User) (*model.User, error)) *Store_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UsernameExists provides a mock function with given fields: ctx, username
func (_m *Store) UsernameExists(ctx context.Context, username string) (bool, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for UsernameExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_UsernameExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UsernameExists'
type Store_UsernameExists_Call struct {
	*mock.Call
}

// UsernameExists is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *Store_Expecter) UsernameExists(ctx interface{}, username interface{}) *Store_UsernameExists_Call {
	return &Store_UsernameExists_Call{Call: _e.mock.On("UsernameExists", ctx, username)}
}

func (_c *Store_UsernameExists_Call) Run(run func(ctx context.Context, username string)) *Store_UsernameExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_UsernameExists_Call) Return(_a0 bool, _a1 error) *Store_UsernameExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_UsernameExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *Store_UsernameExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
