// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RefreshTokenStore is an autogenerated mock type for the RefreshTokenStore type
type RefreshTokenStore struct {
	mock.Mock
}

type RefreshTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenStore) EXPECT() *RefreshTokenStore_Expecter {
	return &RefreshTokenStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, tokenHash
func (_m *RefreshTokenStore) Delete(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RefreshTokenStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *RefreshTokenStore_Expecter) Delete(ctx interface{}, tokenHash interface{}) *RefreshTokenStore_Delete_Call {
	return &RefreshTokenStore_Delete_Call{Call: _e.mock.On("Delete", ctx, tokenHash)}
}

func (_c *RefreshTokenStore_Delete_Call) Run(run func(ctx context.Context, tokenHash string)) *RefreshTokenStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshTokenStore_Delete_Call) Return(_a0 error) *RefreshTokenStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *RefreshTokenStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserID provides a mock function with given fields: ctx, tokenHash
func (_m *RefreshTokenStore) GetUserID(ctx context.Context, tokenHash string) (string, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshTokenStore_GetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserID'
type RefreshTokenStore_GetUserID_Call struct {
	*mock.Call
}

// GetUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *RefreshTokenStore_Expecter) GetUserID(ctx interface{}, tokenHash interface{}) *RefreshTokenStore_GetUserID_Call {
	return &RefreshTokenStore_GetUserID_Call{Call: _e.mock.On("GetUserID", ctx, tokenHash)}
}

func (_c *RefreshTokenStore_GetUserID_Call) Run(run func(ctx context.Context, tokenHash string)) *RefreshTokenStore_GetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshTokenStore_GetUserID_Call) Return(_a0 string, _a1 error) *RefreshTokenStore_GetUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshTokenStore_GetUserID_Call) RunAndReturn(run func(context.Context, string) (string, error)) *RefreshTokenStore_GetUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, tokenHash, userID, ttlSeconds
func (_m *RefreshTokenStore) Save(ctx context.Context, tokenHash string, userID string, ttlSeconds int) error {
	ret := _m.Called(ctx, tokenHash, userID, ttlSeconds)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = rf(ctx, tokenHash, userID, ttlSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type RefreshTokenStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - userID string
//   - ttlSeconds int
func (_e *RefreshTokenStore_Expecter) Save(ctx interface{}, tokenHash interface{}, userID interface{}, ttlSeconds interface{}) *RefreshTokenStore_Save_Call {
	return &RefreshTokenStore_Save_Call{Call: _e.mock.On("Save", ctx, tokenHash, userID, ttlSeconds)}
}

func (_c *RefreshTokenStore_Save_Call) Run(run func(ctx context.Context, tokenHash string, userID string, ttlSeconds int)) *RefreshTokenStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *RefreshTokenStore_Save_Call) Return(_a0 error) *RefreshTokenStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenStore_Save_Call) RunAndReturn(run func(context.Context, string, string, int) error) *RefreshTokenStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefreshTokenStore creates a new instance of RefreshTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenStore {
	mock := &RefreshTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
